### ISSUE TITLE
Service worker Failed to load resource: net::ERR_UNSAFE_REDIRECT

### ISSUE THREAD

**Issue by chebaby** [w3c/ServiceWorker#1001]
would you please tell me what i did wrong with my service worker installation, i have those errors appear in chrome console (see the image).

`The script resource is behind a redirect, which is disallowed.                                           service-worker.js:1`
`Failed to load resource: net::ERR_UNSAFE_REDIRECT    https://harampress.com/post/45/service-worker.js`

i use Laravel framework in backend if that could help 

thank you.

[image](https://harampress.com/uploads/files/shares/service%20worker.png)

**Comment by wanderview** [comment]
I don't think the spec forbids redirects on the script.  Do you get this error in firefox?  This may be a chrome bug.

**Comment by wanderview** [comment]
Oh, I was looking at `Fetch a classic worker script`, but the service worker spec does say to use `error` for the redirect mode.  So I guess this is spec'd.

**Comment by chebaby** [comment]
@wanderview  i don't see this error anywhere in firefox console (developer edition - version 51.0a2), like you said it could be a bug with chrome console, maybe, i really don't know.

just to know that my service-worker.js is in the root of the website, works fine on home page no errors on chrome console, but the moment i try to navigate to a post for example, those two errors appears.
knowing that i use sw-precache and sw-toolbox, i generate the service worker useing sw-precache with gulp.

**Comment by wanderview** [comment]
Is this a blog?  Do you really have a service worker hosted for each post?  The URL in your image is `/post/67/serviceworker.js`.

**Comment by chebaby** [comment]
yes it's a sort of blog
No, i don't really have a service worker hosted for each post, i have one service-worker.js in the root of my website.

**Comment by wanderview** [comment]
Ok, then perhaps chrome is complaining about getting a 404 for the service worker script?  It seems you might be registering a non-existent script from your blog post documents.  Is your register() call to `/serviceworker.js' or just `serviceworker.js'?  What does your local server see?

**Comment by chebaby** [comment]
sorry @wanderview  but i really didn't get what you're saying, would you please reform you answer, thank you

**Comment by Huxpro** [comment]
What @wanderview means is that when you do 

```
navigator.serviceWorker.register('/sw.js')
```

The actually requesting URL is the `sw.js` located in the root

but when you do 

```
navigator.serviceWorker.register('sw.js')
```

This is actually a Relative URL so what you actually request might be `/post/blah/sw.js`

**Comment by chebaby** [comment]
@wanderview  @Huxpro thank you for your help,
@Huxpro thank you for clarifying @wanderview 's answer ^^ 
i added the slash and it look like the two error messages disappeared
