### ISSUE TITLE
Behavior of the onfetch setter regarding no-fetch service workers

### ISSUE THREAD

**Issue by catalinb** [w3c/ServiceWorker#1004]
With the changes discussed in #718 addEventListener should throw unless called during the script's initial evaluation. What should be the behavior of setting the onfetch event handler?

I'm guessing it should throw as well, but this was not included in the spec.

from https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-attributes
> When an event handler H of an element or object T implementing the EventTarget interface is first set to a non-null value, the user agent must append an event listener to the list of event listeners associated with T with type set to the event handler event type corresponding to H and callback set to the event handler processing algorithm defined below. 

This can be changed to use addEventListener for adding the event listener.

**Comment by annevk** [comment]
This should be fixed together with https://github.com/whatwg/dom/issues/371.

**Comment by jungkees** [comment]
Thanks for spotting. I'll follow up on this after clarifying https://github.com/whatwg/dom/issues/371.

**Comment by annevk** [comment]
What's the status here @jungkees? Would be good to sort this out.

**Comment by jungkees** [comment]
> When an event handler H of an element or object T implementing the EventTarget interface is first set to a non-null value

> Event handler IDL attributes, on setting, must set the corresponding event handler to their new value

Yeah, the idea is to add the following step to the above places:

"Throw when T is a ServiceWorkerGlobalScope object, type is an event type in the while list, and the SW's has ever been evaluated flag is set."

But this isn't decided yet. We should conclude what the better design would be in https://github.com/whatwg/dom/issues/371.

**Comment by annevk** [comment]
Since nobody else took this up I wrote the necessary patches for DOM and HTML.

**Comment by annevk** [comment]
OP is now addressed, but I think we should leave this open until someone has addressed the questions I raised in https://github.com/whatwg/dom/issues/371 and there's tests covering exactly what we want to be doing here.

**Comment by annevk** [comment]
Well, that issue isn't fixed yet and that decision is being contested by bz in that issue. That's why that text hasn't been touched thus far.

**Comment by annevk** [comment]
Also, are there any tests?

**Comment by jungkees** [comment]
That bit was posed by the OP: https://github.com/whatwg/dom/issues/371#issue-188315804. Allowing the event target to be any object doesn't make sense, and the proposed change is in the direction of a solution.

I'll need to check out for tests.

**Comment by annevk** [comment]
I think throwing in general doesn't make sense, even for the global object. As bz points out, you could have custom events that you might want to register at a later time.

**Comment by jungkees** [comment]
Closing via https://github.com/whatwg/html/commit/9a2a66cd8f8ddfa4c35d784bcda5c080e82aad38, https://github.com/web-platform-tests/wpt/commit/bc28ef58a83706de626d3d69d53cb2d0fd189141, and https://github.com/whatwg/dom/pull/653.
