### ISSUE TITLE
consider exposing a type attribute on Client

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1005]
Currently `Clients.matchAll()` considers three different types of Client objects:

1. Window
2. DedicatedWorker
3. SharedWorker

Currently its only possible to differentiate the Window client using `instanceof WindowClient`.  Since the algorithm operates on the type, though, it would be nice to expose it for dedicated and shared workers as well.

So, something like:

```
interface Client
{
  readonly attribute DOMString type;
}
```

The value would match those used in `Clients.matchAll()`.

As a side note, I find it annoying that "worker" is mapped to DedicatedWorker.  I think it would have been nicer to use "dedicatedworker" and make "worker" map to all Worker types.

**Comment by annevk** [comment]
Why? Constructors are Worker and SharedWorker.

**Comment by wanderview** [comment]
> Why? Constructors are Worker and SharedWorker.

I guess I was thinking of how [Exposed] works in webidl.

Anyway, the naming of the type is a side issue to the main idea here.

**Comment by jungkees** [comment]
I think it's a good idea to expose `type` to `Client` interface. Returned clients can be one of "window", "worker", and "sharedworker" indeed. For the type of the attribute, we can use the enum, `ClientType` preventing the getter from returning "all". Would it make sense?

```
interface Client
{
  readonly attribute ClientType type;
}
```

For naming, I give my five cents to keeping consistency to the existing names.

**Comment by wanderview** [comment]
Works for me.  I'd like to hear from someone at google if they think its something they would implement, though.

**Comment by mkruisselbrink** [comment]
Not sure if I speak for Google, but it does sound like a sensible addition.

**Comment by jungkees** [comment]
I labeled it V1 as it'd be a simple addition that won't break the time line itself. But if anyone would argue we should add it only to the Nightly, I'd be fine with that.

**Comment by makotoshimazu** [comment]
FYI: Chromium has started to implement this at https://crrev.com/2845963002 .
