### ISSUE TITLE
Edge case for use of client.frameType

### ISSUE THREAD

**Issue by jrd261** [w3c/ServiceWorker#1007]
In an embedded signage application using many nested same domain iframes we we're using frameType to identify the top level frame for post message communications initiated by the service worker. 

We'll move to ports transferred from the client, but we now could no longer check directly check if the client is top level or one of the nested frames directly.

**Comment by jungkees** [comment]
As of this commenting, both Blink and Gecko still provide `client.frameType`. But that attribute is planned to be [deprecated](https://github.com/w3c/ServiceWorker/issues/732) in favor of `windowClient.ancestorOrigins`, which basically captures and returns the client's ancestor origins information in an array. E.g., `.ancestorOrigins` getters returning an empty array means the client is top level. I'm not sure about the exact time line for implementations, but will it work for your use case?

**Comment by jrd261** [comment]
Yes, ancestor origins is perfect. Thanks for pointing me in the right direction. Exciting how fast this moves, but its tough to keep up. Cheers.
