### ISSUE TITLE
.ready promise should be resolved after updating registration.state properties

### ISSUE THREAD

**Issue by catalinb** [w3c/ServiceWorker#1011]
The steps for resolving the .ready promise contain the following (section 3.4.2):
> If registration’s active worker is null, wait until registration’s active worker changes.
>> Implementers should consider this condition is met when the corresponding registration request >> gets to the step 6 of Activate algorithm.

However, both step 5 and step 6 from Activate algorithm use queues to make changes to the ServiceWorkerRegistration objects and dispatching statechange events.

This may lead to situations where the ready promise is resolved before registration.active is updated.

**Comment by jungkees** [comment]
Good catch! What I can promptly think of is to add steps (between step 5.3 and 5.4) that get the `ServiceWorkerRegistration` object, check its `.active`, and wait in a jump-to-labeled-step-loop until `.active` is set with the `ServiceWorker` for registration's active worker.
