### ISSUE TITLE
Inconsistent behaviour when client-side certificates are required

### ISSUE THREAD

**Issue by olemartinorg** [w3c/ServiceWorker#1022]
I've tested ServiceWorkers on a page where the web server requires client-side certificates for authentication. This is inconsistently implemented, as Chrome seems to re-use the chosen certificate that was used for the initial page load (or even ask the user again when it's unsure, when using Chrome on Android). Firefox on the other hand doesn't send the client-side certificate (even if told not to ask about client-side certificates and just choose the first one that fits) and ends up with a 400 response in the install handler (when trying to fill a cache).

**Comment by wanderview** [comment]
These are browser bugs unfortunately.  The spec has already been changed to track the window that initiated a request through the FetchEvent to the SW's fetch() call.  We just haven't implemented it yet.

Note, this will still only work if the SW performs a fetch() on the specific FetchEvent.request object itself.  If you create a different Request you will lose the connection back to the original window.
