### ISSUE TITLE
activation of the Service Worker on an iframe context

### ISSUE THREAD

**Issue by ArturoWipe** [w3c/ServiceWorker#1029]
### Before Chome 54:

- register to a Service Worker with a `domain.com` scope
- go to an HTTPS page with a different domain (`other-domain.com`), that include an HTTPS iframe (`domain.com`) that fall under the Service Worker scope
- the `domain.com` Service Worker is activated and is **running**

### Since Chrome 54:

- register to a Service Worker with a `domain.com` scope
- go to an HTTPS page with a different domain (`other-domain.com`), that include an HTTPS iframe (`domain.com`) that fall under the Service Worker scope
- the `domain.com` Service Worker is activated and is **stopped**
- Service Worker events **will force it to run** (e.g. the installation of a new version, or even a `postMessage()` from the iframe)

### Other contexts
- with Firefox (tested on the FirefoxDeveloperEdition 52), the Service Worker will be activated and **running**
- same behavior if we visit the `domain.com` directly, i.e. without the iframe context, the Service Worker is **running** (we can take this [example](https://jakearchibald.github.io/trained-to-thrill/) from Jake Archibald)

**Comment by wanderview** [comment]
Does chrome 54 fire a FetchEvent for the iframe navigation request to `domain.com`?

**Comment by wanderview** [comment]
And do you have "block 3rd party cookies and site data" enabled in your chrome settings?

I believe firefox will not fire FetchEvents to the service worker if you have 3rd party cookies disabled.

**Comment by jakearchibald** [comment]
I'm not getting the bug here. The browser is free to shut down the SW when
it isn't in use.

**Comment by wanderview** [comment]
> I'm not getting the bug here. The browser is free to shut down the SW when it isn't in use.

I read the report as the FetchEvent not firing for the iframe case.  Otherwise the grace timer probably would keep it long enough to see it running.  But its not clear which is why I asked if the FetchEvent was firing or not.

**Comment by mattto** [comment]
I think I know what's going on. Does the domain.com service worker have a fetch event handler? If not, then Chrome 54+ does not start it up for the navigation. This is an optimization, since the request will just go to network anyway. You can check this by finding the registration in chrome://serviceworker-internals and checking the field "Fetch handler existence".

**Comment by ArturoWipe** [comment]
You are right. If the `domain.com` Service Worker has a `fetch` event listener, then it will be **running** (even on Chrome 54).

So it is fair to say that the iframe context **was not** an element to be considered, and was due to the **optimization** underlined by @mattto. (The _Fetch Handler Existence_ was not available on our Chrome 54, we had to check it on a more recent version)
