### ISSUE TITLE
Client.reserved references wrong context state?

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1030]
Section 4.2.4 Client.reserved states:

> The reserved attribute must return the context object’s associated reserved state.

At:

https://w3c.github.io/ServiceWorker/#client-reserved

But things like `caches.matchAll()` reference "execution ready flag" instead of "reserved state".  See step 2.2.4.1:

https://w3c.github.io/ServiceWorker/#dom-clients-matchall

Should `client.reserved` also use execution ready flag?

**Comment by jungkees** [comment]
A `Client` is a snapshot captured when [Create Client](https://w3c.github.io/ServiceWorker/#create-client-algorithm) is invoked. So, `client.reserved`'s getter just returns the value captured in the creation time as such instead of the execution ready flag that can dynamically change.

**Comment by jakearchibald** [comment]
F2F: @wanderview to look at it again.

**Comment by jakearchibald** [comment]
We aren't going to expose reserved clients, so this is no longer an issue.
