### ISSUE TITLE
Content-Type requirement of service worker importScripts()

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1032]
Currently we require a well-formed content-type for service worker scripts.  See step 7.7:

https://w3c.github.io/ServiceWorker/#update-algorithm

But `importScripts()` does not have this check:

https://w3c.github.io/ServiceWorker/#importscripts

Should we require a well-formed mime-type on imports?

Note, this is currently a compat problem.  On this site:

https://pwa-directory.appspot.com/

The SW script tries to import:

https://pwa-directory.appspot.com/sw-offline-google-analytics/offline-google-analytics-import.js

Which is served with the headers:

  Content-Type:"text/html"
  X-Content-Type-Options:"nosniff"

Edit:  Firefox refuses to load the import.  Chrome loads the import with "text/html".

**Comment by domenic** [comment]
If at all possible it would be really great to add strict MIME type checking (not just well formedness, but also that it's a JS mime type) to all new features like this. There have been notable security issues when allowing other MIME types through.

**Comment by wanderview** [comment]
Well, I meant that service-workers do require one of "text/javascript, application/x-javascript, and application/javascript"

**Comment by annevk** [comment]
Ugh, @mikewest here is another problem with Chrome's nosniff impl.

**Comment by jungkees** [comment]
> Edit: Firefox refuses to load the import. Chrome loads the import with "text/html".

I think Chrome needs to check it. /cc @mattto

**Comment by mikewest** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=689003, thanks all!
