### ISSUE TITLE
Why are only a subset of JS mime types allowed?

### ISSUE THREAD

**Issue by domenic** [w3c/ServiceWorker#1033]
> Extract a MIME type from the response’s header list. If this MIME type (ignoring parameters) is not one of text/javascript, application/x-javascript, and application/javascript, then:

Why doesn't this use [JavaScript MIME type](https://html.spec.whatwg.org/multipage/scripting.html#javascript-mime-type) definition that the rest of the platform uses?

**Comment by jakearchibald** [comment]
I think this is a classic Jake-mistake. I wasn't aware of that definition back then.

**Comment by domenic** [comment]
Does that mean you'll fix it and submit web platform tests and file bugs on implementations? :D

**Comment by jakearchibald** [comment]
F2F: Fix it and write tests

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1354577

**Comment by mattto** [comment]
Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=767606
