### ISSUE TITLE
postMessage() to a reserved client throws

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#1035]
While discussing https://github.com/w3c/ServiceWorker/issues/1031#issuecomment-267948728, I noticed that `client.postMessage()` to a reserved client in the current spec throws as the destination (`ServiceWorkerContainer`) object shouldn't have been created yet. I think we may need a separate message queue to hold the messages while a client is in the reserved state, and re-queue them to the client message queue of the `ServiceWorkerContainer` object when it's created.

**Comment by jakearchibald** [comment]
F2F: Update the spec to allow buffering. Including across redirects, unless the redirect is across origins.

**Comment by domenic** [comment]
Language about queues and moving queued up things between them is already present in HTML for MessagePorts. See e.g. the transferring steps at https://html.spec.whatwg.org/#create-a-new-messageport-object

You may want to copy that, or even use MessagePorts as some underlying mechanism like HTML does for workers (see https://html.spec.whatwg.org/#dom-worker-postmessage).

**Comment by jakearchibald** [comment]
We aren't going to expose reserved clients, so this is no longer an issue.
