### ISSUE TITLE
"if client is an environment" is always true

### ISSUE THREAD

**Issue by isonmad** [w3c/ServiceWorker#1045]
https://github.com/w3c/ServiceWorker/commit/4ce01b53aa96982610c5a671808fae0967b69094#diff-27b79860afe28f01aed4f1f6228367faR1278 added if-else steps in several places in the wrong order, where it probably meant to be checking if *client* is the more specific category (an environment settings object) first, like https://github.com/w3c/ServiceWorker/commit/8b483b091e0f0bae6b698cf05d915c2029748ae0#diff-27b79860afe28f01aed4f1f6228367faR3533 did -- because "if client is an environment" is always true regardless.

**Comment by jungkees** [comment]
Note that https://github.com/w3c/ServiceWorker/commit/4ce01b53aa96982610c5a671808fae0967b69094#diff-27b79860afe28f01aed4f1f6228367faR1278 is different from "if client is an environment". It checks the type of the concept as "If client is a **type of** environment".

**Comment by isonmad** [comment]
What's the practical difference, exactly? Don't those mean the same thing here?

**Comment by annevk** [comment]
I tend to agree with @isonmad. E.g., we use something like "if _X_ is an element" fairly often in DOM and it needs to be true even if _X_ is a subclass of `Element`. At some point we'll formalize this through brands: https://github.com/heycam/webidl/issues/97.
