### ISSUE TITLE
service worker client definition is redundant

### ISSUE THREAD

**Issue by isonmad** [w3c/ServiceWorker#1046]
8b483b091e0f0bae6b698cf05d915c2029748ae0 changed the definition of a service worker client to "`a type of <a>environment</a> or <a>environment settings object</a>`" which is redundant, since every environment settings object [is itself also an environment](https://html.spec.whatwg.org/multipage/webappapis.html#environment-settings-object), so this confusingly implies they don't have an is-a relationship. Also, the 'type of' wording from https://github.com/w3c/ServiceWorker/issues/832#issuecomment-183513422 https://github.com/w3c/ServiceWorker/commit/c11942b04873c1980016b347abe61e7ae0e5ad21 seems redundant and potentially confusing, isn't it more straightforward to just say "a service worker client is an environment [that...]"?

**Comment by jungkees** [comment]
>  isn't it more straightforward to just say "a service worker client is an environment [that...]"?

I'm not sure if we can assume that kind of a polymorphic behavior in the spec language.

I'm actually curious if we can make a service worker client just be a type alias to the environment (i.e the base type) and use it to dynamically reference the states depending on the actual type (either environment or environment settings object) in runtime. @annevk, @domenic, would it make sense?

**Comment by jungkees** [comment]
Note that we have some places in the algorithms where the logic branches depending on the types: https://github.com/w3c/ServiceWorker/commit/4ce01b53aa96982610c5a671808fae0967b69094#diff-27b79860afe28f01aed4f1f6228367faR1278. (In this particular case, an environment doesn't make sense for checking of the secure context.) To deal with this sort of requirements with polymorphic approach, we'd have to define the algorithms on the base type and override them on the sub type (assuming the polymorphic behavior works for the specs in the first place.)

**Comment by isonmad** [comment]
> I'm not sure if we can assume that kind of a polymorphic behavior in the spec language.

Like @annevk said in https://github.com/w3c/ServiceWorker/issues/1045#issuecomment-272811311 that's already endemic in the specs.

> To deal with this sort of requirements with polymorphic approach, we'd have to define the algorithms on the base type and override them on the sub type

Except you don't really need virtual function esque overrides to do that at all. Just do the equivalent of `if (x instanceof SubType) {...} else {/* must be SuperType */...}`. As long as you put the if-else-conditions in order from most-specialized to most-general types (which isn't the case right now, which is #1045), it works like you'd expect.

**Comment by jungkees** [comment]
Just discussed with @domenic in the f2f. We agreed what @isonmad suggested in the above comment. I'll try to update the spec by using the base type with the most-specialized-to-most-general-types language.

**Comment by jungkees** [comment]
Closed by https://github.com/w3c/ServiceWorker/commit/b67c4450e04e12e12777eebbb27c368a25263bc7. Thanks @isonmad! I'd like to add you to acknowledgements if you're okay. Can you provide your name if so?

**Comment by annevk** [comment]
@jungkees we credit isonmad as "isonmad" in various WHATWG standards. I think that's their preference.

**Comment by jungkees** [comment]
I added "isonmad" to the acknowledgements. Thanks for help!
