### ISSUE TITLE
README note seems wrongish

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#1047]
Surely implementers should look at the latest, not v1?

As far as I know we don't have some kind of feature switch tooling in place that allows us to build both specifications from the same source, so by definition one of them isn't really trustworthy.

**Comment by domenic** [comment]
Yes, it seems very wrong that v1 is being mentioned in the readme; it should be removed.

**Comment by jungkees** [comment]
V1 is also in the scope of the works this repo maintains. So, I think the readme should clarify the works. Would the following change make sense?

> For the nitty-gritty of the API, the draft W3C specifications are authoritative. [Service Workers Nightly](https://w3c.github.io/ServiceWorker/) is a living document where all the up-to-date features are being developed. [Service Workers 1](https://w3c.github.io/ServiceWorker/v1) is a version that is advancing toward a W3C Recommendation. For implementers and developers who seek all the latest features, [Service Workers Nightly](https://w3c.github.io/ServiceWorker/) is a right document that is constantly reflecting new requirements. For implementers and developers who seek a version that is stabilizing without introducing new developing features, [Service Workers 1](https://w3c.github.io/ServiceWorker/v1/) is a right document with which the contributors only focus on fixing bugs and resolving compatibility issues.
>
> Currently, version 1 does not include features such as link-and-header-based installation, foreign fetch, and navigation preload.

**Comment by domenic** [comment]
I would just omit the last two sentences in that proposal. It is controversial whether implementers and developers should ever be seeking v1.

**Comment by annevk** [comment]
I think it would be clearer to say that version 1 is meant to be a subset, but that since there's no subset tooling, it's unclear if that's actually the case.

**Comment by jungkees** [comment]
> I think it would be clearer to say that version 1 is meant to be a subset

Agreed. I think we aim to and actually are maintaining it in that way although there's no tooling. How about:

> Service Workers Nightly is a living document. Service Workers 1 is a **subset of the nightly** version that is advancing toward a W3C Recommendation.

**Comment by annevk** [comment]
That seems reasonable. I'd still wish it was a little clearer about subset not being a guarantee, but okay.

**Comment by jungkees** [comment]
Addressed: https://github.com/w3c/ServiceWorker/commit/0feef08732799d55fd04cdfdaeadff0ffaf68acc.
