### ISSUE TITLE
Should 'Extend Service Worker Lifetime' be called after dispatching 'message'

### ISSUE THREAD

**Issue by smaug----** [w3c/ServiceWorker#1050]
'message' is ExtendableMessageEvent, so I guess the idea has been that waitUntil doesn't let one to add more 'extend lifetime promises' forever, like per spec is allowed now.

**Comment by smaug----** [comment]
And if/when this is fixed, https://github.com/w3c/web-platform-tests/blob/master/service-workers/service-worker/extendable-event-async-waituntil.https.html#L59 starts to fail (not sure if it fails already in blink), since all those chained Promises get resolved before dispatching the event has finished.

**Comment by smaug----** [comment]
Or is waitUntil not supposed to do anything useful with 'message' events? If so, why does ExtendableMessageEvent extend ExtendableEvent? 
Per spec 'message' events 'extend lifetime promises' aren't used for anything.

**Comment by wanderview** [comment]
I believe in practice both chrome and firefox extend the lifetime for message events.

There needs to be some protection against using `self.registration.active.postMessage()` to self-post and stay alive forever.  Currently firefox does not have this problem because we don't expose ServiceWorker object on the worker context.  (Its a bug.)  I think chrome handles this case by only extending the lifetime of the SW if the calling SW has a controlled Client.

**Comment by mkruisselbrink** [comment]
> I think chrome handles this case by only extending the lifetime of the SW if the calling SW has a controlled Client.

Chrome handles this case by at most extending the lifetime of the receiving SW to match the lifetime of the sending SW.

**Comment by jungkees** [comment]
> Should 'Extend Service Worker Lifetime' be called after dispatching 'message'

Yes, it should. I missed it. Please note that this part of the spec is being changed in https://github.com/w3c/ServiceWorker/pull/1049. The change will replace the promise-copying-and-checking approach with a reference count based approach. By this change, the Extend Service Worker Lifetime algorithm will be removed, but the semantic will remain unchanged. That is, message events are extendable events that have the same lifetime extension behavior with other SW events.

**Comment by jungkees** [comment]
Closed by https://github.com/w3c/ServiceWorker/commit/6c1f3fe31a976652d1ac4c48d7f0764ff8d63b58.
