### ISSUE TITLE
Create F2F agenda - 3-4 April 2017

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1053]
# Location

Facebook
Ark Hills
Sengokuyama Mori Tower, 30F
1-9-10 Roppongi,
Minato-ku, Tokyo 106-0032

**Map:** https://goo.gl/maps/CmhEgvmPM3o 

Note that there is an old Ark Hills and new Ark Hills in the Roppongi area. Facebook's Tokyo office is at the new Ark Hills. To make sure your cab driver drives you to the correct Ark Hills, please mention "the one next to the Swedish embassy".

Show this to the cab driver if they look confused:
東京都港区六本木1-9-10
アークヒルズ仙石山森タワー
(スウェーデン大使館の隣です。)

# Expected attendees

* **Facebook:** Nathan Schloss, Pieter Vanderwerff.
* **Mozilla:** Andrew Sutherland, Catalin Badea, Ben Kelly, Szmozsánszky István (Flaki), Salvador de la Puente González.
* **Microsoft:** Ali Alabbas, Jatinder Mann.
* **Apple:**  Brady Eidson, Theresa O'Connor.
* **Google:** Jake Archibald, Alex Russell, Surma, Takeshi Yoshino, Tsuyoshi Horo, Kenji Baheux, Matt Falkenhagen, Marijn Kruisselbrink, Kinuko Yasuda, Makoto Shimazu, Yutaka Hirano, Domenic Denicola, Yi Xu.
* **Samsung:** Jungkee Song.
* **W3C:** Yves Lafon, Michael[tm] Smith.
* **Yandex:** Chaals McCathie Nevile

# Minutes

* [Day 1](https://www.w3.org/2017/04/03-serviceworkers-minutes.html)
* [Day 2](https://www.w3.org/2017/04/04-serviceworkers-minutes.html)

# Agenda

Starting 9am.

## Intros

* Update from the browser vendors & Facebook. What they've been doing in the past 6 months & what the next priorities are.

Then, the plan is to tackle V1 stuff in the mornings, then V2 stuff in the afternoon.

The following is in no particular order, and I may cut it down a bit.

### Security & privacy

~~[#1094 Should we implement MIX passthrough](https://github.com/w3c/ServiceWorker/issues/1094)~~
~~[#1075 Track ancestorOrigins privacy issues](https://github.com/w3c/ServiceWorker/issues/1075)~~
~~[#1033 Why are only a subset of JS mime types allowed?](https://github.com/w3c/ServiceWorker/issues/1033)~~
~~[#719 "no-cors" CSS SOP violation](https://github.com/w3c/ServiceWorker/issues/719)~~

### Clients API

~~[#1093 consider how clients.claim() should work with srcdoc iframes](https://github.com/w3c/ServiceWorker/issues/1093)~~
~~[#1091 consider Client behavior for windows where initial about:blank is replaced with a loaded document](https://github.com/w3c/ServiceWorker/issues/1091)~~
~~[#1090 should clients.claim() control reserved Clients?](https://github.com/w3c/ServiceWorker/issues/1090)~~
~~[#1080 clarify Clients.matchAll() focus order for nested frames](https://github.com/w3c/ServiceWorker/issues/1080)~~
~~[#1078 clarify that Client "creation order" means when reserved Client created](https://github.com/w3c/ServiceWorker/issues/1078)~~
~~[#1038 consider how Client API should behave with bfcache](https://github.com/w3c/ServiceWorker/issues/1038)~~
~~[#1035 postMessage() to a reserved client throws](https://github.com/w3c/ServiceWorker/issues/1035)~~
~~[#1034 what should Client.url return for a reserved Worker Client?](https://github.com/w3c/ServiceWorker/issues/1034)~~
~~[#1031 reserved Client objects and redirected navigations](https://github.com/w3c/ServiceWorker/issues/1031)~~
~~[#1030 Client.reserved references wrong context state?](https://github.com/w3c/ServiceWorker/issues/1030)~~

### Spec fixing

* [#1073 Update to reference HTML for link rel=serviceworker](https://github.com/w3c/ServiceWorker/issues/1073)
* [#1063 Handle UA shutdown algorithm always invokes clear reg if we have installing worker](https://github.com/w3c/ServiceWorker/issues/1063)
* [#1055 respondWith uses the wrong targetRealm](https://github.com/w3c/ServiceWorker/issues/1055)
* [#1046 service worker client definition is redundant](https://github.com/w3c/ServiceWorker/issues/1046)
* [#1045 "if client is an environment" is always true](https://github.com/w3c/ServiceWorker/issues/1045)
* [#1013 Sort out settings object for service worker module scripts](https://github.com/w3c/ServiceWorker/issues/1013)
* [#1011 .ready promise should be resolved after updating registration.state properties](https://github.com/w3c/ServiceWorker/issues/1011)
* [#951 Handle Fetch creates JavaScript objects too early (and other feedback)](https://github.com/w3c/ServiceWorker/issues/951)
* [#829 Resolve Job Promise can resolve jobs with an incorrect value](https://github.com/w3c/ServiceWorker/issues/829)

### Lifecycle

~~[#1040 clarify that manually constructed ExtendableEvent objects may not extend lifetime via waitUntil()](https://github.com/w3c/ServiceWorker/issues/1040) - granting time~~
~~[#980 postMessage keeps service workers alive indefinitely](https://github.com/w3c/ServiceWorker/issues/980)~~

~~[#893 consider fetching service worker scripts with no-cache by default](https://github.com/w3c/ServiceWorker/issues/893)~~
~~[#839 importScript no-cache by default](https://github.com/w3c/ServiceWorker/issues/839)~~

* [#777 spec behavior when ServiceWorkerContainer parent client is dead](https://github.com/w3c/ServiceWorker/issues/777)
* [#1021 When should "imported scripts updated flag" be unset?](https://github.com/w3c/ServiceWorker/issues/1021)
* [#1004 Behavior of the onfetch setter regarding no-fetch service workers](https://github.com/w3c/ServiceWorker/issues/1004) & https://github.com/whatwg/dom/issues/371

### Misc

~~[Fix or drop appcache](https://github.com/whatwg/html/issues/151)~~
~~[#882 ServiceWorker lifetime and respondWith() with a user-constructed ReadableStream](https://github.com/w3c/ServiceWorker/issues/882)~~
~~[#1087 Safety versus simplicity in specification tests](https://github.com/w3c/ServiceWorker/issues/1087)~~

* [#991 should Cache API Vary matching use combined header values?](https://github.com/w3c/ServiceWorker/issues/991)
* [#952 Handle Fetch "shift+reload"](https://github.com/w3c/ServiceWorker/issues/952)
* [#947 Should EventSource and WebSocket be exposed in service workers?](https://github.com/w3c/ServiceWorker/issues/947)
* [#875 should FetchEvent.request.cache reflect non-fetch browser cache controls?](https://github.com/w3c/ServiceWorker/issues/875)

### Foreign fetch

~~[#878 Foreign fetch vs non-credentialed requests](https://github.com/w3c/ServiceWorker/issues/878)~~
~~[#1024 consider allowing static routing only for "foreign fetch" for anonymous requests](https://github.com/w3c/ServiceWorker/issues/1024)~~
~~[#1092 Is there any way for a web page to see if their requests will be intercepted by a foreign fetch handler?](https://github.com/w3c/ServiceWorker/issues/1092)~~
~~[#1085 Allow overlapping scopes](https://github.com/w3c/ServiceWorker/issues/1085)~~
~~[#1017 clientId on ForeignFetchEvents](https://github.com/w3c/ServiceWorker/issues/1017)~~
~~[#982 registerForeignFetch({ origins, scope }) optional](https://github.com/w3c/ServiceWorker/issues/982)~~
~~[#979 Define procedure to convert options object of `sw.register()` to `Link` header](https://github.com/w3c/ServiceWorker/issues/979)~~
~~[#910 Expose fragments cross-origin for subresources](https://github.com/w3c/ServiceWorker/issues/910)~~
~~[#899 Foreign fetch and no-referrer Referrer Policy](https://github.com/w3c/ServiceWorker/issues/899)~~
~~[#880 CORS pre-flight for foreign fetch](https://github.com/w3c/ServiceWorker/issues/880)~~
~~[#825 Installing a foreign SW as part of a subresource request](https://github.com/w3c/ServiceWorker/issues/825)~~
~~"Nav" preload for Foreign Fetch~~

### Fetch & streams

~~Setting mode https://github.com/whatwg/fetch/issues/492~~
~~[#1026 Consider mechanisms to bypass the service worker for things that we know won't be in it's cache](https://github.com/w3c/ServiceWorker/issues/1026)~~
~~Upload streams~~
~~Transferrable streams~~
~~[Fetch cancellation/control/observing](https://github.com/whatwg/fetch/issues/447#issuecomment-281731850) - brief overview & next steps~~

* [Background fetch](https://github.com/WICG/background-fetch) - brief overview and initial feedback

### SW object enhancements

~~[#1077 Find a way for service workers to get their current state](https://github.com/w3c/ServiceWorker/issues/1077)~~
~~[#1076 Service worker ID - remove?](https://github.com/w3c/ServiceWorker/issues/1076)~~
~~[#1016 serviceworker.skipWaiting](https://github.com/w3c/ServiceWorker/issues/1016)~~
~~[#842 consider exposing install time on ServiceWorker DOM object](https://github.com/w3c/ServiceWorker/issues/842)~~

### Cache API

* [#1066 Pagination in cache.keys()](https://github.com/w3c/ServiceWorker/issues/1066)
* [#977 Allow Caching of POST requests](https://github.com/w3c/ServiceWorker/issues/977)
* [#823 Cache transactions & fixing `addAll`](https://github.com/w3c/ServiceWorker/issues/823)

### Clients

* [#955 consider exposing self.clients on window and other worker globals](https://github.com/w3c/ServiceWorker/issues/955)
* [#1036 Support returning ServiceWorker Client environments from `Clients.matchAll()`](https://github.com/w3c/ServiceWorker/issues/1036)
* [#1037 `Clients.matchAll()` should exclude the current environment](https://github.com/w3c/ServiceWorker/issues/1037)
* [#886 consider firing a "clientcontrolled" event on ServiceWorkerGlobalScope](https://github.com/w3c/ServiceWorker/issues/886)
* Updating title & favicon of a window client

### Nav preload

~~[#920 Making a concurrent request for navigations](https://github.com/w3c/ServiceWorker/issues/920)~~
~~[#1000 NavigationPreloadManager.setHeaderValue should reject invalid HTTP header field values](https://github.com/w3c/ServiceWorker/issues/1000)~~

### Storage eviction

* [#611 Hints in beforeevicted to let the SW of a web app pick among several house cleaning options? ](https://github.com/w3c/ServiceWorker/issues/611)
* [#971 Handle the quota exceeded error globally](https://github.com/w3c/ServiceWorker/issues/971)

### Dealing with fetch failures & tab crashes

~~[#939 Recovering from fetch failures](https://github.com/w3c/ServiceWorker/issues/939)~~
~~[#877 Reporting URL for SW update failures](https://github.com/w3c/ServiceWorker/issues/877)~~

### JS Modules

* [#908 Auto-cache imported scripts](https://github.com/w3c/ServiceWorker/issues/908)
* [#849 Spec uses incorrect settings object when fetching a module worker](https://github.com/w3c/ServiceWorker/issues/849)

### Misc

~~[#614 A way to immediately unregister a service worker](https://github.com/w3c/ServiceWorker/issues/614)~~
~~[#756 consider allowing multiple worker thread instances for a single registration](https://github.com/w3c/ServiceWorker/issues/756)~~

* [#1028 Consider providing `navigation` event](https://github.com/w3c/ServiceWorker/issues/1028)
* [#962 allow service worker produced resources to be marked as "cachable"](https://github.com/w3c/ServiceWorker/issues/962)
* [#975 Using BroadcastChannel to wake up a service worker](https://github.com/w3c/ServiceWorker/issues/975) - also what's happening with shared worker?
* [#913 cache.match should create partial responses if given a range request](https://github.com/w3c/ServiceWorker/issues/913)
  https://github.com/whatwg/fetch/issues/144
* [#798 Add ServiceWorker.prototype.registration](https://github.com/w3c/ServiceWorker/issues/798)
* [#770 registration.ready promise](https://github.com/w3c/ServiceWorker/issues/770)
* [#707 Add cookie accessor/setter methods?](https://github.com/w3c/ServiceWorker/issues/707)
* Content indexing API?
* What's happening with shared worker?

**Comment by jakearchibald** [comment]
Let me know here or in private if you expect to attend.

**Comment by mkruisselbrink** [comment]
I'm also tentatively planning to attend (although I guess we'll likely have plenty of google presence already anyway).

**Comment by mattto** [comment]
I'll be there.

**Comment by KenjiBaheux** [comment]
I should be there as well.

**Comment by horo-t** [comment]
I'll be there too.

**Comment by delapuente** [comment]
I'll be there also.

**Comment by hober** [comment]
s/TBA/@beidson and @hober/

**Comment by n8schloss** [comment]
@pieterv will be attending from Facebook as well

**Comment by jakearchibald** [comment]
If anyone is worried about travel due to recent events, feel free to reach out. I don't have a grand plan, but if there's anything I can do, let me know - jakearchibald@google.com

**Comment by ylafon** [comment]
I'll be there

**Comment by kinu** [comment]
I plan to be there too!

**Comment by chaals** [comment]
I'll be there…

**Comment by n8schloss** [comment]
Hey everyone,

If you're attending the meeting please fill out https://www.surveymonkey.com/r/6NLCJ9G asap.

We (Facebook) are planning on providing lunch both days of the meeting and are planning taking everyone out to dinner on the first day (April 3th). We need a headcount for the dinner and even if you're not coming to the dinner please fill out the survey so we can get your email address registered in our visitor system.

Thanks, I can't wait to see you all!

**Comment by yutakahirano** [comment]
I'll be there.

**Comment by n8schloss** [comment]
We're still missing 6 responses to https://www.surveymonkey.com/r/6NLCJ9G, if you're planning on coming please fill out the survey asap!

**Comment by makotoshimazu** [comment]
I'll be there.

**Comment by jakearchibald** [comment]
If you're expecting to attend & your name isn't in the list at the top of the page, speak up! We're using the list to ensure everyone can get into the building & we have space etc.

**Comment by annevk** [comment]
Topic suggestion: https://github.com/whatwg/html/issues/151.

**Comment by isonmad** [comment]
Re: fetch & streams: [trying to make a stream (e.g.) downloadable using service workers isn't very ergonomic](https://github.com/whatwg/streams/issues/480#issuecomment-272726391).

**Comment by jakearchibald** [comment]
I've updated the original post with issues we can look at. We're going to start at 9am - looking forward to it!

**Comment by mattto** [comment]
Meeting notes are being taken in #serviceworker on freenode.

**Comment by jakearchibald** [comment]
F2F: background SW (push, notification, sync, bg fetch) vs foreground SW (fetch, postMessage) - MS & Apple want this for service workers to exist when the browser is closed. Should we spec this? Fetches for notification icons go through the background SW in Edge, since there isn't a foreground SW.

What happens to the clients API? How do we represent multiple instances.

Facebook global state case:

* Notification click
* Post to client "navigate"
* Client navigates (may be real nav, or pushstate)
* Client posts back to SW, please focus me

How does the client message the correct service worker?

Edge can work around this by still ensuring there's only one SW at a time. Either using the bg SW, or fg SW.

We need to think more about use cases that require speaking to a particular SW, or otherwise depend on global state.

**Comment by NekR** [comment]
> Fetches for notification icons go through the background SW in Edge, since there isn't a foreground SW.

What about notification happening when where is already foreground SW (i.e. webpage is opened)? Also, what about fetches originated from `push` event to synchronize additional data?

**Comment by jakearchibald** [comment]
Next meeting:

* Teleconferences in the mean time
* Monthly heartbeat VC to catch up

* Potential F2F in August (CSS are in Paris 1st week)
* November TPAC
