### ISSUE TITLE
How can I set service-worker-allowed  header on my sw.js file response ?

### ISSUE THREAD

**Issue by sagar12861** [w3c/ServiceWorker#1061]

**Comment by jakearchibald** [comment]
I've closed this issue as it isn't related to the service worker spec, but I'll continue to provide support.

> How can I set service-worker-allowed header on my sw.js file response?

This depends on which backend you're using.

With apache/nginx, you use config files to add headers to particular paths. With express, you can set headers per response using `res.set(…)`. If you're using a static host such as S3, you need to set the headers at upload time.

**Comment by sagar12861** [comment]
@jakearchibald Ho thank you very much. The project that I'm working is java spring hosted on tomcat.

Thanks for your clarification.
