### ISSUE TITLE
Handle UA shutdown algorithm always invokes clear reg if we have installing worker

### ISSUE THREAD

**Issue by aliams** [w3c/ServiceWorker#1063]
[2.6 User Agent Shutdown](https://w3c.github.io/ServiceWorker/#user-agent-shutdown) states that:
- An installing worker does not persist but discarded. If the installing worker was the only service worker for the service worker registration, the service worker registration is discarded.

In contrast, the [User Agent Shutdown Algorithm](https://w3c.github.io/ServiceWorker/#on-user-agent-shutdown-algorithm) states that:
1. If _registration_'s installing worker _installingWorker_ is not null, then:
   1. If the result of running Get Newest Worker with _registration_ is _installingWorker_, invoke Clear Registration with _registration_ and continue to the next iteration of the loop.

According to the algorithm, when we call [Get Newest Worker](https://w3c.github.io/ServiceWorker/#get-newest-worker), we're always going to get the installingWorker. Step 1 checks if the  _registration_'s installing worker _installingWorker_ is not null and the Get Newest Worker returns newestWorker which is going to be the registration's installing worker since the installing worker is not null.

This can be a problem since that means we are always invoking Clear Registration regardless if we have an installing worker (even if there's an active worker).

cc editors: @jungkees @jakearchibald

**Comment by jakearchibald** [comment]
Ohhh haha yeah. I'm pretty sure that "Get Newest Worker" should be intending to get the *oldest* worker, as in the active worker. Is that right @jungkees?

Good catch!

**Comment by jungkees** [comment]
Yes, I think I intended "Get Oldest Worker" and if it's the installing worker. ;)

Thanks @aliams!
