### ISSUE TITLE
mode 'no-cors' showing error no 'access-control-allow-origin' header

### ISSUE THREAD

**Issue by sagar12861** [w3c/ServiceWorker#1064]
I'm using following code to add requests to cache on fetch event to cache images from another domain
```cache.add(new Request(event.request.url, { mode: 'no-cors' }));```
But it is still showing error  'no-cors' showing error n 'access-control-allow-origin' header

**Comment by jakearchibald** [comment]
You cannot make no-cors requests with `cache.add` as it cannot tell you if the response was 404 or not. You can work around this by fetching the response with `fetch` then use `cache.put`, which allows you to store things like 404s.
