### ISSUE TITLE
Consider throwing when non-promise is passed to `waitUntil`.

### ISSUE THREAD

**Issue by surma** [w3c/ServiceWorker#1068]
Once switching to async/await, you start writing code like

```js
self.oninstall = event => {
  event.waitUntil(async function() {
    // ...
  }());
}
```

Note that the `async` function is an IIFE, something that is easy to forget and incredibly hard to spot and/or debug, but your code just stops running, effectively failing silently.

I propose that passing anything but a promise to `waitUntil` should throw. This is technically a breaking change, so we should investigate if there’s any _intentional_ usage for non-promises with `waitUntil`.

**Comment by annevk** [comment]
What does IIFE mean?

Also, I don't think we can change this easily, since IDL automatically casts non-promises.

**Comment by surma** [comment]
IIFE = Immediately-invoked function expression.

>Also, I don't think we can change this easily, since IDL automatically casts non-promises.

We should still be able to do type checks, shouldn’t we?

**Comment by annevk** [comment]
No, IDL does those. By the time the algorithm in the standard is invoked you have a promise.

**Comment by annevk** [comment]
See https://heycam.github.io/webidl/#es-promise in particular.

**Comment by surma** [comment]
I see. Is there any other way we can address the problem? I mean, it’s mostly about developer ergonomics here. One way would be to add handling if that promise passed to `waitUntil` resolves to an async function (or even just a plain function), but I am not sure if that has any implications I am not seeing right now.

**Comment by annevk** [comment]
I guess I don't really understand the problem. How is this different from `waitUntil(new Promise(...))`?

**Comment by jakearchibald** [comment]
Maybe we just need to push a pattern like:

```js
const response = Promise.try(async () => {
  // …
});

event.respondWith(response);
```

**Comment by surma** [comment]
To clarify, the problem I have is the following:

The following code will add `index.html` and `styles.css` to my cache:
```js
self.oninstall = event => {
  event.waitUntil(async function() {
    const cache = await caches.open('mycache');
    await cache.addAll(['index.html', 'styles.css']);
  }());
}
```

The following code will do _nothing_:
```js
self.oninstall = event => {
  event.waitUntil(async function() {
    const cache = await caches.open('mycache');
    await cache.addAll(['index.html', 'styles.css']);
  });
}
```

The only difference is that I forgot to invoke my async function literal. I would like to somehow catch that. 

> Maybe we just need to push a pattern like:

I guess we could try solving this by pushing best practices, but I feel like there’s barely ever a use-case where the value passed to `waitUntil` is anything else but a promise[citation needed]. I do understand @annevk that IDL does not allow us to inspect the value passed to `waitUntil`, but I’d still like us to at least think about if there’s a feasible solution to making this error for developers’ sake.

**Comment by annevk** [comment]
Since @domenic effectively designed the IDL-side of this, perhaps he has some thoughts on this. If we had known about this sooner I suppose the prose could have required `waitUntil` to settle with a specific value (say, `undefined`), and reject if it's something else.

**Comment by domenic** [comment]
> I suppose the prose could have required waitUntil to settle with a specific value (say, undefined), and reject if it's something else.

This seems like the more correct path to me.

Browsers could add a warning here if they wanted.

**Comment by wanderview** [comment]
It seems a bit breaking to suddenly require an exact resolution type for install event `waitUntil()`.  This API has been in the wild for a long time and it seems likely people do resolve to other values.

The browser could detect if it resolves to a function, though, and add a console warning that perhaps the function was not called?

**Comment by annevk** [comment]
@wanderview yeah, I think that's the best we can do at this point.

**Comment by surma** [comment]
> It seems a bit breaking to suddenly require an exact resolution type for install event waitUntil(). 

Definitely breaking change and I am not proposing that we do that. I am looking into getting data what types of values are used in the wild and so we can make an informed decision regarding throwing.

For now I’d be very happy with a warning, but that doesn’t need to happen at spec level I guess(?)

**Comment by surma** [comment]
Closing this as it is not a spec issue. But do agree that librarifying(?) is the best path from here.

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/sw-helpers/issues/200 on the "librarifying" front.
