### ISSUE TITLE
useCache attribute design seems very very wrong

### ISSUE THREAD

**Issue by domenic** [w3c/ServiceWorker#1069]
> If useCache is not a valid boolean value, queue a task to fire an event named error at the link element, and abort these steps.

This is *not* how HTML boolean attributes work. You should never do `usecache="true"` or `usecache="false"`.

Instead this step and the previous should just check for the presence of the usecache attribute. There is no such thing as an invalid value. The attribute is either present or absent; it's value does not matter. That's how boolean attributes work.

This is especially important since the `useCache` IDL attribute is supposed to reflect the content attribute. That will work very very poorly with the above processing model.

**Comment by jakearchibald** [comment]
Whoa, indeed. Fixing…

**Comment by jakearchibald** [comment]
PR https://github.com/w3c/ServiceWorker/pull/1070

**Comment by jungkees** [comment]
It was my bad. Left a comment in the PR. Thanks!
