### ISSUE TITLE
Update to reference HTML for link rel=serviceworker

### ISSUE THREAD

**Issue by domenic** [w3c/ServiceWorker#1073]
@sideshowbarker added formal definitions for link rel=serviceworker to HTML, containing e.g. authoring conformance requirements, in https://github.com/whatwg/html/pull/2356. The processing model of course stays in this spec. But there are some small tweaks that can be done for integration purposes.

- Update the introductory paragraph in https://w3c.github.io/ServiceWorker/#link-type-serviceworker. You still need to define the term "serviceworker link" but I'd say something like how it can be created with either a `Link` header or a HTML `<{link}>` element with `<{link/rel}>` equal to `"serviceworker"`. Ideally that last should link to https://html.spec.whatwg.org/multipage/semantics.html#link-type-serviceworker.
- https://w3c.github.io/ServiceWorker/#link-element-interface-extensions can be removed. That should hopefully make all links to the content attributes automatically go to their definitions in HTML.
- Step 7 should change to "Let workerType be the state of the `<{link/workertype}>` attribute". HTML now takes care of the missing and invalid value default.
  - Either step 8 should be removed (normative change!), or we should update HTML to have an invalid value default state (say "invalid"), which you can then throw an error on. Let me know what you think is best.

**Comment by sideshowbarker** [comment]
I can put time into creating a PR for this if nobody else has the cycles at the moment.

**Comment by jungkees** [comment]
I'm OOO until 1st of March. PR would be appreciated!

**Comment by sideshowbarker** [comment]
Note that this needs a resolution on the following question from @domenic:

> Either step 8 at https://w3c.github.io/ServiceWorker/#link-element-processing should be removed (normative change!), or we should update HTML to have an invalid value default state (say "invalid"), which you can then throw an error on. Let me know what you think is best.

That step 8 is this:

> If _workerType_ is not a valid `WorkerType` value, queue a task to fire an event named `error` at the `link` element, and abort these steps.

**Comment by sideshowbarker** [comment]
I’m creating a patch/PR for this at the moment and am at the point of realizing the spec doesn’t yet actually define what syntax a service-worker `Link` header value is expected conform to.

So it seems like as part of this PR I also need to add an ABNF for `Link` header value.

I now wonder what other specs we might have that contain something I could use as a model—I mean an existing spec that defines the syntax of the value of the `Link` header for some particular link type.
