### ISSUE TITLE
No event for knowing when service worker is not available

### ISSUE THREAD

**Issue by publicocean0** [w3c/ServiceWorker#1082]
I want notify a server when service worker is online and when is offline . I thought to use sync command once for notify when is online . But how to know when browser is closing  independently by the page in which user is surfing ?

**Comment by jakearchibald** [comment]
Can you give a example of what you'd use this for? I'm having trouble understanding what "online" and "offline" mean in this example.

**Comment by jakearchibald** [comment]
Closing due to lack of feedback. Feel free to reopen with details!
