### ISSUE TITLE
what should Client.navigate() set the referrer to?

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1086]
The SW spec doesn't say anything about referrer in Client.navigate().  Gecko code currently sets the referrer to the URL of the document being navigated, but that seems dubious to me.  Should it be the creation URL of the environment calling Client.navigation()?  So the service worker script URL?

**Comment by n8schloss** [comment]
Why not treat Client.navigate() referrer's like a navigate via the address bar and make them be empty?

**Comment by wanderview** [comment]
That would be fine too.  Maybe that is what the spec says to do now?

**Comment by n8schloss** [comment]
I think I'd interpret it that way. It says 'navigate' and links to the whatwg navigation spec, so to me that implies it should be empty just like on a navigation from the address bar.

**Comment by domenic** [comment]
In particular step 1 of the navigate algorithm linked to creates a new request whose url is the given URL. No headers are set. /cc @annevk.

**Comment by wanderview** [comment]
Sounds good.  Sorry I can't read!
