### ISSUE TITLE
service Worker cache

### ISSUE THREAD

**Issue by ankit4794** [w3c/ServiceWorker#1088]
1. how can i restrict some of my website pages from caching?
2. how can i create service worker that work only for mobile only?

**Comment by flaki** [comment]
Hey Ankit!

For *(1)* you can use the [`scope` directive when you register your service worker script](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Registering_your_worker) and put those pages to a different scope not covered by your service worker, or alter the service worker script itself to not cache anything on some pages. What is your use case? Also, are you using any service worker libraries or write your own SW script?

For *(2)*, I would also like to ask what would be the use case of only having a service worker on mobile, but not on desktop?

Also, I'd recommend asking development-related questions [on StackOverflow, using the `service-worker` tag](http://stackoverflow.com/questions/tagged/service-worker) - they might better be able to assist you, this repository is mostly for specification-related issues. ;)

**Comment by ankit4794** [comment]
for 1) 
"const version = 1;
const offlinePage = '/offline';
const urlBlacklist = [
    './checkout',
    './onepage',
    './customer/'
  ];
  
  // Functions
// #####################################

/**
 * Add all of the static pages and assets to the cache.
 *
 * @returns {*|Promise.<TResult>}
 */
function updateStaticCache() {
    return caches.open(version)
        .then(cache => {
            return cache.addAll([
                offlinePage
            ]);
        });
}

/**
 * Delete caches that do not match the current version of the service worker.
 *
 * @returns {*|Promise.<TResult>}
 */
function clearOldCaches() {
    return caches.keys().then(keys => {
        return Promise.all(
            keys
                .filter(key => key.indexOf(version) !== 0)
                .map(key => caches.delete(key))
        );
    });
}

/**
 * Check if the given request is expecting a HTML page returned.
 *
 * @param {Request} request
 * @returns {boolean}
 */
function isHtmlRequest(request) {
    return request.headers.get('Accept').indexOf('text/html') !== -1;
}

/**
 * Check if the given URL matches any of the blacklist URL prefixes.
 *
 * @param {string} url
 * @returns {boolean}
 */
function isBlacklisted(url) {
    return urlBlacklist.filter(bl => url.indexOf(bl) == 0).length > 0;
}

/**
 * Return the response if it can be cached, null otherwise.
 *
 * @param {Response} response
 * @returns {boolean}
 */
function isCachableResponse(response) {
    return response && response.ok;
}

// Install
// #####################################

self.addEventListener('install', event => {
    event.waitUntil(
        updateStaticCache()
            .then(() => self.skipWaiting())
    );
});

// Activate
// #####################################

self.addEventListener('activate', event => {
    event.waitUntil(
        clearOldCaches()
            .then(() => self.clients.claim())
    );
});

// Fetch
// #####################################

self.addEventListener('fetch', event => {
    let request = event.request;

    if (request.method !== 'GET') {
        // Only process GET request, unless offline and expecting a HTML page, then show the offline page instead
        if (!navigator.onLine && isHtmlRequest(request)) {
            return event.respondWith(caches.match(offlinePage));
        }
        return;
    }

    if (isHtmlRequest(request)) {
        // For HTML requests, fetch from the network first, otherwise fall back to cache
        event.respondWith(
            fetch(request)
                .then(response => {
                    if (isCachableResponse(response) && !isBlacklisted(response.url)) {
                        let copy = response.clone();
                        caches.open(version).then(cache => cache.put(request, copy));
                    }
                    return response;
                })
                .catch(() => {
                    return caches.match(request)
                        .then(response => {
                            if (!response && request.mode == 'navigate') {
                                return caches.match(offlinePage);
                            }
                            return response;
                        });
                })
        );
    } else {
        // For asset requests, get from cache, otherwise fetch from the network
        event.respondWith(
            caches.match(request)
                .then(response => {
                    return response || fetch(request)
                            .then(response => {
                                if (isCachableResponse(response)) {
                                    let copy = response.clone();
                                    caches.open(version).then(cache => cache.put(request, copy));
                                }
                                return response;
                            })
                })
        );
    }
});"

this is my code..

offlinePage, urlBlacklist are not working... while offline the my offline page didnt show up..
n while caching, all the pages get cached..



For 2) i m using different website, amp for mobile.. non-amp for desktop.. but the url is same...
while cache the amp website show up in desktop... so i want to differentiate it... i want service worker for mobile site.. not for desktop...


please help me in this problem..

**Comment by jakearchibald** [comment]
> how can i restrict some of my website pages from caching?

Things only cache when you call `cache.add(request)`, `cache.addAll(requests)`, or `cache.put(request, response)`. If you don't want something to cache, don't add it to the cache 😄.

> how can i create service worker that work only for mobile only?

A service worker is only registered when you call `navigator.serviceWorker.register(url)`, so if you want to register a service worker, don't call it. It seems like you're already using some logic to change the content you're serving for mobile, so leverage that.

I've closed this issue as it doesn't relate to the spec, but we're happy to continue to offer support (although stackoverflow would be better).
