### ISSUE TITLE
Is there any way for a web page to see if their requests will be intercepted by a foreign fetch handler?

### ISSUE THREAD

**Issue by delapuente** [w3c/ServiceWorker#1092]
Suppose I know my favourite CDN is installing a SW with foreign fetch and I want to wait for downloading other assets until my CDN SW is registered. Is there any API feature to check this?

**Comment by mkruisselbrink** [comment]
Not currently, no. You could poll for the presence of a (cooperating) foreign fetch handler by fetching some resource where you have some way of identifying if the request was intercepted or not (foreign fetch handler adding custom header, or just specific content/URL), but there isn't currently any way to wait for the presence of the CDN SW.

You should always be able to deal with the foreign fetch handler not being present though. Even if you somehow determine that at time X there was a foreign fetch handler that gives no guarantees that the handler will still be there for future requests.

The closest to what you're asking for is something like what's discussed in whatwg/fetch#492, providing some way to specify that certain fetches should or should not be served by a service worker.

**Comment by delapuente** [comment]
Does it make sense to ask the Service Worker manager if there is some foreign fetch related with certain origins? Such as:

```js
let willBeIntercepted =
  await navigator.serviceWorker.checkInterception('https://fontsite.com');
if (!willBeIntercepted) {
  navigator.serviceWorker.onforeignfetchinterception = evt => {
    willBeIntercepted = evt.origin === 'https://fontsite.com';
  };
}
```

**Comment by jakearchibald** [comment]
Closing due to https://github.com/w3c/ServiceWorker/issues/1188
