### ISSUE TITLE
Switch useCache to an enum

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1104]
We're worried about fetch all `importScripts` on every navigation. It sounds really heavy and a waste of bandwidth.

New proposal. `useCache` values:

* "never"
* "imports"
* "all"

It's a bit late in the day, but we all think this is a much safer change.

**Comment by wanderview** [comment]
Gecko bug to avoid shipping boolean useCache: https://bugzilla.mozilla.org/show_bug.cgi?id=1353638

Gecko bug to switch to enum: https://bugzilla.mozilla.org/show_bug.cgi?id=1353636

**Comment by jakearchibald** [comment]
I'm worried it isn't clear that `useCache` applies to updates, so I'm going to rename it `updateViaCache`. Objections welcome.

**Comment by jakearchibald** [comment]
Service worker spec PR https://github.com/w3c/ServiceWorker/pull/1107

**Comment by wanderview** [comment]
Just to clarify, is this also doing FB's request to bypass cache on register?  The new name just made me wonder.

**Comment by jakearchibald** [comment]
Nah, I haven't added that. But you're right, the naming makes even more sense considering that.

**Comment by jakearchibald** [comment]
https://github.com/w3c/ServiceWorker/pull/1107

**Comment by jungkees** [comment]
SW change: https://github.com/w3c/ServiceWorker/commit/c92c1485583eed0c26a10b5b8dc8ed41ffa8d1e6. (merged)
HTML change: https://github.com/whatwg/html/commit/b5fcec0fa105de2dd3c3aeeb7ea5c630a7bf5024. (merged)
Tests: https://github.com/w3c/web-platform-tests/pull/5515. (underway)

**Comment by mattto** [comment]
We're confused that the service worker spec and the HTML spec seem to have contradicting definitions of updateViaCache in HTMLLinkElement.
(SW spec)
```
partial interface HTMLLinkElement {
  ...
  [CEReactions] attribute ServiceWorkerUpdateViaCache updateViaCache;
};
```

(HTML spec)
```
interface HTMLLinkElement : HTMLElement {
  ...
  [CEReactions] attribute DOMString updateViaCache;
};
```

It seems the HTMLLinkElement extension in the service worker spec is not needed since the HTML spec has it.

**Comment by jakearchibald** [comment]
Ahh yes, we need to remove the one from the service worker spec. The HTML spec is the correct one.

**Comment by jungkees** [comment]
Yes, it's being addressed in https://github.com/w3c/ServiceWorker/pull/1110#issue-220441661.

**Comment by jakearchibald** [comment]
Tests landed https://github.com/w3c/web-platform-tests/pull/5515
