### ISSUE TITLE
Confusing "Updating a service worker" section in explainer

### ISSUE THREAD

**Issue by kownacki** [w3c/ServiceWorker#1111]
In https://github.com/w3c/ServiceWorker/blob/master/explainer.md#updating-a-service-worker
it's explained how service worker is managed when multiple tabs are opened.

In the third paragraph it's written "This avoids the problem of two versions of a site running at the same time, in different tabs."
but then "Our current strategy for this is “cross fingers, hope it doesn’t happen”."

Those are two contradictory statements. 

So how it really works? Is it always by default working like in the example (new service worker takes place only when all tabs get closed) or some work is needed to handle multiple tabs (and if not, there is danger that some tabs have different service workers at the same time)?

**Comment by jakearchibald** [comment]
Yeah, that was confusing. I meant that we currently just cross our fingers, but service worker means you don't have to.

You might be interested in this article on [the service worker lifecycle](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle).
