### ISSUE TITLE
FetchEventInit.preloadResponse should not be a required member

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1114]
FetchEventInit.preloadResponse should not be a required member.

Feedback from https://groups.google.com/a/chromium.org/d/msg/blink-dev/d8KxOilsS2g/QOj5b5pFBAAJ

**Comment by foolip** [comment]
This is in https://w3c.github.io/ServiceWorker/#fetchevent-interface

Making it optional, perhaps the prose of the constructor should just create a new promise that is never settled, like what `Promise<any> preloadResponse = new Promise()` would do if that were valid syntax. Or create a rejected promise. Anything WFM :)

**Comment by mattto** [comment]
Probably resolving to undefined is the most sane, since that's what happens when navigation preload is not enabled.
