### ISSUE TITLE
Secure context language is redundant/contradicts secure context spec

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1125]
The spec contains the language

> A user agent may allow localhost, 127.0.0.0/8, and ::1/128 for development purpose. (Note that they may still be secure contexts.) 

("may still be" should read "must still be"?)

This seems redundant with the Secure Contexts spec which seems to cover localhost and loopback addresses, for example at https://w3c.github.io/webappsec-secure-contexts/#localhost

So I think we should just need to rely on the Secure Contexts spec here.

**Comment by mattto** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=656442 and https://github.com/w3c/webappsec-secure-contexts/issues/43

**Comment by jungkees** [comment]
> A user agent may allow localhost, 127.0.0.0/8, and ::1/128 for development purpose. (Note that they may still be secure contexts.)

I agree to remove it and rely on the Secure Contexts spec but still want to provide information to devs that they can use loopback addresses, etc. Would leaving the following note make sense?

> Note: Developers can use 127.0.0.0/8, ::1/128, and localhost (see [the requirements](https://w3c.github.io/webappsec-secure-contexts/#localhost)) for development purpose.

**Comment by mattto** [comment]
Sure, it'd make sense for the first two sentences to be normative, and the rest to be a non-normative note. Something like this:

Service workers must execute in secure contexts. Service worker clients must also be secure contexts to register a service worker registration, to get access to the service worker registrations and the service workers, to do messaging with the service workers, and to be manipulated by the service workers.

Note: This effectively means that service workers and their service worker clients should be hosted over HTTPS. A user agent may allow localhost, 127.0.0.0/8, and ::1/128 for development purposes. The primary reason for this restriction is to protect users from the risks associated with insecure contexts.
