### ISSUE TITLE
clients.get() should resolve with null instead of undefined

### ISSUE THREAD

**Issue by esprehn** [w3c/ServiceWorker#1133]
This was confusing using the API since getElementById (and other similar apis) return null, while this seems to resolve to undefined instead.

**Comment by domenic** [comment]
-1, `new Map().get("foo")` returns undefined, and that is the precedent we should be following for map-likes.

**Comment by jakearchibald** [comment]
I'm not always sure when I should be using null vs undefined. Are there any docs for this?
