### ISSUE TITLE
navigator.serviceWorker.ready remain resolved after unregister

### ISSUE THREAD

**Issue by toxic-johann** [w3c/ServiceWorker#1139]
navigator.serviceWorker.ready will be resolved when worker is active.
but if we unregister the worker, the ready attribute remain resolved.
In the document, it has not specified that the ready attribute will be reset.
Will it be strange ?

**Comment by jungkees** [comment]
Once a client gets a controller, it's being controlled until the client is unloaded/terminated. Calling `unregister()` sets the [uninstalling flag](https://w3c.github.io/ServiceWorker/#dfn-uninstalling-flag), but it tries to clear the registration only when all the controlled clients are closed. That said, I don't think we should reset the ready promise on an unregister attempt.

**Comment by wanderview** [comment]
Note, it is possible to use the `.ready` flag and not become controlled.  Consider a window that is already open before `.register()` is called.  So its possible for the service worker to go away with a ready promise settled.

**Comment by toxic-johann** [comment]
@wanderview Yes. I agree with that. So maybe `controllerchange` event is much better in that situation?
@jungkees Thanks for your explanation. Now i understand what it means.

**Comment by wanderview** [comment]
@toxic-johann Yea, I think writing a helper that uses `.controller` and `controllerchange` event will be much more reliable if this situation can realistically occur for you.

**Comment by toxic-johann** [comment]
Thanks a lot~
