### ISSUE TITLE
Should update() called on an installing worker reject (as currently does?)

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#1155]
`registration.update()` step 5 has:
> If the context object’s relevant settings object’s global object globalObject is a ServiceWorkerGlobalScope object, and globalObject’s associated service worker's state is installing, reject p with an "InvalidStateError" exception and abort these steps.

@mattto, @wanderview, AFAICT, Chrome doesn't have this error checking. Does Firefox check this? Do we need this error checking here?

**Comment by wanderview** [comment]
I believe we do.  We added it to prevent the service worker spinning on a SW that calls update() before install completes and then has its install fail.  If we queue an update job in those circumstances we will continuously run jobs that each fail.  So we added this step to prevent self-update on uninstalled SW.

**Comment by jungkees** [comment]
Right. I remember the discussion. I'll keep it while addressing the issue raised through https://github.com/w3c/ServiceWorker/pull/1152: ensuring update() returns a promise regardless of the error conditions.

Do we have a wpt test for this already by the way?

**Comment by jungkees** [comment]
Fixed the control flow of update() method that rejected a non-returned promise and aborted right away: https://github.com/w3c/ServiceWorker/commit/62811434324a5d00cfbb236fc736a2eeaf36a19d.

**Comment by wanderview** [comment]
There is this test, but it seems to suggest it shouldn't throw:

https://github.com/w3c/web-platform-tests/blob/56ea52b8668ceee63ec196c59dd11ad7797e4f0d/service-workers/service-worker/ServiceWorkerGlobalScope/resources/update-worker.js#L25

It seems we pass the test, so perhaps we don't implement the exception yet.

**Comment by jungkees** [comment]
Added a check to the test to ensure it throws: https://github.com/w3c/web-platform-tests/pull/6107. Running the test with this change locally, chrome passes it already.

**Comment by delapuente** [comment]
Let me a question, please. What happens if I call `update()` twice in a row on an already installed service worker?

**Comment by jungkees** [comment]
They are basically [scheduled](https://w3c.github.io/ServiceWorker/#schedule-job) to the job queue. If the job queue is empty when the first update is scheduled, that job is run right away. So, the second update will be queued and run later again. If more (same) update jobs are scheduled, they are not queued but aggregated (Schedule Job step 2.2) as a duplicate to the update job already pushed in the queue.

**Comment by jungkees** [comment]
@delapuente, the first job queued and run will be popped from the queue when the job finishes. So, the second job should have been aggregated no matter whether the job queue was empty or not when the first job arrived. That is, the consecutive update() calls will always be aggregated. So, only one update occurs. (Note that, if other type of jobs (register or unregister) are queued in between, the latter update jobs are queued.)

**Comment by mattto** [comment]
Closing this one as it's been settled and in the spec, though see related #1429.
