### ISSUE TITLE
Route showNotification() URLs through a fetch event?

### ISSUE THREAD

**Issue by alastaircoote** [w3c/ServiceWorker#1161]
Right now (on Firefox and Chrome, at least) any `image`, `icon` and `badge` URL passed into showNotification() goes straight to the remote URL. It would be a much better experience if those requests were routed through the fetch event, so that we could use cached assets instead.

There is a work-around using `cache.match()` -> `res.blob()` -> `FileReader.readAsDataURL()`, but it's pretty inefficient since the lack of `URL.createObjectURL` (as removed in #688) means that every image is turned into a base-64 encoded string. Since the introduction of the `image` attribute, some of these images can be pretty huge.

**Comment by jakearchibald** [comment]
We've already made this change in the spec, we're just waiting for browsers to catch up.

**Comment by alastaircoote** [comment]
Fantastic news. Thanks!
