### ISSUE TITLE
Range header is not send 

### ISSUE THREAD

**Issue by vardius** [w3c/ServiceWorker#1164]
Hi I have simple service worker, but my [Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) is not being send even thought i can log it on request object.

```javascript
    self.addEventListener('fetch', async function(event) {
        if (event.request.headers.get("range")) {
          const response = await fetch(event.request.clone());
    
          return  event.respondWith(this.getPartialResponse(event.request, response));
        }
    
        return  event.respondWith(fetch(event.request));
    }
    
    async getPartialResponse(req, res) {
      const pos = Number(/^bytes\=(\d+)\-$/g.exec(req.headers.get("range"))[1]);
      const ab = await res.arrayBuffer();
      const headers = new Headers(res.headers);
    
      headers.append("Content-Range", `bytes ${pos}-${ab.byteLength - 1}/${ab.byteLength}`);
      headers.append("Content-Length", ab.byteLength - pos + 1);
    
      return new Response(ab.slice(pos), {
        status: 206,
        statusText: "Partial Content",
        headers
      });
    }
```

Here you can see request one catched by service worker and the second one send to the api where you can notice the `Range` header is missing. Why ? My browser: `Chrome/59.0.3071.104`

![console 1](https://i.stack.imgur.com/jddiO.png)
![console 2](https://i.stack.imgur.com/5chlZ.png)

**Comment by jakearchibald** [comment]
We're tackling this at https://github.com/whatwg/fetch/issues/144

**Comment by AndySpider** [comment]
@vardius, Hi, just be interested, may off the topic, what's the browser you were using? And how did you send the movie.mp4 request?
I have some code run in Chrome, and I see Chrome never sends the "Range" header to my service worker... No idea how to make Chrome send request with the "Range" header.
