### ISSUE TITLE
Difference between disk and memory cache 

### ISSUE THREAD

**Issue by mishk0** [w3c/ServiceWorker#1174]
If the browser gets a file from its disk cache - it triggers a `fetch` event in SW, If gets from memory cache - it doesn't trigger a fetch. Is this behaviour according to spec? Reproduce it in Chrome (version 59.0.3071.115)

**Comment by wanderview** [comment]
I don't think chrome memory cache is spec'd.  There are some memory caches that are spec'd, though, like image cache.

Related to integrating this stuff to SW see #962.

**Comment by jakearchibald** [comment]
The img cache is spec'd to come before service worker. Unfortunately, other memory caches, such as `<link rel=preload>` aren't spec'd, but I expect them to behave like `<img>` in terms of their cache relative to the service worker. Namely:

* Their caches come before the service worker. As in, you'll get no fetch event if there's a cache hit.
* Fetches generated by these things will go through the service worker.

Closing in favour of https://github.com/whatwg/fetch/issues/354.
