### ISSUE TITLE
What can I guarantee when the promise returned by `register` resolves()

### ISSUE THREAD

**Issue by ConradIrwin** [w3c/ServiceWorker#1176]
Hi All, Apologies if this is a silly question. It seems like when I call `.register()` the promise resolves with a service worker that is active.

Is this guaranteed? Will there by at least any service worker (installing, waiting or active?) on the registration, or can there be none?

I tried tracing through the spec, and it seems (assuming I executed all the job instructions correctly) that this is probably true; but neither https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers or https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle say anything about it, so I'm left unsure as to whether this is something I can trust.

Assuming it is true, it might be nice to add something to https://www.w3.org/TR/service-workers-1/#navigator-service-worker-register that makes it clear what I can assume as a caller of the .register() method when the returned promise resolves.

**Comment by jakearchibald** [comment]
At least one of `reg.installing`, `reg.waiting` or `reg.active` will be a SW object.

I've got a doc sprint coming up, hopefully we can improve MDN as part of that.
