### ISSUE TITLE
Cross origin error due to htaccess restrictions

### ISSUE THREAD

**Issue by audas** [w3c/ServiceWorker#1181]
Sorry for the intrusion but I  just spent a few days with an issue where Firefox threw an error for service worker registration as my htaccess files had restrictions for requests OUTSIDE of the domain accessing non-white listed files (index.html etc).

To clarify - calling 

`navigator.serviceWorker.register('test_worker.js')`

Failed with the error 

> Service Worker Error DOMException [SecurityError: "The operation is insecure." code: 18 nsresult: 0x80530012]

Allowing the test_worker.js to be accessed directly from outside the host fixed the error. 

This was not required with Chrome. I find it a bit strange.

**Comment by jakearchibald** [comment]
Can you share the part of the htaccess they caused the issues?

**Comment by wanderview** [comment]
Is the mime-type correct?  I think chrome might support more mime-types than we do at the moment because we haven't updated to the latest spec there.

**Comment by jakearchibald** [comment]
Closing. Will reopen if we get more details.
