### ISSUE TITLE
Mixed feelings about ServiceWorker for module loader

### ISSUE THREAD

**Issue by Krinkle** [w3c/ServiceWorker#1203]
Here's a brief story about past attempts at considering use of ServiceWorker in Wikimedia's module loader.

### Current
I'll limit details to just the storing and fetching of modules.  For more, see <https://www.mediawiki.org/wiki/ResourceLoader/Features>.

The client has access to a manifest consisting of a dependency tree and version hashes. The page then instructs the client to load a list of modules for the current page.

Before touching the network, it first checks `localStorage` for blobs matching the requested keys (moduleName/moduleVersion). Matches are retrieved, parsed and scheduled for global-eval via `requestIdleCallback`. Any remaining modules that weren't cached (or version mismatch) are requested in a single batch request from the network. The server responds by providing each module in a way that allows the client to orchestrate execution (honouring the dependency tree) and stashes a copy in `localStorage` for future use.

### Why

_See also <https://meta.wikimedia.org/wiki/Research:Module_storage_performance>._

The main reason why, is to reduce wasted network bandwidth by creating "perfect cache fragmentation". We previously tried to maintain cache groups manually (typical "common", "app", "vendor", "page-specific" cache groups) which would inform the client to put certain modules in a separate request to improve chances of a client-side cache hits when navigating between different pages. But the majority of our modules are page specific, and some common (but small) modules chance frequently. Whenever one changes, the client would re-download the batch, despite a cache entry that was still valid for the most part. Unpacking the batch response client-side and using them directly has solved this problem. We also disabling batching requests in general (both prior to HTTP/2, and more recently), but we found similar findings as published elsewhere in the industry: the overhead is non-trivial and doesn't make for a net-win.

### Problem

Space in `localStorage` is precious and its traditional use (small values for state management, e.g. remembering state of a collapsible element) is hampered in a way that is increasingly hard to cope with. Especially due to the lack of any eviction mechanism (eg. TTL/LRU). In fact, we've had to disable our client-store in Firefox because our more active users that visit multiple *.wikipedia.org domains had their localStorage full in no time, at which point any other attempt to write data would fail, with no sensible way to clear it. ([T66721](https://phabricator.wikimedia.org/T66721))

### ServiceWorker

The first attempt to leverage SW was to basically disable the logic in the main thread, and just have it send a network request for all modules at once. The SW thread then does what the main thread used to do: Split the batch url into one-off urls, check the Cache API for each would-be request url, hold on to the responses while making a request for any cache misses, then once it comes back, respond to the original request with a concatenated response of both the cache hits and the network request.

Two regressions:
* Delay: Previously cache hits execute immediately, and only cache misses wait for the network. With the above, nothing executes until the last module comes back from the network because even if we add streaming logic and if browsers parse JavaScript programs in a streaming way, execution won't happen until the entire response is received.
* Overhead: Previously each cache hit was executed separately, thus letting requestIdleCallback control combination or distribution of execution in a friendly way. The network request still comes back at an undefined point with a potentially large payload, but with the above everything would always be combined and execute in one large uninterruptible burst.

### Cache API

After considering different ways for the above, I think the next-best thing is to consider using the Cache API directly from the main thread and basically just drop it in as a direct (async) replacement for localStorage. We'd get and set keys directly, and keep using `eval()`.

Thoughts?

**Comment by jakearchibald** [comment]
I agree with your conclusion – using the cache API from the window will be quicker and simpler.

Quick note on localstorage: Browsers are moving away from having limits per storage type, since it doesn't really make sense. Instead, the limits are per origin, and across all storage types.

I thought it was only Edge that still had separate limits per storage, but I may be wrong.

**Comment by wanderview** [comment]
We could get rid of the `eval()` if we permitted this, right?

```
let el = document.createElement('script');
el.src = await cache.match(url);
document.body.appendChild(el);
```

**Comment by jakearchibald** [comment]
Blob URLs could do it too.

**Comment by wanderview** [comment]
> Blob URLs could do it too.

Just make sure you call `revokeObjectURL()` or you are going to leak until the page closes.  Such a common problem, sadly.

**Comment by asutherland** [comment]
> I thought it was only Edge that still had separate limits per storage, but I may be wrong.

Firefox has separate limits for cookies, localStorage, sessionStorage, and the unified-by-"Quota Manager" IndexedDB/Cache API APIs.  We are migrating localStorage to operate with the unified "Quota Manager" framework and its generous storage budgets, but plan to maintain localStorage's per-origin rough 5MB limit counted over len(key)+len(value) for all stored tuples that ignores actual on-disk costs.   We do plan to relax our stricter "group" TLD+1 accounting for localStorage that is the source of the *.wikipedia.org problems to Quota Manager's more forgiving "group" TLD+1 accounting, however.

The reason we're keeping the limit intact is that we currently load and retain-in-memory the entirety of an origin's LocalStorage when we decide to load it at all.  Even if we further optimized our localStorage implementation to be more strategic in key loading and retention, more quota for localStorage is just more problems.

**Comment by GrosSacASac** [comment]
@Krinkle Have you tried to send your code to the DOM thread as it arrives in the service worker with postMessage ?

**Comment by Krinkle** [comment]
@GrosSacASac I haven't tried that, but I'm not sure where that would leave the actual fetch response. I guess I could have the response be empty with a no-cache header? Because otherwise, it would still arrive in the main thread and arrive twice.

I'm also not sure whether there is a performance overhead in sending all that data across threads.

Also, I was hoping that any solution involving ServiceWorker would also involve an improvement (not a regression) in debug-ability. E.g. where each logical resource would get its own entry in the Network panel. That would be an improvement. Right now I can sort-of get it by adding `//#sourceURL=` to the end of the eval string, but that only works if I eval each script separately, which I found to be significantly slower than running them all at once.

Ideally there'd be a way to both combine chunks (or otherwise avoid the performance penalty), but also stop executing when it takes too long. E.g. a way of combining a batch-eval with requestIdleCallback deadline, or some such. I was hoping that if I leave eval behind me and give control back to the browser through normal HTTP responses (via SW), that it would "Do the right thing". It would certainly allow the browser to start parsing the JavaScript code off-thread as soon as it has it, because it would know what its purpose would be before I trigger execution.

Although I don't know of any browser actually does that. And also, I suppose in a way it might not be certain of it because until I stitch the responses together, it could end up being used for something else, or the header changed to `text/plain`. And also, technically, combing responses can change the meaning of the script, so that won't be re-used either.

I suppose for the parse optimisation, it would need to be separate requests from the main thread, not just separate requests in SW.

**Comment by Krinkle** [comment]
Thanks all for your input. I'll close this now as it isn't really a ServiceWorker issue.
