### ISSUE TITLE
Require JS content type for serviceworkers is not present in the spec

### ISSUE THREAD

**Issue by shhnjk** [w3c/ServiceWorker#1209]
Below issue is said to be addressed.
https://github.com/w3c/ServiceWorker/issues/380

But I don't see this restriction being mentioned in the spec.
https://w3c.github.io/ServiceWorker/

**Comment by wanderview** [comment]
Search for "JavaScript MIME type".  For example step 7.7 here:

https://w3c.github.io/ServiceWorker/#update-algorithm

**Comment by shhnjk** [comment]
Which lands to https://html.spec.whatwg.org/multipage/scripting.html#javascript-mime-type, includes bunch of MIME Types. 

Issue 380 was a request to Strict MIME types to only application/x-javascript, text/javascript, or application/javascript

**Comment by wanderview** [comment]
Yea, that was changed in #1033.

**Comment by shhnjk** [comment]
Ah, okay. Thanks!

**Comment by wanderview** [comment]
Sounds like this is resolved, so going ahead and closing.  Feel free to re-open if there is still an issue.
