### ISSUE TITLE
The classic script's source text isn't defined in HTML any more

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#1212]
[Update](https://w3c.github.io/ServiceWorker/#update-algorithm) algorithm step 8 compares the updating script's source text against the installed script's source text. This check is to return early when the two scripts are byte identical.

I noticed HTML removed the definition of the source text from the classic script struct and added a record (Script Record) to the script struct instead.

I wonder if comparing the record.[[ECMAScriptCode]] of the two scripts would make sense or we should add the source text to the script struct again. From https://github.com/w3c/ServiceWorker/pull/1023#discussion_r92696321, the latter seems to be more appropriate I suppose.

/cc @domenic

**Comment by domenic** [comment]
Oh, sorry about this. It does sound like we need to add the source text back to the script record. I will try to add it back soon, per the comment you cited.

**Comment by jungkees** [comment]
That sounds good. I presume you meant to add it back to the script struct, right? We need non-parsed raw script texts for both classic scripts and module scripts.

**Comment by domenic** [comment]
Yep.

**Comment by jungkees** [comment]
https://github.com/w3c/ServiceWorker/commit/8e25c26efc932960a1449cf65de36dada371c867 closes this issue by comparing response bodies instead of source texts.
