### ISSUE TITLE
Clarity: "is dispatched a set of"

### ISSUE THREAD

**Issue by JosephPecoraro** [w3c/ServiceWorker#1214]
https://w3c.github.io/ServiceWorker/#service-worker-concept has:

> A service worker is dispatched a set of lifecycle events, install and activate, and functional events including fetch.

This read poorly. For a while I thought this was a typo of "dispatches". But perhaps this mean the service worker "is dispatched" meaning informed of / sent? Perhaps this could be reworded to be less confusing?

**Comment by jakearchibald** [comment]
https://github.com/w3c/ServiceWorker/pull/1217

**Comment by jakearchibald** [comment]
Thanks for reporting this!
