### ISSUE TITLE
Navigating reserved clients

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1215]
What happens if `.navigate()` is called on a reserved client (from `resultingClientId`)?

Failing in this case seems like the simplest thing to do. In this case the developer could navigate the `replacesClientId`.

**Comment by jakearchibald** [comment]
Alternatively, if `.navigate()` is called on a reserved client, we could try and redirect that call to the associated client that would be replaced.

This association doesn't exist right now, but it may be developer-friendly to create it.

**Comment by wanderview** [comment]
I think we decided that it should reject over here?  https://github.com/w3c/ServiceWorker/issues/1034#issuecomment-280357895

I guess the F2F note does not mention the navigate() method itself, just the properties.

**Comment by jakearchibald** [comment]
I thought we discussed it, but couldn't find the comment. I'll leave this open so we confirm at the f2f, but yeah I think rejecting is the right choice.

**Comment by wanderview** [comment]
Yea, I'd much rather expose the target client ID and let script redirect to their request there themselves instead of trying to do some kind of auto-magical mapping cross-process.

**Comment by jungkees** [comment]
Misclicked.

I agree to reject on reserved client.

**Comment by jakearchibald** [comment]
https://github.com/w3c/ServiceWorker/issues/1216 could remove this problem

**Comment by jungkees** [comment]
> #1216 could remove this problem

And #1034, #1035.

**Comment by jakearchibald** [comment]
Makes it sounds like a good idea 😄

**Comment by jakearchibald** [comment]
We aren't going to expose reserved clients, so this is no longer an issue.
