### ISSUE TITLE
How do I get extendableEvent.waitUntil() to play nicely with async functions

### ISSUE THREAD

**Issue by Zectbumo** [w3c/ServiceWorker#1237]
The `await` operator is a great way to clean up async code avoiding the "callback pyramid of doom" up until I ran into this case when I'm wrestling `waitUntil()` to wait for my async function to finish:
```javascript
self.addEventListener('install', async event => {
  var resolve, reject;
  event.waitUntil(
    new Promise((...callbacks) => {
      [resolve, reject] = callbacks;
    })
  );
  try {
    let cache = await caches.open(cacheName);
    await cache.addAll(cacheUrls);
    resolve();
  } catch (e) {
    reject(e);
  }
});
```
I would like access to the promise object made by the async function in order to dramatically clean up the code. For example:
```javascript
self.addEventListener('install', async event => {
  event.waitUntil(arguments.promise); // example access to the async function's promise
  let cache = await caches.open(cacheName);
  await cache.addAll(cacheUrls);
});
```
I know that I can create an async function and nest it inside the `waitUntil()` call but my request is to get access to the current promise in order to keep simple, concise, and highly readable procedural code and eliminate use of unnecessary nesting and anonymous functions.

**Comment by wanderview** [comment]
The typical pattern I've seen used is immediately invoking an async function passed to waitUntil:

```javascript
self.addEventListener('install', evt => {
  evt.waitUntil(async function() {
    await stuff();
  }()); // <-- see extra parens here
});
```

**Comment by Zectbumo** [comment]
Thanks @wanderview, I'm familiar with that pattern and I'm looking to access to the promise inside the async function. Having this would give a more readable solution without the use of anonymous functions, extra indentation level, and the `}());` cough drop sugar pill at the end.

**Comment by Zectbumo** [comment]
I would like the focus this issue to concentrate on keeping procedural programming intact. Javascript has been doing great at keeping multiple design patterns co-existing with each other. Using `await` keeps a straight forward line of execution. Using inline function nesting callbacks, I believe, will be universally frowned upon by 10 years. For good reasons unknown to me the `waitUntil()` broke the basic promise development pattern which in turn upset the await procedural style as I pointed out. I found that the missing link is the lack of the promise while inside an async function. Here is another example of a procedural style workaround:
```javascript
self.addEventListener('install', event => { event.waitUntil(installHandler(event)); });

async function installHandler(event) {
  let cache = await caches.open(cacheName);
  await cache.addAll(cacheUrls);
}
```

**Comment by jakearchibald** [comment]
Dupe. More data in https://github.com/w3c/ServiceWorker/issues/1148 and https://github.com/w3c/ServiceWorker/issues/256

**Comment by Zectbumo** [comment]
@jakearchibald  this is not a dupe since I am requesting access to the promise inside an asynchronous function. I am only using the `waitUntil()` as an example where this can benefit developers. I looked over the issues you mentioned and none mention the promise being accessed inside an async function so my request still stands.

**Comment by inexorabletash** [comment]
It sounds like you're wanting a new ECMAScript language feature to make the Service Worker API more usable. This is not the appropriate place to request that.

**Comment by Zectbumo** [comment]
@inexorabletash yes, thank you. I'll look up where I can do that. If you know the answer then please share.
