### ISSUE TITLE
 getRegistrations manipulates ES arrays in parallel steps

### ISSUE THREAD

**Issue by bzbarsky** [w3c/ServiceWorker#1241]
https://w3c.github.io/ServiceWorker/#navigator-service-worker-getRegistrations is manipulating "arrays" in parallel steps. The only "arrays" around in the web platform are ES Arrays, which is presumably what it's working with, since it then proceeds to resolve promises with some of these "arrays". It's not OK to touch ES arrays in parallel. Further, operations like adding to the array need to be carefully specified in terms of how it's actually done (defineProperty call? A property set? Something else?).

If these are meant to be infra Lists per https://infra.spec.whatwg.org/#lists that should be made explicit. Then the promise resolution bits need to be made a bit more explicit, possibly (e.g. how an Array is produced from the List).

**Comment by jakearchibald** [comment]
PR https://github.com/w3c/ServiceWorker/pull/1243/files
