### ISSUE TITLE
fetch() file stream fails when passing through fetch handler

### ISSUE THREAD

**Issue by Zectbumo** [w3c/ServiceWorker#1246]
I am trying to stream a selected file using `fetch()` and when the serviceworker fetch handler intercepts the fetch it make the fetch fail. If I don't register the fetch handler then the fetch succeeds. How can I get a file to stream through a fetch while I'm online and using a service worker?

Error:
```
Uncaught (in promise) TypeError: Failed to fetch
PUT https://example.com/upload net::ERR_FAILED
```
HTML:
```html
<input type='file' onchange='upload(event)'>
```
Javascript:
```js
navigator.serviceWorker.register('service.js')

async function upload(event) {
  let file = event.target.files[0];
  let res = await fetch('upload', {
    method: 'PUT',
    body: file,
    mode: 'same-origin',
    credentials: 'same-origin'
  });
}
```
service.js:
```js
onfetch = event => {event.respondWith(fetchHandler(event))};

async function fetchHandler(event) {
  let response = await caches.match(event.request); // 'upload' not in cache
  return response || fetch(event.request);
}
```

**Comment by jakearchibald** [comment]
This seems like a Chrome/Firefox bug to me.

Live demo: https://post-file-serviceworker-test.glitch.me/.

Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=793783
Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1424701

Closing this, as I don't think it's a spec issue.

**Comment by jakearchibald** [comment]
FWIW, this works fine in Edge with service workers enabled.

**Comment by wanderview** [comment]
Thanks for filing bugs.  It would be good to get WPT coverage for this.

**Comment by Zectbumo** [comment]
Yes! My first service worker bug discovery.

**Comment by huangjihua** [comment]
thanks!
