### ISSUE TITLE
Until resultingClientId is implemented, what should FetchEvent.clientId be for navigation requests?

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1266]
Historically we have not provided a `FetchEvent.clientId` value for navigation requests.  Both firefox and chrome returned `null` instead.

When `resultingClientId` was spec'd the plan became to start setting this value.  Until that is implemented, though, we chose not to expose `FetchEvent.clientId` in case sites were relying on that to infer navigation requests somehow.

Until that implementation happens, however, we have this WPT check:

https://github.com/w3c/web-platform-tests/blob/master/service-workers/service-worker/resources/clients-get-worker.js#L7

Up until recently this checked that `null` was provided.  It appears @youennf changed this to require empty string instead.  As a result both firefox and chrome are timing out all tests using this worker script.

My question is how should we resolve this?  My thoughts:

* We are maintaining null explicitly for backward compat right now.  Of course the spec doesn't say to do this currently.  The spec has the new resultingClientId language.
* Nothing in the spec says to explicitly set it to empty string.  Its says to use empty string if not set, but the spec says to override it with a real value when dispatching a FetchEvent.

If there are objections to testing for the historical value of `null` it seems like maybe we should just remove the check from the test.  I don't think we should require empty string here, though, because no shipping browser does that and it also doesn't match the spec.

@jakearchibald @jungkees @aliams @youennf What do you all think?

**Comment by wanderview** [comment]
Or we could change it to a falsy test instead.

**Comment by wanderview** [comment]
Also cc @mattto for his opinion.

**Comment by mattto** [comment]
Thanks for flagging this. I just noticed the fetch-event.https.html test also changed and Chrome and Firefox are failing in the same way for "Service Worker responds to fetch event with an existing client id" at https://wpt.fyi/service-workers/service-worker/fetch-event.https.html.

Is there a reason we decided empty string is better than null to indicate "no id"?

**Comment by mattto** [comment]
Of course it would be best for the WPT tests to reflect the current spec. I would rather they fail in a nicer way than just timeout, e.g. instead just fail one assertion like that fetch-event.https.html test.

In the particular case of clients-get-worker, I'd probably vote to remove the clientId check and just rely on fetch-event.https.html for test coverage.

I'm still wondering though if we needed to make the change from null to empty string for client ids.. what did resultingClientId and targetClientId have to do with that decision?

**Comment by wanderview** [comment]
> In the particular case of clients-get-worker, I'd probably vote to remove the clientId check and just rely on fetch-event.https.html for test coverage.

I addressed your one review comment.  If you approve the WPT PR I can land this fix for now.  I think this is ok since we have fetch-event.https.html coverage as you pointed out.  I'd like to get our WPT coverage turned back ASAP on for the tests effected by this.  I'm in the middle of touching code that effects other things covered by these tests.

> I'm still wondering though if we needed to make the change from null to empty string for client ids.. what did resultingClientId and targetClientId have to do with that decision?

I think its probably an ergonomics thing?  If you can assume the type of the id is always a string perhaps it makes it easier to work with.

**Comment by wanderview** [comment]
The change to empty string was made in this spec commit:

https://github.com/w3c/ServiceWorker/commit/8b483b091e0f0bae6b698cf05d915c2029748ae0

Which I think is related to #870.  I don't see any discussion of null-vs-empty-string though.  Maybe @jungkees knows.

**Comment by mattto** [comment]
I see, thanks for tracking that down. Is there something like a web spec style guide that has conventions for things like this (empty string vs null)?

**Comment by wanderview** [comment]
Not sure.  I asked @annevk on IRC he kind of thought maybe the ergonomics thing as well:

```
9:47 AM <wanderview> annevk: do you know why FetchEvent.clientId might have gone from
null to empty string for indicating "no client id"?  Is that conforming to an overall spec
convention or something?
9:49 AM <annevk> wanderview: I'm not sure; I might have argued that if it cannot be the empty
string it always being a string seeming nicer
```

**Comment by jungkees** [comment]
> I don't see any discussion of null-vs-empty-string though. Maybe @jungkees knows.

In https://github.com/w3c/ServiceWorker/commit/8b483b091e0f0bae6b698cf05d915c2029748ae0, we effectively changed semantics of `clientId` from either-fetch-client-or-null-for-navigation to always-fetch-client (introducing `resultingClientId`.) We changed `clientId` to non-nullable DOMString as such. After that change, the expectation is `clientId` is always set to a string value initialized in HTML. Also, I think we had come across some discussion somewhere that using the empty string over null helps ergonomics.

For compatibility before implementing `resultingClientId`, will it help to change V1 spec back to set `clientId` to null for navigation requests and change its type to nullable adding a note to explain the future plan? (I've tested EdgeHTML also returns null. Haven't tested WebKit yet.)

**Comment by mattto** [comment]
Thanks Jungkee. I'm not sure about reverting the spec. If the plan is to make it empty string in the end, it'd be better to start making that change in the implementations sooner than later.

If it's better for devs to be the empty string, I think I'm comfortable making the change (I'm trying to investigate whether sites that would break). But I don't quite get how the semantics changed: even with resultingClientId, clientId for navigations is non-existent/null/empty and it seems that could be validly expressed as empty string or null.

It'd be good to know what WebKit does.

**Comment by youennf** [comment]
WebKit aligns with the spec and uses an empty string in that case.
I guess the existing tests could be updated to check for !!event.clientId.

**Comment by mattto** [comment]
OK, I think I'm going to move to change Chrome to use the empty string. @wanderview @aliams any objections to that?

**Comment by jungkees** [comment]
> (I'm trying to investigate whether sites that would break)

Thanks for checking this.

> But I don't quite get how the semantics changed: even with resultingClientId, clientId for navigations is non-existent/null/empty and it seems that could be validly expressed as empty string or null.

By introducing `resultingClientId`, I thought we'll set `clientId` for a navigate request to the [source browsing context](https://html.spec.whatwg.org/#source-browsing-context)'s active document's environment's id. (See https://html.spec.whatwg.org/#process-a-navigate-fetch step 2 where the request is set up. `FetchEvent.clientId` is set to request's client's id later in Handle Fetch.) So, I think changing from null to the empty string wouldn't reflect the semantics we'll have in the final behavior.

**Comment by mattto** [comment]
> So, I think changing from null to the empty string wouldn't reflect the semantics we'll have in the final behavior.

@jungkees I'm a bit confused. In the final behavior, for a navigation request, will FetchEvent.clientId actually be populated with something rather than being empty/null? Is this a special case with about:blank?

**Comment by wanderview** [comment]
> After that change, the expectation is clientId is always set to a string value initialized in HTML.

Just to clarify, I think there will be cases where its still not set.  For example, a user opening a new tab and navigating to a URL will not have any `clientId` for the navigation `FetchEvent`, correct?  There is no current Client to populate the value.

I think its a little unclear what happens for `window.open()`, `iframe.src`, `clients.openWindow()`, etc, but the intention was for those to have a populated `clientId`.

**Comment by wanderview** [comment]
> OK, I think I'm going to move to change Chrome to use the empty string. @wanderview @aliams any objections to that?

Yea, we can do this in firefox as well.  I just wanted to make sure we were all on the same page about it.

**Comment by wanderview** [comment]
> @jungkees I'm a bit confused. In the final behavior, for a navigation request, will FetchEvent.clientId actually be populated with something rather than being empty/null? Is this a special case with about:blank?

I split this off into a separate spec issue to discuss.

**Comment by wanderview** [comment]
Since we changed the test not to enforce navigation FetchEvent.clientId and we are going to implement empty string for missing clientId, I think we can mark this closed.

**Comment by mattto** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=807818

**Comment by wanderview** [comment]
Gecko bug for non-nullable FetchEvent.clientId: https://bugzilla.mozilla.org/show_bug.cgi?id=1434913
