### ISSUE TITLE
Query Cache algorithm contains orphaned 'f' references

### ISSUE THREAD

**Issue by inexorabletash** [w3c/ServiceWorker#1280]
> If _fieldValue_ matches "*", or the **combined value** given _f_ and _cachedRequest_’s **header list** does not match the **combined value** given _f_ and _request_’s **header list**, then:

_f_ is never defined anywhere. From context, I assume it's _fieldValue_.

**Comment by jungkees** [comment]
Thanks for spotting this. I missed it in https://github.com/w3c/ServiceWorker/commit/c8ab7142412bcc7d65377af9dc513282910493b1.

**Comment by jungkees** [comment]
They should be replaced by _fieldValue_, and we're working on #1281.
