### ISSUE TITLE
Detect Abort Events in Service Worker

### ISSUE THREAD

**Issue by AnthumChris** [w3c/ServiceWorker#1284]
It would be great if Service Workers could detect the "abort" event that _should_ fire on the DOM when users cancel a document load (e.g. `window.stop()`, ESC key, browser stop button).  Perhaps:
1. SWs could detect "abort" events directly.
1. SWs could detect "aborts" indirectly (via "onmessage" event handlers triggered by application). This doesn't currently seem possible, because the "abort" event doesn't currently fire on the DOM  (See https://github.com/whatwg/html/issues/3525).

This would be specifically useful when implementing custom Streams in Service Workers.  The SW could detect "abort" events, close open streams, do cleanup, or send notifications to the underlying application.

For example, this SW progress indicator demo (https://fetch-progress.anthum.com/sw-basic/) implements a `ReadableStream` and has no way to for the SW to respond when the document load is aborted.  Additionally, the network transfer continues in Chrome (Firefox successfully stops it), which may be different issue entirely.

**Comment by jakearchibald** [comment]
This was solved in https://github.com/w3c/ServiceWorker/commit/5474d11143611709eeccf3102f2d1eb459e3789e, but I don't think there are any implementations yet.

More details: https://developers.google.com/web/updates/2017/09/abortable-fetch#in_a_service_worker.
