### ISSUE TITLE
Interaction of fetch abort with Cache APIs

### ISSUE THREAD

**Issue by ricea** [w3c/ServiceWorker#1286]
What error should be returned from put() and add() if the fetch is aborted using AbortSignal?

In other words, what should code like this log?

```javascript
  const controller = new AbortController();
  const signal = controller.signal;
  const request = new Request('slow', { signal });
  const response = await fetch(request);
  const cachePromise = cache.put(request, response);
  controller.abort();
  try {
    await cachePromise;
    console.log('unwanted success');
  } catch (e) {
    console.log(e);
  }
```

**Comment by mattto** [comment]
cc/ @jakearchibald: does the spec just need to be updated to handle this? Based on your blog post at https://developers.google.com/web/updates/2017/09/abortable-fetch, it looks like the intent is to throw an AbortError? (see https://chromium-review.googlesource.com/c/chromium/src/+/954765)

**Comment by wanderview** [comment]
AbortError works for me.

Also, AFAIK the spec doesn't really treat writing the body as an operation that takes time.  It just sort of implies a synchronous write by saying:

`Append operation’s request/operation’s response to cache.`

It would be nice if this was changed to use stream language for writing the body.  Then the abort operation would be easier to represent.

**Comment by ricea** [comment]
I just noticed this line in the standard:

> If response’s aborted flag is set, reject responsePromise with an "AbortError" DOMException and abort these steps.

That answers my question.
