### ISSUE TITLE
Cache API: Cache-Control headers and Opaque Responses

### ISSUE THREAD

**Issue by inexorabletash** [w3c/ServiceWorker#1299]
By design, the Cache API does not respect cache-control headers; storing and deleting is done explicitly via the API. For non-opaque responses, this doesn't extend the capabilities of script; a non-opaque response could be read and a synthetic response with the same content stored instead.

As @mkruisselbrink raises in https://bugs.chromium.org/p/chromium/issues/detail?id=828420 though, _"the interesting question is indeed what to do about CacheControl headers on opaque responses, as arguably there it was the intention of the server that it shouldn't be stored. "_

(Failing the store would presumably itself be an information leak...)

**Comment by wanderview** [comment]
I don't suppose anyone has any data on how often this happens...

**Comment by wanderview** [comment]
Would the From-Origin header proposed in https://github.com/whatwg/fetch/issues/687 help here?  It would allow these sites to avoid having their resources loaded as opaque resources in hostile origins at all.

**Comment by annevk** [comment]
I think recommending sites to use `Cross-Origin-Resource-Policy: same-origin` is indeed the way to go here. Let's not further complicate the caching logic as it will not make things more secure.

**Comment by wanderview** [comment]
Can we close this issue?

**Comment by inexorabletash** [comment]
Pending further data, SGTM.
