### ISSUE TITLE
Responding to cross-origin requests using a worker?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/ServiceWorker#130]
I was wondering how this situation was possible:
- There's no harm in responding to a cross-origin request with a new SameOriginResponse() that you create out of thin air. Since the document in question is the thing that's at risk, and since the other APIs available to you won't allow you undue access to cross-origin response bodies, you can pretend you're any other origin -- so long as the only person you're fooling is yourself.

It seems to me that a service worker can only reply to requests to its own server, and all those requests are by definition same-origin.

Or can a worker installed from "domain.com" reply to a request of "a.domain.com" to a resource of "b.domain.com"? Even if so, my interpretation is that the "same origin" in this case is still "b.domain.com" and not "a.domain.com" or "domain.com".

What was the intent here?

**Comment by Pacerier** [comment]
@jakearchibald, @all; Anyone can solve [chrome ext crossorigin serviceworker](https://stackoverflow.com/questions/41350291/how-to-use-service-workers-in-google-chrome-extensions-to-modify-an-http-respons#comment80466980_41350291)?
