### ISSUE TITLE
Create F2F agenda - 25 October 2018

### ISSUE THREAD

**Issue by jatindersmann** [w3c/ServiceWorker#1303]
# Where

**Location:** [TPAC](https://www.w3.org/wiki/TPAC/2018), Lyon, France.
**When:** 9AM, October, 25, 2018

# Minutes

* https://www.w3.org/2018/10/25-serviceworker-minutes.html

# Attendance

Please let us know if you're planning on attending the F2F meeting.

# Agenda

The agenda is subject to change reflecting the progress of the work. Please update it if you notice things outdated or missing.

## Implementer update

Share implementation status and issues, performance issues, compatibility issues, etc.

* Discuss on the concerns Safari folks had around the push API.

## Changes & bugs

* Multiple service worker instances
  * Allowing multiple worker threads: https://github.com/w3c/ServiceWorker/issues/756.
  * Exposing mulitple instances via DOM: https://github.com/w3c/ServiceWorker/issues/1185.
  * Using separate instances for each functional event: https://github.com/w3c/ServiceWorker/issues/756#issuecomment-325721645.
* Service worker resurrection
  * Should we ditch resurrection?: https://github.com/w3c/ServiceWorker/issues/1204.
  * Behavior of `ready` promise when controlling rgistration is resurrected: https://github.com/w3c/ServiceWorker/issues/1198.
* `ready` promise weirdness
  * `ready` promise is kind of weird with overlapping scopes: https://github.com/w3c/ServiceWorker/issues/1278.
  * `ready` promise is kind of weird after you call unregister(): https://github.com/w3c/ServiceWorker/issues/1279.
* Does changing `updateViaCache` mint a new `ServiceWorkerRegistration` or update them all?: https://github.com/w3c/ServiceWorker/issues/1189. This is being implemented. We need to help them by working on the corresponding part of the spec.
* FetchEvent.navigationLoadType: https://github.com/w3c/ServiceWorker/issues/1167. The spec and the implmentations are underway. We need to review them.
* Is the browser required to start the ServiceWorker for `postMessage()` if there is no message event handler?: https://github.com/w3c/ServiceWorker/issues/1200, https://github.com/whatwg/dom/issues/371#issuecomment-378476612.
* Async waitUntil microtask issue: https://github.com/w3c/ServiceWorker/issues/1213.
* "no-cors" CSS SOP violation: https://github.com/w3c/ServiceWorker/issues/719.
* What happens to the request body if the fetch isn't handled?: https://github.com/w3c/ServiceWorker/issues/1191.
* Exposing the identity of service workers and a clients: https://github.com/w3c/ServiceWorker/issues/1077, https://github.com/w3c/ServiceWorker/issues/643.
* "Unregister" operation may be interrupted by `ServiceWorker#postMessage`: https://github.com/w3c/ServiceWorker/issues/1146.
* Should a service worker be allowed to register new service workers?: https://github.com/w3c/ServiceWorker/issues/1117.
* What happens if an initial about:blank inherits a controller, but its navigation request does not match any service worker?: https://github.com/w3c/ServiceWorker/issues/1232.
* Should `Client.navigate()` reject on uncontrolled clients?: https://github.com/w3c/ServiceWorker/issues/1254.
* `updatefound` event in service worker context seems unreliable: https://github.com/w3c/ServiceWorker/issues/1255.
* Should blob URLs inherit controller from parent environment or environment that called `createObjectURL`: https://github.com/w3c/ServiceWorker/issues/1261.
* Should local URLs check origin before inheritting a controller?: https://github.com/w3c/ServiceWorker/issues/1262.
* Should a SW `client.id` persists across Discards/Reloads of the same page?: https://github.com/w3c/ServiceWorker/issues/1263.
* Scope matching algorithm breaks sites that don't end in a slash: https://github.com/w3c/ServiceWorker/issues/1272.
* Should the worker be removed from the registration *before* its state is set to "redundant"?: https://github.com/w3c/ServiceWorker/issues/1273.
* The Cache objects do not expire unless authors *or users* delete the entries.: https://github.com/w3c/ServiceWorker/issues/1276.
* Possible race between Activate and Update Algorithms: https://github.com/w3c/ServiceWorker/issues/1285.
* Consider a method to force immediate disk deletion even if there are live Cache/Response js objects: https://github.com/w3c/ServiceWorker/issues/1287.
* SharedWorker script interception after redirects: https://github.com/w3c/ServiceWorker/issues/1289.
* `Client.postMessage()` throwing for unloaded client is problematic: https://github.com/w3c/ServiceWorker/issues/1291.
* Confusion around new events after `skipWaiting`: https://github.com/w3c/ServiceWorker/issues/1295.
* Cache API: Cache-Control headers and Opaque Responses: https://github.com/w3c/ServiceWorker/issues/1299.
* Should prefetch loads trigger FetchEvents?: https://github.com/w3c/ServiceWorker/issues/1302.
* Spec says `update()` should resolve to a registration, but browsers do different things: https://github.com/w3c/ServiceWorker/issues/1304.
* How can `unregister()`'s same-origin check ever fail?: https://github.com/w3c/ServiceWorker/issues/1305.
* Service-Worker-Allowed can be cross-origin to the script URL.: https://github.com/w3c/ServiceWorker/issues/1307.
* Merge with storage: https://github.com/w3c/ServiceWorker/issues/1230.
* Background Fetch review
  * Related issues: Keeping the service worker awake during a fetch. Does Background Fetch satisfy these requirements?
    * Error handling for aborted streams feeding a navigation request: https://github.com/w3c/ServiceWorker/issues/1184.
    * How long can the service worker stay awake during an active fetch: https://github.com/w3c/ServiceWorker/issues/1182.
* Covering use cases of foreign fetch?
* Dynamic import modules: https://github.com/w3c/ServiceWorker/issues/1356
* No way to beacon during activate: https://github.com/w3c/ServiceWorker/issues/1336

## WPT status

TODO: Update this section.

## Interesting feature requests
* Bypassing the service worker in particular cases
  * Proposal: Allow `addEventListener`/`removeEventListener` for '`fetch`' to called at anytime: https://github.com/w3c/ServiceWorker/issues/1195.
  * Consider mechanisms to bypass the service worker for things that we know won't be in it's cache: https://github.com/w3c/ServiceWorker/issues/1026.
* Service workers in the clients API & adding to windows
  * `Clients.matchAll()` should exclude the current environment: https://github.com/w3c/ServiceWorker/issues/1037.
  * Support returning ServiceWorker Client environments from `Clients.matchAll()`: https://github.com/w3c/ServiceWorker/issues/1036.
  * Consider exposing `self.clients` on window and other worker globals: https://github.com/w3c/ServiceWorker/issues/955.
* Recovering from fetch failures: https://github.com/w3c/ServiceWorker/issues/939.
* Enabling multiple Service Workers for a single scope: https://github.com/w3c/ServiceWorker/issues/921.
* Consider providing `navigation` event: https://github.com/w3c/ServiceWorker/issues/1028.
  * Service Worker Launch Event: https://wicg.github.io/sw-launch/
  * https://github.com/w3c/manifest/issues/597
  * A way to control which client (or type of client) receives a navigation: https://github.com/w3c/ServiceWorker/issues/758.
* Lifecycle for the web
  * User initiated 'uninstall' event: https://github.com/w3c/ServiceWorker/issues/998.
  * WICG proposal: https://github.com/WICG/web-lifecycle.
  * Back forward cache
    * Consider how Client API should behave with bfcache: https://github.com/w3c/ServiceWorker/issues/1038.
* Consider firing a "clientcontrolled" event on ServiceWorkerGlobalScope: https://github.com/w3c/ServiceWorker/issues/886.
* Allow caches to opt-in to granular cleanup: https://github.com/w3c/ServiceWorker/issues/863.
* Preventing / delaying service worker updates
  * Preventing server-forced updates: https://github.com/w3c/ServiceWorker/issues/822.
  * Feature request: Provide a way to delay execution of a new service worker: https://github.com/w3c/ServiceWorker/issues/1208.
  * Allow preventing the update process to finish: https://github.com/w3c/ServiceWorker/issues/761.
* Save initial files into cache storage instead of browser's cache: https://github.com/w3c/ServiceWorker/issues/820.
* `registration.ready` promise: https://github.com/w3c/ServiceWorker/issues/770.
* Support updating multiple service workers coherently: https://github.com/w3c/ServiceWorker/issues/727.
* A way to immediately unregister a service worker: https://github.com/w3c/ServiceWorker/issues/614.
* Consider exposing size for cache entries: https://github.com/w3c/ServiceWorker/issues/587.
* Provide a one-line way to listen for a waiting Service Worker: https://github.com/w3c/ServiceWorker/issues/1222.
* Provide a way to skipWaiting when the last tab refreshes: https://github.com/w3c/ServiceWorker/issues/1238.
* Provide an easier way to listen for waiting/activated/redundant Service Workers: https://github.com/w3c/ServiceWorker/issues/1247.
* Service Worker handling of first page load subresources: https://github.com/w3c/ServiceWorker/issues/1282.
* Allow users to extend ExtendableEvent, anywhere: https://github.com/w3c/ServiceWorker/issues/1290.
* Formalizing a timeout API: https://github.com/w3c/ServiceWorker/issues/1292.
* Allow active worker to immediately evict itself: https://github.com/w3c/ServiceWorker/issues/1296.
* Give a fine grade to the Service Worker's lifetime: https://github.com/w3c/ServiceWorker/issues/1297.

## V1

Should have been done by this point.

* Issues: https://github.com/w3c/ServiceWorker/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+1%22.

**Comment by wanderview** [comment]
If possible I'd like to discuss a proposal for a new API to help sites measure the performance of their FetchEvent handlers.  It spans both the WebPerf and ServiceWorker API surface.  I'm going to be discussing it in WebPerf on Friday, but I'd also like to discuss with the ServiceWorker group on Thursday if possible.

The explainer for this proposal can be found here:

https://github.com/wanderview/fetchevent-worker-timing/blob/master/explainer.md

Thanks!

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
@jatindersmann huge thank you for getting the agenda together. I realise I've been totally useless this time around.

If we get time, I'd like to discuss:

* `cache.match` generating partial responses [#913](https://github.com/w3c/ServiceWorker/issues/913).
* I'd like to get cross-implementation feelings about performance state & goals, and I promise not to say "static routes" (this is a lie).

And that's it, @jatindersmann already captured everything else.

**Comment by jakearchibald** [comment]
Also: We didn't have a meet-up this year. Was that a bad thing?

**Comment by tomayac** [comment]
One thing that came up in the *Devices and Sensors WG* and that I would like to discuss is *geofencing* and how it relates to service workers. Abstracting from that, essentially we are looking for some sort of mechanism ("Alarms API") to *wake up a service worker* based on an event (which could be a geofence being crossed but should not be limited to that) to do some work. Here is the related issue: https://github.com/w3c/geolocation-sensor/issues/22.

**Comment by jakearchibald** [comment]
A couple of folks today have mentioned the complexity of testing service workers (@yoavweiss, @rniwa). We could introduce something specific for testing mode (we [did something similar for background fetch](https://wicg.github.io/background-fetch/#automation)), but maybe we can do something that would benefit regular users too?

**Comment by jakearchibald** [comment]
@tomayac isn't this covered by https://w3c.github.io/ServiceWorker/#extensibility?

**Comment by tomayac** [comment]
> Isn't this covered by https://w3c.github.io/ServiceWorker/#extensibility?

@jakearchibald This is exactly what I would want to discuss. Or if there needs to be another primitive.

**Comment by jakearchibald** [comment]
@tomayac could you write up an issue or DM me about this? I think I can answer this before Thursday, & it doesn't need to take up the time of the room. If it turns out it *does* need the room to discuss, at least we'll have the problem written up in a way that gets everyone caught up quickly.

**Comment by tomayac** [comment]
A chat with @jakearchibald indeed removed the need to discuss this. It's covered by https://w3c.github.io/ServiceWorker/#extensibility.

**Comment by jakearchibald** [comment]
Action item: Now's the time to provide something like `.ready` for a specific registration.

`.ready` returns the same promise forevermore, which is confusing. Look at deprecating and doing something better.

**Comment by ewilligers** [comment]
I'd also like to discuss [File Handling](https://github.com/ewilligers/file-handling/blob/master/explainer.md).

**Comment by jakearchibald** [comment]
Things linkedin would like this see:

* `unregister({ force: true })` - unclaims pages.
* `skipWaiting({ deadline: 0 })` - kill the current active service worker regardless of events after this time.

**Comment by jakearchibald** [comment]
AI for @jakearchibald create an issue for a rough static routes proposal.

**Comment by DeltaEvo** [comment]
Hello,

I was interested in Foreign Fetch, is something has been discussed to cover it's use cases?

Sorry to bother you and thanks for your attention :smile:

**Comment by wanderview** [comment]
@DeltaEvo We did not end up discussing foreign fetch use cases at this meeting.  Sorry.

**Comment by asakusuma** [comment]
@jakearchibald 
FWIW, there's already a [`terminate()`](https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate) for web workers. Not sure if using the same name would be confusing or better. Probably confusing if we add service worker specific options.

It's unclear to me what exactly `unregister({ force: true })` vs `terminate()` would mean. I believe the simplest MVP to accomplish what we (linkedin) want would be to add options to `unregister()` that allow immediately stopping any new events being sent to the service worker (even for already opened clients) and then terminating all associated workers (and their associated tasks) with some time guarantee. For instance:

```
// Immediately stop sending events to the service worker, all workers will be completely gone within 10 seconds.
navigator.serviceWorker.unregister({
  unclaim: true,
  terminateDeadline: 10000
});
```

I believe "unregister" is simpler, because it doesn't have to deal with transitioning events to another worker, which is needed if the active worker is terminated and there's a waiting/installed worker.

**Comment by asakusuma** [comment]
@mattto good call, though I'm not actually sure which issue to move to. https://github.com/w3c/ServiceWorker/issues/614 or https://github.com/w3c/ServiceWorker/issues/1296 might also fit

**Comment by mattto** [comment]
@asakusuma Ah fair enough, we can continue here. As an implementor I feel I like the contract of  unregister(force) or skipWaiting(timeout) over terminate(). Whether to declaim clients or evict the active worker is only indirectly related to whether the active worker is actually running. I can imagine some race conditions where we terminate the active worker but it gets woken up before activation can be triggered.

**Comment by asakusuma** [comment]
@mattto not sure I follow the theoretical race condition. How would the terminating worker get woken up if events are no longer being sent from the clients?

If we can table terminate for now, let's move the conversation to https://github.com/w3c/ServiceWorker/issues/1303

**Comment by arpit-gagneja** [comment]
@jakearchibald any updates on https://github.com/w3c/ServiceWorker/issues/1026?
I wish service worker API can provide us the ability to bypass the service worker for certain cases. I have experienced the performance regression on the page load time when there are too many network requests.
