### ISSUE TITLE
sometimes, we cannot find the request in webview when we use the serviceworker 

### ISSUE THREAD

**Issue by normanfan** [w3c/ServiceWorker#1312]
the webview will display the empty page when we use the serviceworker in android. However, the webview will display right when we remove the service worker

**Comment by jakearchibald** [comment]
This isn't anything to do with the spec. If you think it's a Chrome bug, file it at crbug.com. However, please create a demo page that shows a demo of the issue, else it's unlikely to be fixed (as engineers won't know what you're experiencing).
