### ISSUE TITLE
How to report install progress back to the DOM ?

### ISSUE THREAD

**Issue by GrosSacASac** [w3c/ServiceWorker#1324]
Inside the "install" handler, what is the proper way to report the DOM how many files have been cached and how many are still downloading ?

This question is only relevant when there are multiple MB of files to cache or when the connection is slow.

**Comment by jakearchibald** [comment]
Use `postMessage` on client objects https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage.

To get clients https://developer.mozilla.org/en-US/docs/Web/API/Clients/matchAll.

**Comment by GrosSacASac** [comment]
I'll make a minimal example, last time I tried, getClients and postmessage was not available during install.

**Comment by wanderview** [comment]
You need to use `includeUncontrolled: true` because installing service workers will never be controlling any clients.

**Comment by GrosSacASac** [comment]
Thanks that was it !
