### ISSUE TITLE
I am loosing my revenue because of sandbox

### ISSUE THREAD

**Issue by Srikanth80792** [w3c/ServiceWorker#1330]
Hello Guys, I am streaming some videos on my website with domain protect. And put pops and banner ands on that player. 

But some of webmasters creating my player page iframe by using sandbox attribute. (I am loosing bandwidth with 0 revenue.) I am investing on servers and on streaming content and webmasters using sandbox attribute like their own content. 

I don't want to block iframe because i dont have problem with those webmasters who are not using sandbox because I can earn from them. I can block webmasters who are using sandbox but I want to earn from those webmasters also who are using sandbox.

ANY SOLUTIONS?

**Comment by jakearchibald** [comment]
Does this have anything to do with service workers?
