### ISSUE TITLE
Align "uncaught runtime script error" with the HTML spec

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1334]
The Update algorithm has:

> 16. Invoke Run Service Worker algorithm..
> 17. If an uncaught runtime script error occurs during the above step, then...

Step 17 is a bit vague: does it refer to just script errors or if JS execution was interrupted for some reason (I think Chrome may do this from DevTools or some system error). I believe the HTML and ES spec calls all such states "abrupt completion". We could refer to that.

Run Service Worker invokes:
> If script is a classic script, then run the classic script script. Otherwise, it is a module script; run the
> module script script.

[Run the classic script](https://html.spec.whatwg.org/multipage/webappapis.html#run-a-classic-script) returns undefined on an abrupt completion. [Run the module script](https://html.spec.whatwg.org/multipage/webappapis.html#run-a-module-script) doesn't return anything but it can probably be extended to, or we can handwave with "if script's evaluationStatus is an abrupt completion".

**Comment by domenic** [comment]
We could definitely make the "run an X script" return the actual completion records, if other callers would use them.

**Comment by mattto** [comment]
This was addressed by https://github.com/w3c/ServiceWorker/pull/1346.
