### ISSUE TITLE
Worker Update leaves open notifications behind (unclickable)

### ISSUE THREAD

**Issue by gbhrdt** [w3c/ServiceWorker#1337]
We open clickable notifications trough our ServiceWorker. When the browser then updates a ServiceWorker (cache expired, or forces trough `ServiceWorkerRegistration.update`), the remaining open notifications become *unclickable*.
I am not sure if should be is the desired behaviour or if I am missing something here.

**Comment by wanderview** [comment]
This sounds like a browser bug.  Can you file bugs on the appropriate browser(s) issue tracker?  I'm sure a reproducible test case using glitch.com or something would help get it looked at quicker.  Thanks.

**Comment by wanderview** [comment]
Thanks.  I'm closing this spec issue since it appears to be a browser bug.
