### ISSUE TITLE
preloadResponse resolved to wrong kind of thing?

### ISSUE THREAD

**Issue by jyasskin** [w3c/ServiceWorker#1339]
In https://w3c.github.io/ServiceWorker/#handle-fetch, we have:

> Let preloadResponseObject be a new Response object ...
> ...
> To [process response](https://fetch.spec.whatwg.org/#process-response) for navigationPreloadResponse, run these substeps:
> ...
> Associate preloadResponseObject with navigationPreloadResponse.
> Resolve preloadResponse with navigationPreloadResponse.
> ...
> Initialize e’s preloadResponse to preloadResponse.

This makes *navigationPreloadResponse* a [response](https://fetch.spec.whatwg.org/#concept-response) struct and *preloadResponseObject* a [Response](https://fetch.spec.whatwg.org/#response) JS object. e's preloadResponse gets exposed to JS, so it's weird or wrong to resolve it with a struct instead of an object.

Unless I'm misreading this. :)

**Comment by jakearchibald** [comment]
lol yeah my bad. It should resolve with `preloadResponseObject`.
