### ISSUE TITLE
service worker source file is requesting from the server every time any navigation occurs in the page/ an frame is embedded in the page

### ISSUE THREAD

**Issue by sonochacko** [w3c/ServiceWorker#1351]
Is there any possibility to cache service worker file for at least 24 hours? I have tried providing cache-control: public, max-age=1440. but it's not working. 

Also, If a page contains an iframe and if you reload that iframe alone, sw.js(service worker script) is getting downloaded from the server. 

Any idea why this is happening? How to avoid this?

**Comment by jakearchibald** [comment]
All the answers are in https://developers.google.com/web/updates/2018/06/fresher-sw 😀

**Comment by sonochacko** [comment]
Thanks
