### ISSUE TITLE
What is the name for `installing`, `waiting` and `active`?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [w3c/ServiceWorker#1362]
`installing`, `installed`, `activating`, `activated` and `redundant` are **state**s of service worker.

What is the (official) name for `installing`, `waiting` and `active` of service worker?

**Comment by jakearchibald** [comment]
What's wrong with installing / waiting / active?

**Comment by FluorescentHallucinogen** [comment]
I'm writing an article. There is a name for `installing` / `installed` / `activating` / `activated` / `redundant`. This name is a _state_.

But what is the name for `installing` / `waiting` / `active`? I can't find it in the spec. If I'll use the same (_state_) term for them, it may confuse readers. These are different things. I need another official term for `installing` / `waiting` / `active`, different from _state_.

**Comment by jakearchibald** [comment]
Ohh I get it now. I'd go for "slot" or "position".

**Comment by jakearchibald** [comment]
"state" is usually inside a thing, so `reg.active` isn't the state of a service worker, it's where the worker is in the registration.

It could be referred to as the state of the registration, but go for whatever you think readers would understand best.
