### ISSUE TITLE
Why does spec set redirect's mode to error ?

### ISSUE THREAD

**Issue by TomPradat** [w3c/ServiceWorker#1366]
I don't really understand why we have this in the spec.

This causes trouble when redirection websites to new urls.
If you want to redirect some old-website to new-website, you'd think you just need to 301 redirect from old-website to new-website. The problem is that doing so the service-worker won't update and serve the cached content. The only solution found for now is to redirect everything from old-website except /service-worker.js that serves a custom service-worker that unregister the current service-worker.

Is there any other way to tackle the problem ?

**Comment by TomPradat** [comment]
Can I have someone to answer me ?

Here is the problem explained more thoroughly  => https://stackoverflow.com/questions/53539111/service-worker-breaks-the-internet

**Comment by jakearchibald** [comment]
History here: https://github.com/w3c/ServiceWorker/issues/618#issuecomment-74052612
