### ISSUE TITLE
Update shouldn't fail due to MIME check or 404 for the incumbent's worker scripts

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1374]
The update check spiders the script resource map of the incumbent worker scripts, but then fails immediately if one script has a non-OK status or fails the MIME check. This means if the incumbent worker is using import-script.js which now 404s, and the updated worker doesn't use import-script.js, the update will fail.

Instead these checks shouldn't fail the whole update, since it's not known whether the new worker will use them.

> For each url → storedResponse of newestWorker’s script resource map:
> ...
> 7. Extract a MIME type from the fetchedResponse’s header list. If this MIME type (ignoring parameters) is not a JavaScript MIME type, asynchronously complete these steps with a network error.
> 8. If fetchedResponse’s type is "error", or fetchedResponse’s status is not an ok status, asynchronously complete these steps with a network error.

**Comment by mattto** [comment]
Proposal: When spidering |newestWorker|'s script resource map, always write the response into |updatedResourceMap|. On MIME failure, network error, or byte-for-byte body diff, set |hasUpdatedResources| to true. This ensures the diff translates into starting the installing worker, which is correct since the worker scripts are different. When the installing worker does importScripts() a MIME failure or network failure will throw SecurityError/NetworkError so in effect the installation will usually fail. We also need to remove unused resources from the installing worker's map that ended up not being used, or these will be used in the next update check against this new worker. So augment the script resource map with a flag about whether the script was loaded. After installation finishes, drop unused scripts from the map.

**Comment by mattto** [comment]
Ah I think I found Chrome's (in-progress) implementation is doing the ""no change" and continue on to the next script" already: https://cs.chromium.org/chromium/src/content/browser/service_worker/service_worker_single_script_update_checker.cc?rcl=e2f59f49da06e49c476bd0d32913d7349d61a0d4&l=175

**Comment by makotoshimazu** [comment]
Yeah, it's implemented as no change tentatively. [this](https://cs.chromium.org/chromium/src/content/browser/service_worker/service_worker_single_script_update_checker.cc?l=176) is the latest code, which treats network error differently from 200 and identical case, but it behaves similarly for now.
Treating network error on comparison as "no change" sounds reasonable to me too.

**Comment by tingshao** [comment]
I'm watching this issue for some time, I just updated chrome's code for byte to byte check several days ago. If a network error is found for a script, the failure result is recorded but it's not treated as "Changed". This error result may be useful in future to distinguish it from a real not changed script if we want to do more work on it. 
Currently, only an explicit content change leads to "Changed". Treat the error as "no change" also sounds reasonable to me.

**Comment by wanderview** [comment]
> One gentle change (which may be in-line with Firefox's implementation) is to consider failures to be "no change" but continue the update check.

I believe this is consistent with the firefox implementation.

**Comment by mattto** [comment]
Fixed by #1377
