### ISSUE TITLE
Hiding add to homescreen minibar for certain urls.

### ISSUE THREAD

**Issue by pnkapadia6** [w3c/ServiceWorker#1375]
I have the service worker integrated on my website. For a particular route, I do not wish the Add to Homescreen minibar to appear at the bottom of the page. Is it possible to get that configuration done?

**Comment by Malvoz** [comment]
Although some browsers _may_ require a serviceworker for the "Add to homescreen"-interface to show, it is part of the [Web App Manifest](https://www.w3.org/TR/appmanifest/). What you want to do is [listen to the `BeforeInstallPromptEvent`](https://developers.google.com/web/fundamentals/app-install-banners/#listen_for_beforeinstallprompt), the spec says:

> If the `BeforeInstallPromptEvent` is not cancelled, the user agent is allowed to present an automated install prompt to the end-user.

**Comment by pnkapadia6** [comment]
@Malvoz Yes, it's about the mini-info bar and is not controlled by BeforeInstallPromptEvent. Currently I've not registered the service worker if the landing page is the route I want. Is there a better way?

**Comment by Malvoz** [comment]
@pnkapadia6 

This Chrome behavior is out of scope and does not apply to the serviceworker specification. You could however, send feedback to Chrome instead.

**Comment by Malvoz** [comment]
https://developers.google.com/web/updates/2019/05/mini-infobar-update

> Starting in Chrome 76, you can prevent the mini-infobar by calling `preventDefault()` on the `beforeinstallprompt` event.

**Comment by jakearchibald** [comment]
This is chrome-specific behaviour. Can you file it at crbug.com?
