### ISSUE TITLE
The compatibility of service worker on ios devices

### ISSUE THREAD

**Issue by Lozoe** [w3c/ServiceWorker#1381]
This is a question about the compatibility of service worker on ios devices. After testing, safari has good support for service worker after ios 11.3 version,but the Chrome on the same device is not supported.However, webview of the client uses webkit kernel directly,so it can't use this new feature of Progressive Web App.Is there a further solution to this problem?

**Comment by jakearchibald** [comment]
Chrome on iOS can only use the browser view that iOS gives it ☹️
