### ISSUE TITLE
Cache.put() does not read response's body

### ISSUE THREAD

**Issue by ytausky** [w3c/ServiceWorker#1383]
A response's body is never explicitly read, so it's unclear what would be stored in the cache for a response with an arbitrary `ReadableStream`.

**Comment by jakearchibald** [comment]
I used the background fetch spec as a place to try a more explicit way of doing this.

https://wicg.github.io/background-fetch/#background-fetch-manager-fetch - step 8.8.

My plan is to extract the cache spec from the service worker spec, and refactor it in terms of what I did for the fetch spec. I'd also like to be more explicit about which fields of the request/response are stored.
