### ISSUE TITLE
Can respondWith() be called from a microtask?

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1394]
Should this respondWith() throw?
```
self.addEventListener('fetch', e => {
  Promise.resolve().then(() => {
    e.respondWith(new Response('respondWith succeeded'));
  });
```

Firefox and Chrome have different behavior here. Demo site at
https://respond-with-microtask.glitch.me/
(Chrome Canary throws an exception and then crashes, sorry, just ignore the crash for now.)

In Chrome we tried hard to make it so respondWith()/waitUntil() can't be called like this, now I'm wondering whether the spec allows it after all.

The respondWith() spec steps check whether the dispatch flag is set: https://dom.spec.whatwg.org/#dispatch-flag 

It's not clear to me if the dispatch flag gets unset before microtasks are run at the end of the event handler.

**Comment by mattto** [comment]
OK wow I think this is exactly https://github.com/w3c/ServiceWorker/issues/1213 actually. I'll re-read that tomorrow.

**Comment by wanderview** [comment]
I think the spec says it should be allowed in the microtask.  The microtask checkpoint is in "Cleanup After Running Scripts" here:

https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script

This is called from step 16.2 here:

https://heycam.github.io/webidl/#call-a-user-objects-operation

Which in turn is called from the DOM spec's "Inner Invoke" to call event targets:

https://dom.spec.whatwg.org/#concept-event-listener-inner-invoke

**Comment by mattto** [comment]
Thanks @wanderview! I'll see if the WPT tests need updating. Chrome is the only 11/11 on https://wpt.fyi/results/service-workers/service-worker/extendable-event-async-waituntil.https.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned which is suspicious since it's probably not following the spec here.

**Comment by wanderview** [comment]
The waitUntil tests may be different than the respondWith() issue.  I believe a lot of that test is trying to verify when you are allowed to append promises to the waiting promise list, etc.  That is probably more nuanced than the dispatch flag being unset.  Its likely we just don't have a WPT test for respondWith() from an immediate microtask.

**Comment by mattto** [comment]
Thanks, yes we in fact don't have a respondWith() from an immediate microtask. Let me close this issue and we can follow up on #1213 for the more complex cases.
