### ISSUE TITLE
Browsers should not consume the stream right away on ReadableStream responses with 'Content-Disposition: attachment' header.

### ISSUE THREAD

**Issue by Khivar** [w3c/ServiceWorker#1398]
When providing the `FetchEvent.respondWith()` method with a Response object that has the `Content-Disposition` header set to `attachment` and a `ReadableStream` as its body, then if the browser is not set to automatic download mode and prompt the user with a window asking where to download the file or cancel the download, the stream should only be consumed if and when the user accepts the download.

Currently on both Firefox and Chrome, the browser starts consuming the stream as soon as the response is sent by the service worker. Meaning that while the window asking where to download the file / cancel the download is on the user's screen, the stream is pulling data non-stop and, it seems, storing it into memory.

I understand the need to fetch data immediately on inline content, however when the content is meant to be downloaded (`Content-Disposition: attachment`) then it makes no sense and can be dangerous to consume the stream right away if the browser is not set to automatic download mode. First because that means starting downloading data before having the user consent. Additionally, let's say this is a 10GB download, this means that without any transformation on the stream, the browser will potentially load 10GB in memory, which, apart for being an insane amount, can have unwanted side effects and will surely will crash the tab.

**Comment by makotoshimazu** [comment]
I think it depends on how the browser implements download. As far as I quickly scanned the code around download, Chromium reads the contents into a temporary file during the confirmation dialog. It seems working as intended.

**Comment by mattto** [comment]
I think this started as https://crbug.com/945600. I agree it's better to track as an implementation bug as I don't think spec text is necessary here.
