### ISSUE TITLE
No credentials prompt with basic auth (401)

### ISSUE THREAD

**Issue by joker-777** [w3c/ServiceWorker#1400]
Hello,

I'm not sure where to post this error but I hope you guys can help me out. I know there are already [quite a few tickets which seem to be related](https://github.com/w3c/ServiceWorker/issues?utf8=%E2%9C%93&q=is%3Aissue+401) but after reading all of them, none of them gave me a solution which worked. I'm using right now the latest Chrome version 73.0.3683.103 with Linux.

I can reproduce this error very reliable on our staging server which is basic auth potected. The first time accessing https://staging.kenhub.com it prompts me correctly for the basic auth credentials.

![Screenshot_20190410_185421](https://user-images.githubusercontent.com/378859/55921389-24c23080-5bc2-11e9-97e0-eac34186f6b1.jpeg)

But when I then insert `chrome://restart` in the address bar, it clears the basic auth cache and the next time I access https://staging.kenhub.com, it doesn't show me the basic auth prompt any more.

![Screenshot_20190410_190006](https://user-images.githubusercontent.com/378859/55921544-e4af7d80-5bc2-11e9-9be6-35b9b4b70dca.jpeg)

The only way to fix this is to unregister the current service worker.

![Screenshot_20190410_190120](https://user-images.githubusercontent.com/378859/55921654-525ba980-5bc3-11e9-8071-1ce2219a2171.jpeg)

**Comment by mattto** [comment]
This is a known issue in Chrome: https://crbug.com/623464.

The spec has this right, Chrome just needs to implement the spec.

**Comment by joker-777** [comment]
Thanks for sharing this link. Good to know that this problem isn't because of our servicemworker implementation.
