### ISSUE TITLE
Tracking JS issue in firefox pwa

### ISSUE THREAD

**Issue by marmikdesai** [w3c/ServiceWorker#1401]
Hi,

While implementing PWA on our mobile site, We noticed that GA tracking pixels and other third party tracking JS opening automatically in new tabs in FIREFOX. Attached a GIF of the same. Please help us resolve this issue.

![pepperfry pwa](https://user-images.githubusercontent.com/4994566/56113463-93650c80-5f7b-11e9-9b66-da7327e2c07c.gif)

**Comment by mattto** [comment]
This seems like a specific issue about your site or possibly the Firefox browser. I don't think this is an issue about the service worker specification.
