### ISSUE TITLE
Casing convention for acronyms vs abbrev. (ie `clientId`)

### ISSUE THREAD

**Issue by SMotaal** [w3c/ServiceWorker#1402]
I can't help feeling that casing for the abbreviation "id." in this spec is somewhat clashing with the capitalization in other specs (which notebly mostly deal with acronyms).

Can you clarify how this particular case was determined? Is there a formal SOP or historical norms that signify a difference between abbreviations versus acronyms when camelCasing is used in specs?

**Comment by mkruisselbrink** [comment]
https://w3ctag.github.io/design-principles/#casing-rules specially addresses this case I believe

**Comment by SMotaal** [comment]
@mkruisselbrink Thanks for point me to that reference — It is exactly what was needed here 👍
