### ISSUE TITLE
Discuss the maxScopeString and Service-Worker-Allowed in security considerations

### ISSUE THREAD

**Issue by jyasskin** [w3c/ServiceWorker#1405]
[`Service-Worker-Allowed`](https://w3c.github.io/ServiceWorker/#service-worker-allowed) and the [*maxScopeString* in Update](https://w3c.github.io/ServiceWorker/#update-algorithm) exist to protect sites that allow different users to operate within different paths but don't want those users to overwrite each other's content. This could use some discussion in the [Security Considerations](https://w3c.github.io/ServiceWorker/#security-considerations) since it's not particularly obvious that there is this protection or what its limits are.

**Comment by mattto** [comment]
Thanks, added in #1409.
