### ISSUE TITLE
New 'update via cache' value doesn't take effect in register algorithm.

### ISSUE THREAD

**Issue by tingshao** [w3c/ServiceWorker#1406]
In register algorithm step 5.3, if job's script url equals newestWorker's script url but the 'update via cache' is different. Then it runs to step 7 to do the Update. However, in Update algorithm, it uses the 'update via cache' value from existing registration instead of the job's 'update via cache' value. It seems that job's new value will not be used and lost. I think the Update algorithm should be called with using the job's new 'update via cache' value.

**Comment by makotoshimazu** [comment]
I found Issue #1189 which covers this.
The parameter should be updated dynamically but we still need to update the spec.
Matt added the WPT for this:
https://github.com/web-platform-tests/wpt/blob/master/service-workers/service-worker/registration-updateviacache.https.html

**Comment by tingshao** [comment]
Thanks for note this, then I will close this issue.
