### ISSUE TITLE
Should register() trigger byte-for-byte checking when WorkerType is updated?

### ISSUE THREAD

**Issue by makotoshimazu** [w3c/ServiceWorker#1408]
```js
// (1) Register sw.js as classic script.
await navigator.serviceWorker.register('sw.js', {type: 'classic'});
// (2) Register sw.js as module script with the same script.
await navigator.serviceWorker.register('sw.js', {type: 'module'});
```
Should (2) install a new ServiceWorker and invoke install/activate event?

**Comment by mattto** [comment]
I think I'd expect a new service worker to be installed and the byte-to-byte check skipped as if the URL changed.

See also https://github.com/w3c/ServiceWorker/issues/1359.

**Comment by makotoshimazu** [comment]
Thanks!
The current spec seems to have another edge case where install/activate events are not triggered as follows, and it also can be solved by adding a "skip byte-to-byte checking" flag.

```js
// ==== script in something.html ====
// Register a.js, and it imports b.js too.
await navigator.serviceWorker.register('a.js');
// Register b.js, but b.js is identical to the one we previously put into the script cache map.
await navigator.serviceWorker.register('b.js');

// ==== a.js ====
a = true;
if (typeof b === 'undefined') {
  importScripts('b.js');
}

// ==== b.js ====
b = true;
if (typeof a === 'undefined') {
  importScripts('a.js');
}
```

For example, does changing [[Register]] like this and refers to the flag in the [[Update]] algorithm make sense?

5. If registration is not null, then:
    ....
    4. If newestWorker is not null, job's script url doesn't equal to newestWorker's script url or job's worker type doesn't equal to newestWorker's worker type, then:
        1. Set job's skip byte-for-byte comparison to true.

**Comment by mattto** [comment]
Addressed in https://github.com/w3c/ServiceWorker/pull/1411
