### ISSUE TITLE
Export "clear registration"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ServiceWorker#1410]
The Push API tries to call into "Clear Registration", but that algorithm has "no-export" defined  on it so that cross reference in the Push API breaks. 

Is that algorithm private design or could it be exported? (maybe same with "Try Clear Registration"... seem try might be a safer export?)

**Comment by jakearchibald** [comment]
Can you give a bit more detail around what you're looking to use this for?

**Comment by marcoscaceres** [comment]
This is the conformance requirement:

> A push subscription is deactivated when its associated service worker registration is unregistered, though a push subscription MAY be deactivated earlier. A push subscription is removed when the **clear registration** algorithm is run for the service worker registration.

https://w3c.github.io/push-api/#subscription-deactivation

**Comment by marcoscaceres** [comment]
McPingittypingping (always wanted to say that)

**Comment by jakearchibald** [comment]
Are there steps you need to run if the service worker is unregistered? If so, I'll add a hook in for that.

When a service worker is unregistered, it remains in use by existing pages (not new ones). At what point do you want to deactivate the push subscription? Once the service worker is unregistered, or once all remaining pages using it go away, and the registration becomes completely redundant?

If there aren't any steps you need to run, then it should be taken care of automatically. If you push subscription is a child of the service worker registration, then when the registration can no longer be referenced, neither can the push subscription.

**Comment by jakearchibald** [comment]
McPingittypingping 😄

**Comment by marcoscaceres** [comment]
Heh, went on vacation. Back next week. I’ll need to ping the editors to confirm nothing special needs to happen, but if it’s all taken care of automatically on unregister... that’s awesome.

**Comment by marcoscaceres** [comment]
Closing this, as nothing special needs to happen. I'll change the Push spec so that part of the spec is a note.
