### ISSUE TITLE
Object equality of service worker registrations

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1420]
The spec says these are [NewObject], but the tests and implementation (in Chrome at least) seem to suggest that the same registration is returned in a given realm if it represents the same underlying registration.

@mattto is this correct? Are there cases where we'd create two registration objects for the same registration?

Using a single object makes sense. If it's what browsers and the tests are doing, we should update the spec.

**Comment by wanderview** [comment]
Doesn't the `[NewObject]` apply to the promise, not the registration itself?

**Comment by jakearchibald** [comment]
ugh i feel stupid.

I wish the spec was clearer about object reuse, but yes, you are right.
