### ISSUE TITLE
oncurrentchange in test

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1421]
https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/service-workers/service-worker/registration-end-to-end.https.html#L20

Is this a typo, or is it something we had at some point?

cc @mattto

**Comment by mattto** [comment]
Haha, that's awesome. I vaguely remember there was navigator.serviceWorker.current before. This was part of the initial commit of this test: https://codereview.chromium.org/238993003

There were also tests about .current added here: https://codereview.chromium.org/265943003

Safe to remove :)

**Comment by jakearchibald** [comment]
Hah! Nice bit of history there. I'll remove it.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/web-platform-tests/wpt/pull/17206
