### ISSUE TITLE
maxScopeString definition is missing the trailing '/'

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1423]
The spec has:

> Set maxScopeString to "/" concatenated with the strings, except the last string that denotes the script’s file name, in job’s script url's path (including empty strings), separated from each other by "/".

This seems to omit the trailing "/". Therefore a service worker in /foo/bar/sw.js gets maxScopeString of /foo/bar instead of the intended /foo/bar/.

**Comment by jakearchibald** [comment]
Agreed. "/" should be added to the end.
