### ISSUE TITLE
Broken links to v1

### ISSUE THREAD

**Issue by mattto** [w3c/ServiceWorker#1431]
https://w3c.github.io/ServiceWorker/v1/ is a 404 so these links are broken.

In Nightly:
> [Service Workers 1](https://w3c.github.io/ServiceWorker/v1/) is a version that is advancing toward a W3C Recommendation.

At https://www.w3.org/TR/service-workers/:
> Editor's Draft: https://w3c.github.io/ServiceWorker/v1/

cc @jungkees

**Comment by jakearchibald** [comment]
Hmm maybe I broke this when I "fixed" the build script. I'll take a look.

**Comment by jungkees** [comment]
We have manually compiled and deployed v1 html before so it seems we should add the following at the end of compile.sh:
```
cd v1 && curlbikeshed "index.html"
```

I tried to do that but failed to push presumably due to permission error. Can you try it?

**Comment by jakearchibald** [comment]
Fixed in https://github.com/w3c/ServiceWorker/commit/c04359b2c8629311fe5d6d067a0405d7ecbd2123. Sorry, my bad.
