### ISSUE TITLE
content-type in csp report on fetch is missed

### ISSUE THREAD

**Issue by maxkuzmin** [w3c/ServiceWorker#1449]
When csp report is initiated by browser and fetched by service worker, content-type header of request is missing for some reason. I created a [demo page](https://billowy-study.glitch.me/).
Being on loaded page, please open network, filter request by "report" substring and reload the page. You will see 4 requests:

- report1 xhr
- report csp
- report1 fetch
- report fetch

`report1` is called manually from javascript (`new XMLHttpRequest()`...), `report` - by browser because of csp rule violation.
Both `report1 xhr` and `report csp` calls have "Content-Type: application/csp-report" provisional request header. However, only `report1 fetch` has such header, `report1 fetch` lacks the Content-Type header.

Tested in latest Chrome and Firefox.

**Comment by jakearchibald** [comment]
This sounds like a browser bug. Can you file it in the browser trackers?

**Comment by bathos** [comment]
Although this is not a SW-spec issue, very grateful that Google turned up confirmation that I’m not just losing my mind.
