### ISSUE TITLE
Clarify "waiting for all" in Install

### ISSUE THREAD

**Issue by Ms2ger** [w3c/ServiceWorker#1461]
> Wait until e is not active.
> If e’s timed out flag is set, or the result of waiting for all of e’s extend lifetime promises rejected, set installFailed to true.

"waiting for all" (or "get a promise for waiting for all"; #1363) doesn't return a result synchronously, so we can't just check if it rejected. Is this supposed to wait until the promise settles?

**Comment by mattto** [comment]
Yes it's trying to wait for all the promises to settle.
