### ISSUE TITLE
Inaccurate Abstract

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#1493]
"This specification describes a method that enables applications to take advantage of persistent background processing, including hooks to enable bootstrapping of web applications while offline."

It mentions "background" a few more times, but I think in practice they're not so much for background processing as this might make it seem.

I think it'd be better to describe it as being able to handle specific type of events in parallel to the main application, including potentially when the main application is not running. And that last bit only has some agreement for push thus far in practice, which is still visible to the user in some manner as I understand it.

**Comment by jungkees** [comment]
If I understood correctly, your point is that Service Worker is not for long running background tasks in general. Agree on that point. How about along the lines of this:

> This specification describes a method that enables applications to take advantage of event-driven processing off the main thread, which includes enabling bootstrapping of web applications while offline. The core of this system is an event-driven Web Worker, which responds to extensible events dispatched from documents and other sources.
> 
> Service Worker is a generic entry point for [extensible event](https://w3c.github.io/ServiceWorker/#extendableevent) processing in the Web Platform.
> 
> This specification also provides a request and response store similar in design to the HTTP cache, which makes it easier to build offline-enabled web applications.

**Comment by annevk** [comment]
Something like that seems fine. I'd not link from the abstract though.
