### ISSUE TITLE
What happens with event.respondWith(Promise.reject(err))?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#150]
``` js
this.onfetch(function(event) {
  // this:
  event.respondWith(Promise.reject(Error("Nope!")));
  // or this:
  event.respondWith(caches.match(event.request.url));
  // …where that url is not in the cache
})
```

My understanding was:
- If you call `respondWith`, you're taking charge of the response
- If the promise rejects with a response, that response is used (it may be a 404, 500 etc)
- If the promise rejects with something else, the browser gets a network failure, and may choose to display the rejection error & stack trace

This means it's down to you to catch rejections and recover in the way you want.

However, from https://github.com/slightlyoff/ServiceWorker/blob/master/explainer.md

> If the Promise generated by match() returns anything else or resolves as an error, the request is then routed to the browser's HTTP stack (as would happen without the ServiceWorker).

I think this is a bit… magic.

Eg:

``` js
event.respondWith(fetch(event.request.url));
```

If the above fetch fails (which could be off-domain redirect, offline, maybe even 404 - it's not specced yet) the promise rejects & the browser goes to the network stack, essentially making the request again.

Also, an offline-first page would typically make two requests per API call. One to the cache, another to the network. This is allows the page to display cached data first then update as the network request arrives. If rejections go to the network, I'm going to have to catch the cache miss and resolve with an empty response, else get a double request.

**Comment by jcubic** [comment]
Any way to hide the stack trace when fetch in onfetch fail?

[How to hide stack trace from service worker fetch?](https://stackoverflow.com/q/70477047/387194)

It seems that the current behavior in Chrome is to throw uncatch exception when fetch in Service Worker fail.
