### ISSUE TITLE
Service worker spec meetup

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1501]
At TPAC we suggested meeting up again between TPACs. Let's try to figure out a date.

BlinkOn is in London on April 7-8, so I figured some folks would already be in town. Are there dates around there that work?

https://doodle.com/poll/8dugy78e577rbdk8 - let me know.

If we can't make it work, I'll find some more dates. Also, let me know if there's anything I should consider when looking at the next set of dates.

cc @jungkees @aliams @slightlyoff @wanderview @mattto @asakusuma @n8schloss @annevk @asutherland @youennf @cdumez (please tag anyone I've forgotten)

**Comment by xtuc** [comment]
Is the meetup open to anyone?

**Comment by wanderview** [comment]
Will this work for folks preparing for the upcoming IO conference a month later?

I believe I'll be in town for BlinkOn.  Meeting after BlinkOn would work for me.

Note I think at least some of us also discussed doing an adjacent day around storage topics like quota, IDB, etc.

**Comment by mkruisselbrink** [comment]
+1 for the adjacent day around storage topics. After BlinkOn would push this really close to easter and family obligations around that though, so my preference would be before BlinkOn...

**Comment by n8schloss** [comment]
Unfortunately I won't be able to attend BlinkOn this year given how close it is to passover. I'd probably be unable to attend in person or even call in if it's the same week as BlinkOn.

**Comment by wanderview** [comment]
Week before could possibly work for me.  I have a summit on Monday before BlinkOn, though.

**Comment by mattto** [comment]
The week before BlinkOn likely works for me too. I probably can't make BlinkOn itself this year.

**Comment by jungkees** [comment]
Regrettably, I'm not sure at this point if I can attend the meeting in person. So, I'd abstain in the scheduling vote. I'll try to call in the afternoon sessions if I'm not be able to be there.

Adding @SteveBeckerMSFT.

**Comment by jungkees** [comment]
@xtuc, thanks for your interest. It's a Working Group meeting, so I'll take it offline with you, @jakearchibald, and @ylafon.

**Comment by wanderview** [comment]
Another factor for me is I was hoping to have a good deal of work done on my scopes pattern matching prototype and spec proposal so we could discuss at the meeting.  I had been expecting a meeting at end of May or early June.  I'm not sure how far I will get by early April.

**Comment by n8schloss** [comment]
Just wanted to flag that apparently there's a web perf wg meeting on 4/2 and 4/3, so that will probably conflict with the week before, and given that FB is hoping to host at least part of that meeting I'll probably need to be there instead.

So meeting in May or early June sounds like it would be better for me too :)

**Comment by wanderview** [comment]
BlinkOn confirmations have gone out, so it would be good to resolve this so those of us going to that conf can book travel.

**Comment by jakearchibald** [comment]
It doesn't seem like enough folks can make it around BlinkOn. I'll try to find some other dates later in the year, probably June. I'll open a new issue for that.

**Comment by asutherland** [comment]
I think we're quite happy to host at the Mozilla Berlin office if there's interest.  The office is conveniently located by a hotel that plays the Big Lebowski 24/7!

**Comment by jakearchibald** [comment]
I'm holding off on this until I see what other events do in terms of coronavirus.
