### ISSUE TITLE
safari fetches from memory cache instead of Service worker

### ISSUE THREAD

**Issue by novaknole** [w3c/ServiceWorker#1510]
Question 1 is asked so that Question 2 strange behaviour might be explained or something. 

**Question 1)** Let's say browser requests a `index.js` file . There are different steps involved where this file should be brought from.  So , let's take a look at scenario where browser first goes to check if the file is present there and if not, where it goes next.
 * Memory Cache -> Service Worker -> Disk Cache -> Network

 This is the sequence I think is most valid. Do you agree?

**Question 2)** Now, I found out the following about Safari on MacOS.

I went to the page for the first time, service worker's install event gets called and things get precached from there (I checked and they are precached). Now, I refreshed the page and looking at network tab, requests all get returned from `Service Worker` in transfer column. Now, I refresh Again and it looks like some of those files,  I'd say 80% gets returned from memory cache (that's what network's `transfer size` column says in safari. I am wondering why they get returned from `memory cache` after 2 refreshes? It seems like that now, I get an assumption that i can't full control some requests via service worker.  First, I was thinking maybe `safari` browser's `transfer` column size shows wrong information, but I tried to test it like this: 

I registered `fetch` listener and put `console.log(e.request.url)` there. After I refresh my website 2 times where `transfer` column shows that items get returned from `memory cache`, it seems like `fetch` listener doesn't get called for those urls that get brought from `memory` which makes my point that some of the urls don't get controlled after 2 refreshes and they keep coming back from memory cache. On chrome, this behaviour doesn't happen.  What could be the case?

**Comment by jakearchibald** [comment]
I replied to this at https://github.com/jakearchibald/idb/issues/171.

**Comment by np300** [comment]
> ผมตอบนี้ที่jakearchibald[ / IDB # 171](https://github.com/jakearchibald/idb/issues/171)

**Comment by wanderview** [comment]
There is some previous discussion in #962.

**Comment by novaknole** [comment]
@wanderview  I read those, but still, there's some vague statements. Have you found out the final answers? I will quickly ask my question in a simple way.

1) Which cache is the first one that browser goes to? I think It's memory cache overally.  Agree? but if i use service worker and if browser goes first to memory cache, it proves that my service worker is not in full control of my assets and that's a bad thing. It should be in control. What do you think?

2) I read this on that another discussion:
`So we do actually re-use our image cache across documents, but we explicitly disable that when service workers are in play.` 

I believe there're some kind of memory caches for js/css files too. But what you're saying is if service worker is in play, files don't get fetched from memory cache right?

3) In safari, this is all strange, because `first refresh` gives you assets from service worker and second refresh and all subsequent requests give you from memory cache. So, it's interesting why this is the behaviour. Using service worker should mean that it's in full control of assets , but somehow memory cache makes it all weird. What would you say?

**Comment by wanderview** [comment]
The memory cache in chromium (and I believe webkit) sits above service workers.  So if you hit the memory cache then the service worker FetchEvent is not triggered (because no network request is ever initiated).  All non standard.
