### ISSUE TITLE
register() lacks same origin check

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#1518]
Am I missing something or does `register()` not perform a same origin check anywhere?

**Comment by mozfreddyb** [comment]
The ["Start Register" algorithm](https://w3c.github.io/ServiceWorker/#start-register) has some checks in step 3 and 4:
- step 3 checks that scheme is http or https
- step 4 checks that the scriptURL's path doesn't contain "%2F" or "%5C".

The only invokation of Start Register is in [ServiceWorkerContainer.register()](https://w3c.github.io/ServiceWorker/#navigator-service-worker-register), which does not apply any checks, just parsing in step 3.


P.S.: This issue filed was based on a question I had directed at @annevk based on [folks requesting subresource integrity support for ServiceWorkers](https://github.com/w3c/webappsec-subresource-integrity/issues/66) - which is providing most of its on cross-origin resources only.

**Comment by mkruisselbrink** [comment]
Start Register schedules a "Register" job, which ends up invoking https://w3c.github.io/ServiceWorker/#register-algorithm, which does do same origin checks in step 2 and 3 (the "referrer" is set to "client's creation URL" in the register() method.

This definitely could be cleaned up more to make it clearer. I remember there was a good reason for making this this complicated back when I spec'ed header-based installation, but that was a bad idea anyway. So probably it could be done much more straight forward.

**Comment by annevk** [comment]
Thanks, though note that it does not actually do a same origin check. It checks if _A_ is _B_, not if _A_ is same origin with _B_. Those are different checks.

**Comment by annevk** [comment]
What happens in case of a cross-origin redirect?

**Comment by wanderview** [comment]
Per step 5 of "perform the fetch" here:

https://w3c.github.io/ServiceWorker/#update-algorithm

The the request.redirect mode is set to "error".

**Comment by annevk** [comment]
I see, but it's weird that "perform the fetch" isn't passed to the algorithm (or is an official optional parameter). @domenic that might be worth cleaning up.

**Comment by mfalken** [comment]
I moved this to https://github.com/whatwg/html/issues/6339.

**Comment by mfalken** [comment]
I missed the comment here: https://github.com/w3c/ServiceWorker/issues/1518#issuecomment-644232051

**Comment by mfalken** [comment]
Fixed in #1568
