### ISSUE TITLE
why service-worker.js can not be automatically detected

### ISSUE THREAD

**Issue by UNDERCOVERj** [w3c/ServiceWorker#1521]
I serve the service-worker.js on my server, when I have some changes in my .tsx，and then update the service-worker.js on my server, but the web browser can not immediately detect the update。Only if I manually refresh my browser, the browser can detect the update, and then trigger the onupdatefound event。

**Comment by jakearchibald** [comment]
Check out https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle
