### ISSUE TITLE
Open(cacheName) resolvse with null value, though cacheName matches key

### ISSUE THREAD

**Issue by ATerentjev** [w3c/ServiceWorker#1524]
I apologize if the question is incorrect, I am new in javascript.
The [mapbox ](https://github.com/mapbox/mapbox-gl-js/issues/9145) uses the following code

`// We're using a global shared cache object. Normally, requesting ad-hoc Cache objects is fine, but
// Safari has a memory leak in which it fails to release memory when requesting keys() from a Cache
// object. See https://bugs.webkit.org/show_bug.cgi?id=203991 for more information.
var sharedCache                 ;

function cacheOpen() {

	//debugger;
    if (window$1.caches && !sharedCache) {
        sharedCache = window$1.caches.open(CACHE_NAME);
    }
function enforceCacheSizeLimit(limit        ) {
    cacheOpen();
    if (!sharedCache) { return; }
 
    sharedCache
        .then(function (cache) {
            //
            if(!cache){
                debugger;
                return;
            }
            cache.keys().then(function (keys) {
                //debugger;
                for (var i = 0; i < keys.length - limit; i++) {
                    cache.delete(keys[i]);
                }
            });
        });
}
 `
I insert the line 
` if (!cache) return; `
to fix my problem, but I would like to understand why this is happening.
Here `https://w3c.github.io/ServiceWorker/#cachestorage` I read 
`If cacheName matches key, then:
Resolve promise with a new Cache object that represents value.
Abort these steps.`
As !sharedCache = false, then I expect that promise wil resolve with new Cache, not undefined.
Can anyone explain to me what I'm wrong about?

**Comment by wanderview** [comment]
This probably belongs on a browser bug tracker and not the spec.  Which browsers does this problem trigger in?

**Comment by ATerentjev** [comment]
Google Chrome Version 84.0.4147.89

**Comment by ATerentjev** [comment]
Sorry, the problem arises when the program is launched in iis express in VS 2019

**Comment by wanderview** [comment]
Probably more appropriate to file a bug at:

https://bugs.chromium.org/p/chromium/issues/entry

However, as the chromium cache_storage owner I can tell you this is unlikely to be addressed if it only happens when debugging under visual studio.

**Comment by ATerentjev** [comment]
Thank you for the advice, I still tried to ask a question   [,https://bugs.chromium.org/p/chromium/issues/detail?id=1110313](https://bugs.chromium.org/p/chromium/issues/detail?id=1110313). It  is very necessary for debugging programs in VS

**Comment by wanderview** [comment]
Closing in favor of crbug.
