### ISSUE TITLE
Virtual Call: pattern matching scopes

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1535]
All, I'd like to do a video call to discuss my latest proposal for service worker pattern matching scopes:

https://github.com/w3c/ServiceWorker/issues/1468#issuecomment-689198638

One major change is that URLPattern syntax is proposed to align with path-to-regexp.

I'd also like to discuss the service worker registration id issue as well since its related:

https://github.com/w3c/ServiceWorker/issues/1512

We could do this during the TPAC week (Oct 12 - 16?) or we could just have a meeting whenever its convenient for folks.  I think the first step would be to get a sense of who is interested in attending.  I'm hoping to at least get @jakearchibald @asutherland @youennf and @annevk.  Also, FYI @blakeembrey as the author of path-to-regexp.

If you are interested in attending please post below with your timezone and any general calendar restrictions (holiday, etc).  I'll then make a doodle with some proposed timeslots for folks to vote on.

Thanks!

Date: Friday October 9, 2020
Time: 2pm UTC
Meeting Link: https://meet.google.com/wxc-hfij-pai
Minuntes: https://docs.google.com/document/d/17FBYuYSBKkYrBnCfj8FQh_gwNPZEhRAqxrjCgXcEkGA/edit?usp=sharing
Slides: https://docs.google.com/presentation/d/1RFqSfIVGiW40BWt09unVMSThBc3vMwNF7b6XFEsFXSY/edit?usp=sharing

**Comment by jakearchibald** [comment]
I'm happy to attend. I can't do the 16th. Timezone: BST.

**Comment by annevk** [comment]
Same. Timezone: Berlin.

**Comment by asakusuma** [comment]
I'm interested in attending. Timezone is PST

**Comment by youennf** [comment]
Happy to join, CET timezone. Doodle sounds good.
Seems this could be discussed during TPAC service worker virtual meeting.

**Comment by asutherland** [comment]
I would like to attend, ET Timezone, I don't have any prior restraints on the doodle.

**Comment by jakearchibald** [comment]
My preference would be to have multiple smaller focused meetings. The scheduling is going to be bad for some, so it'd be good to spread that out a bit, and avoid keeping people awake hours past bedtime.

**Comment by makotoshimazu** [comment]
Could you invite me as an optional? 
I'm in JP timezone (UTC+9). I'm fine to schedule the meeting without thinking of my timezone and I'll join it if I can.

**Comment by wanderview** [comment]
I'm going to put together the doodle tomorrow.  Just FYI in case there are folks who are interested, but not posted yet.

**Comment by wanderview** [comment]
Here is the doodle poll.  I thought we could try for the week before TPAC WG meetings to try to reduce scheduling conflicts.

https://doodle.com/poll/272trzquxk2fed8w

Please let me know if you would like me to shift it later/earlier in the day.  I tried to pick something that looked good for the timezones listed here.

**Comment by wanderview** [comment]
Based on previous posts, still looking for feedback on the doodle from:  @jakearchibald @annevk @youennf @makotoshimazu

**Comment by wanderview** [comment]
I sent out a meeting invite for Oct 9, 10am EDT.

**Comment by jakearchibald** [comment]
Works for me, sorry for not responding.

**Comment by wanderview** [comment]
No problem.  I can look at your calendar. :-)

**Comment by makotoshimazu** [comment]
Sorry for bothering you. I think I can join, thanks!

**Comment by wanderview** [comment]
No bother at all.  Sorry I missed that you hadn't responded to the doodle yet.

**Comment by wanderview** [comment]
FYI, I plan to use google meet for this video call.  The link is in the calendar invite sent to folks already and I will post it in the top comment of this issue just before the meeting tomorrow.

**Comment by wanderview** [comment]
I've updated the top comment here with the meeting link, minutes doc, and slides.

**Comment by annevk** [comment]
Thanks again for taking this on @wanderview! It seems folks interested in next steps here can read on over at

* https://github.com/WICG/proposals/issues/9
* https://github.com/w3c/ServiceWorker/issues/1468

as well as OP.

**Comment by wanderview** [comment]
Just to follow-up here I have filed the following issues based on the discussion:

* https://github.com/WICG/urlpattern/issues/14
* https://github.com/WICG/urlpattern/issues/15
* https://github.com/WICG/urlpattern/issues/18
* https://github.com/WICG/urlpattern/issues/19
* https://github.com/WICG/urlpattern/issues/20
* https://github.com/WICG/urlpattern/issues/21

Please let me know if I missed something.

Thank you everyone for participating and providing feedback.  I'll be focusing on prototyping and spec'ing the pattern primitive next.
