### ISSUE TITLE
Virtual calls around TPAC time

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#1536]
I'd like to set up some calls to cover particular topics around TPAC time. I'll take a look through the issues and propose topics, but if there's a particular issue you'd like to bring up, please let me know.

@youennf, it feels like we should chat about background fetch and try to come to a consensus there.

@annevk @wanderview @asutherland @asakusuma @mfalken @yutakahirano @youennf @jungkees anything spring to mind?

## 20-21 Oct, 2020 [14:00-16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20201020T140000&p1=tz_gmt&p2=43&p3=33&p4=248&p5=195&p6=224)
See the TPAC group meeting [schedule](https://www.w3.org/2020/10/TPAC/group-schedule.html) for your schedule management.

## Meeting notes
Meetings are done! Thank you for your participation. Sorry that we couldn't cover all the topics in the agenda. See the [meeting notes](https://docs.google.com/document/d/1qX-6w2Ixo7f0NdWv--SQbRWLtvnoKHgjyAQ0DnB6xc8/edit?ts=5f914356#).

### 20 Oct (Tue)
- **Progress updates** - A round-table of what we're up to service worker-wise, and what bandwidth/hunger we have for additional features.
  - Finding out current thinking from Mozilla and Apple on implementing navigation preload. The single most important performance win for service workers heard from devs.
- **Declarative routing**: https://github.com/w3c/ServiceWorker/issues/1373#issuecomment-451436409
- **Clear-Site-Data**: https://github.com/w3c/ServiceWorker/pull/1506
- **Background activity and privacy** - Resolving the issues @youennf posted around [background fetch](https://github.com/WICG/background-fetch/issues), which may have implications for push notifications.

### 21 Oct (Wed)
- **Cache metadata** - [Proposal](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/CacheAPIResponseMetadata/explainer.md).
- **Client lifecycle with bfcache, frozen tabs** - Revisit and close on the frozen document discussion: [Add an option to include frozen documents.](https://github.com/w3c/ServiceWorker/pull/1442), [consider how client API should behave with bfcache](https://github.com/w3c/ServiceWorker/issues/1038), [How are unloaded tabs represented?](https://github.com/w3c/ServiceWorker/issues/626)
- **Testing to exit CR and recharter**
- **Service workers on opaque origins** - Discuss VS Code's use case on [Registering Service Workers for unique origins?](https://github.com/w3c/ServiceWorker/issues/1437)
- **The timing of header setting in fetch** - Sometimes [headers are set pretty late](https://github.com/w3c/ServiceWorker/issues/1542), is this something we should/could change?

### Not covered
- **Fix worker timing** - Right now it isn't well described, [can we salvage it](https://github.com/w3c/resource-timing/issues/119#issuecomment-694627668)?
- **Determine expected parameter values in Navigation + Resource Timing APIs for responses that have been synthesized using a Service Worker**: https://github.com/w3c/navigation-timing/issues/124
- **Ye old CSS CORS issue** - https://github.com/w3c/ServiceWorker/issues/719
- **The proposal for ServiceWorkerRegistration.id** in #1512. There is a bit of contention on the issue. @wanderview would like to hear wider input to try to resolve things.
- **whether cross-origin-isolated value can be platform dependent or not** - https://github.com/w3c/ServiceWorker/pull/1545

**Comment by asakusuma** [comment]
I'd love to see progress on https://github.com/w3c/ServiceWorker/issues/1373#issuecomment-451436409

Not sure if a discussion is actually needed, or if someone just needs to execute, but we still haven't actually updated the spec to reflect the Clear-Site-Data changes that were made in Chromium:
https://github.com/w3c/ServiceWorker/pull/1506
https://github.com/w3c/ServiceWorker/pull/1440

**Comment by youennf** [comment]
> @youennf, it feels like we should chat about background fetch and try to come to a consensus there.

Yes, this might also have potential implications for push notifications as well.

**Comment by wanderview** [comment]
@jungkees Do you think MS would like to discuss this cache API proposal at all?

https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/CacheAPIResponseMetadata/explainer.md

**Comment by jungkees** [comment]
Yes, @wanderview. Thanks for bring it up. We'd love to put it on the agenda if folks are interested. In addition to the feature details in the proposal, I wish to also hear feedback around whether it'd be useful for devs. @asakusuma @n8schloss @aarongustafson

**Comment by yoavweiss** [comment]
I'd love to discuss https://github.com/w3c/ServiceWorker/issues/1542 and potential solutions, if there's still room on the agenda

**Comment by mfalken** [comment]
Some issues that come to mind:
- https://github.com/w3c/resource-timing/issues/119
- https://github.com/w3c/ServiceWorker/issues/719

**Comment by jakearchibald** [comment]
I've captured the topics in the OP. Please let me know what topics you're interested in, and what timezone you're in, and I'll get schedulin'.

**Comment by makotoshimazu** [comment]
Thanks Jake for organizing!
I'm specifically interested in updates, background activity, header's timing, and fix worker timing. I'm in JST (UTC+9).

**Comment by annevk** [comment]
All, except for declarative routing/cache metadata. CET. Thanks Jake!

**Comment by asutherland** [comment]
All. EDT. Thank you kindly.

**Comment by jungkees** [comment]
All, PDT. Thanks, @jakearchibald! Please add @erik-anderson and @SteveBeckerMSFT from MSFT to the invitee list (all PDT).

**Comment by mfalken** [comment]
I'm interested in at least updates & the two topics I proposed. I'm in JST.

**Comment by tomayac** [comment]
All, CET (CEST until Oct. 25). Thank you!

**Comment by jeffposnick** [comment]
👋  I'm specifically interested in the following, and am in EDT:

- Cache metadata
- Declarative routing
- `clear-site-data`

**Comment by makotoshimazu** [comment]
Is there a room to add one more topic regarding PerformanceResourceTiming body/transfer sizes? https://github.com/w3c/navigation-timing/issues/124

**Comment by jungkees** [comment]
Thanks @makotoshimazu. I added it to the Topics section and also added two more topics: frozen tabs and registering SW on opaque origins. I'll sync with @jakearchibald and schedule our meeting(s).

**Comment by jungkees** [comment]
I updated the OP with the proposed time and the collected agenda topics. I'm working with Jake to get this arranged as part of the TPAC plan. Please let me know if you have any comments or suggestions.

**Comment by jakearchibald** [comment]
Thanks for stepping in to organise this @jungkees!

There are some topics that might need more time, but we can identify those and organise additional calls with the folks that are interested.

**Comment by wanderview** [comment]
Sorry for the late request, but if there is time I wouldn't mind:

1. Finding out current thinking from Mozilla and Apple on implementing navigation preload.  I continue to hear from partners that this is the single most important performance win for service workers.
2. Discussing the proposal for `ServiceWorkerRegistration.id` in #1512.  There is a bit of contention on the issue and I would welcome wider input to try to resolve things.

**Comment by jungkees** [comment]
Thanks @wanderview. I updated the agenda. I think we can talk about the navigation preload as part of the progress update item. For `ServiceWorkerRegistration.id`, I put it as the last one in the 2nd day. Hope we can cover this. Otherwise, let's arrange a separate call for items later.

**Comment by makotoshimazu** [comment]
Hi, sorry about the last minute request.
If possible, can you add https://github.com/w3c/ServiceWorker/pull/1545 to the items on day 2?
This is a discussion about whether cross-origin-isolated value can be platform dependent or not because the value might largely depend on internal process allocation logic.

**Comment by wanderview** [comment]
Are we going to use this issue to schedule the 3rd meeting?

**Comment by jakearchibald** [comment]
@wanderview yes! I'll start organising that next week. Chrome Dev Summit stuff has owned all my time recently.

**Comment by mfalken** [comment]
I spoke with Jake. We are planning to hold the next meeting in November. To help decide the day, please fill in this Doodle:
https://doodle.com/poll/gn4ew5n3eni3kyik?utm_source=poll&utm_medium=link

Thanks!

**Comment by wanderview** [comment]
Could we use something other than zoom for the next meeting?  The web interface for zoom is difficult to use for large meetings and we're not allowed to install the native app on our corp devices.

**Comment by jakearchibald** [comment]
Anyone object to using Google Meet?

**Comment by annevk** [comment]
I prefer Zoom as it makes it easier to not share your personal space, but still be present.

**Comment by jakearchibald** [comment]
@annevk fwiw, you can use https://snapcamera.snapchat.com/ to apply those effects to any site, as it acts like a virtual webcam. I think your kids would love it too!

**Comment by wanderview** [comment]
You can blur your background in google meet: https://support.google.com/meet/answer/10058482?hl=en

In zoom web I can only see a single participant at a time which makes it harder to take part in the discussion.  Zoom chrome app supports more layouts, but I cannot get my microphone to work with it.  As I said above, I cannot install zoom native.

**Comment by asutherland** [comment]
> You can blur your background in google meet: https://support.google.com/meet/answer/10058482?hl=en

This doesn't seem to work in Firefox Nightly?  The page you link seems to suggest this is Chrome specific.  It does link to https://webglreport.com/?v=2 and my Firefox Nightly on a Macbook supports Web GL 2.0 and has "Major Performance Caveat: No" which suggests that's not the problem.  I also tried in Safari and the background magic didn't seem to be available there, but it appeared my Safari didn't support Web GL 2.0.

**Comment by wanderview** [comment]
Sorry for that.  Its a new feature and I was mainly skimming the doc to make sure it had been released.

**Comment by wanderview** [comment]
> This doesn't seem to work in Firefox Nightly?

Kind of off topic at this point, but in case anyone is wondering, the [meet blur feature depends on wasm simd](https://ai.googleblog.com/2020/10/background-features-in-google-meet.html) which is only shipped in chrome at the moment.  While firefox nightly does support wasm simd, there are some known interop issues in other APIs that would also need to be worked around before it could be used there.

**Comment by mfalken** [comment]
Thanks for those who filled in the Doodle: https://doodle.com/poll/gn4ew5n3eni3kyik?utm_source=poll&utm_medium=link

If you haven't yet, please do if you have a preference. It's looking like Fri Nov 20 is the popular option now. By the way, you can scroll to the right to see more days. cc/ @yoavweiss  @jungkees @n8schloss @erik-anderson @SteveBeckerMSFT

**Comment by wanderview** [comment]
FYI, due to the time change in the US I think the meeting time is now 1 hour earlier than previously.  This still works for me, but wanted to highlight for other folks.  Might be hard to move later since folks in JPT are already calling in at 11pm.

**Comment by mfalken** [comment]
Thanks Ben for pointing this out. Let's go ahead with November 20 based on the Doodle responses. I've created #1553 for this meeting.

**Comment by wanderview** [comment]
@youennf can you share the slides you presented on background_fetch?

**Comment by youennf** [comment]
> @youennf can you share the slides you presented on background_fetch?

They are currently available at https://docs.google.com/presentation/d/1bFufsntEd8WV__ipfXUS5T2j02C6_JDJRTA0rvlN-qw/edit#slide=id.p
