### ISSUE TITLE
export 'ServiceWorkerRegistration/service worker registration'

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/ServiceWorker#1537]
Spec's that are extending `ServiceWorkerRegistration` probably need to refer to the [service worker registration](https://w3c.github.io/ServiceWorker/#dfn-service-worker-registration) associated with a `ServiceWorkerRegistration`, i.e. https://w3c.github.io/ServiceWorker/#serviceworkerregistration-service-worker-registration. That definition isn't currently exported though.

**Comment by jakearchibald** [comment]
Agreed. Fixed in ce67c0407def81312fcf51643f0b5d733b42ea31.
