### ISSUE TITLE
importScripts request does not include Service-Worker header

### ISSUE THREAD

**Issue by tms320c** [w3c/ServiceWorker#1538]
This GET request for the root service worker script does include "Service-Worker: script" header as required by the spec, while the GET request generated by importScripts() from the root script does not. 

This is behavior of the recent (at the moment of the issue submitting) desktop versions of Chrome 85.0.4183.102 (Official Build) (64-bit), FireFox 80.0.1 (64-bit), and Edge  85.0.564.51 (Official build) (64-bit). 

I did not test this behavior neither on the mobile devices, nor with other browsers.

**Comment by jakearchibald** [comment]
Why should it?

**Comment by tms320c** [comment]
Well, it looks natural. If a browser loads service worker script with this header (and it is mentioned in the spec), and the script's server can verify (a bit) the request, why it (browser) does not set the header if the request is initiated in another way, using 'importScripts' instead of 'register'?

In the current situation, the same functionality (service worker loading) looks not the same from the script's server point of view.
At least, it worth to mention the difference in the documentation or in the spec, or make clear that the header is optional.

**Comment by jakearchibald** [comment]
The header isn't optional, it's included on the request for the service worker script, always. It isn't included on additional requests made by that script, including fetch and importScripts.

It's definitely mentioned in the spec - it's requires that header to be there on root service worker scripts, and it requires it isn't there on other requests.
