### ISSUE TITLE
`Vary` and requests added after the SW

### ISSUE THREAD

**Issue by yoavweiss** [w3c/ServiceWorker#1542]
I learned recently that [`Cache.match()`](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match) is taking the Vary headers into account when matching requests and responses. That seems neat.

At the same time, for request headers added after the SW (e.g. `Cookie`, `User-Agent`) that doesn't seem like something that can work: The server indicates that the request would vary based on the user state or browser version, but that is not respected because the `Request` objects the SW's `fetch` event sees don't contain those headers and would always match, even if those headers changed in the underlying layers.

The reason I'm looking into this is that for Client Hints, we decided on adding them above the SW in order to have visibility into their values when matching responses, but that has many downsides, especially when it comes to SW generated requests.

Maybe the right path here is a way to provide those relevant values to `match()` (coming from the relevant JS APIs) in a generic way that'd enable it to take them into account?

**Comment by wanderview** [comment]
I'm not sure I understand the issue.  The `VARY` header is indeed on the request, but that just instructs the matching algorithm as to which headers to inspect on the *response*.   So I'm not sure it matters when the browser sets certain request headers since this algorithm is comparing response headers.

**Comment by yoavweiss** [comment]
It's the other way around.
`Vary` is a response header, which value indicates which request headers should be considered when matching requests to responses.
That way, a response with `Vary: User-Agent` that was cached in response to a request with a `User-Agent` header of Chrome 86 will no longer match requests with the Chrome 87 UA string.

**Comment by wanderview** [comment]
Oh, yes.  Sorry for my confusion.

**Comment by mfalken** [comment]
Sorry, what does "below" mean here? 

Last I understood, Chrome sets the User Agent header before the service worker (i.e., the SW sees the UA header).

The spec says the User Agent header should be set after the service worker (i.e., the SW doesn't see the UA header).

Related bugs are https://crbug.com/595993, https://crbug.com/962620, https://crbug.com/963260

**Comment by yoavweiss** [comment]
Apologies for the confusing langauge. By "below", I meant "added after SWs".

**Comment by yoavweiss** [comment]
We discussed this in last week's call.
I think we can close this, as it seems like a better design to add headers before the SWs, rather than somehow expose the same variables to Vary. For Client Hints specifically, I outlined the [solution](https://docs.google.com/document/d/1Oiai_wH5Me8QttrjdeC-zjJEO2a2KfpwwbtoIrQacUo/edit#heading=h.f3rdp3f4ot1u) I have in mind.
