### ISSUE TITLE
<object> having issue with service workers registration, failing with error message Service worker registration failed with: DOMException: Failed to register a ServiceWorker: The document is in an invalid state.

### ISSUE THREAD

**Issue by RamLodhi111** [w3c/ServiceWorker#1546]
I am trying to have an child app which is a PWA app  inside /< object >/ tag of parent app.
Getting below error
Service worker registration failed with: DOMException: Failed to register a ServiceWorker: The document is in an invalid state.

**Comment by GidijalaAnoopKumar** [comment]
did you solve this error?? I got the same issue with chrome browser where as it is working fine with firefox browsers

**Comment by wanderview** [comment]
Please file a chrome bug.  https://bugs.chromium.org/p/chromium/issues/entry

**Comment by RamLodhi111** [comment]
No, <object> or <iFrame> tags doesn't support PWA apps inside them.

**Comment by jakearchibald** [comment]
Service worker should be used for iframes, so please file a bug if that isn't working (although, be aware that some browsers use third party isolation for cross origin iframes)

As for embed/object, it's unsafe to intercept those, as some plugins do not use the same security model as the web (eg Flash) https://w3c.github.io/ServiceWorker/#implementer-concerns

**Comment by ZaidKhan144** [comment]
Hi, @RamLodhi111 

Were you able to solve this issue? I just ran into it. Please, any help would be appreciated.

**Comment by jakearchibald** [comment]
In most cases, you can use an iframe instead. Does that work for you?

**Comment by RamLodhi111** [comment]
@ZaidKhan144  No, I was not able to resolve the issue.
