### ISSUE TITLE
Virtual call on November 20, 2020

### ISSUE THREAD

**Issue by mfalken** [w3c/ServiceWorker#1553]
Virtual call on November 20, carrying over topics from #1536 

## 20 Nov, 2020 [14:00-16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20201120T140000&p1=tz_gmt&p2=43&p3=33&p4=248&p5=195&p6=224)
Zoom URL TBD

## Meeting notes

TBD

## Agenda

- **The timing of header setting in fetch** - Sometimes [headers are set pretty late](https://github.com/w3c/ServiceWorker/issues/1542), is this something we should/could change?
- **Fix worker timing** - Right now it isn't well described, [can we salvage it](https://github.com/w3c/resource-timing/issues/119#issuecomment-694627668)?
- **Determine expected parameter values in Navigation + Resource Timing APIs for responses that have been synthesized using a Service Worker**: https://github.com/w3c/navigation-timing/issues/124
- **Ye old CSS CORS issue** - https://github.com/w3c/ServiceWorker/issues/719
- **The proposal for ServiceWorkerRegistration.id** in #1512. There is a bit of contention on the issue. @wanderview would like to hear wider input to try to resolve things.
- **whether cross-origin-isolated value can be platform dependent or not** - https://github.com/w3c/ServiceWorker/pull/1545

**Comment by mfalken** [comment]
As Ben pointed out, due to the daylight savings change in some regions, the original time shown on the Doodle might not be the currently scheduled time now. Let me know if the currently scheduled time won't work out for you.

**Comment by annevk** [comment]
Will someone create a calendar invite again?

**Comment by asakusuma** [comment]
I'm on PST time and I'm fine with the time. I'd personally rather be meeting at 6:00 than 23:00 :)

**Comment by mfalken** [comment]
Thanks all. I sent details/calendar invite to member-serviceworkers@w3c.org.

**Comment by wanderview** [comment]
I believe the minutes/notes from the meeting are [here](https://docs.google.com/document/d/1ybS1q2HCPh3bNNOkjGpAPFug19A2BsIxYEi-i6lrB1w/edit).

**Comment by mfalken** [comment]
Thanks, yes. I've updated the individual issues with summaries of the meeting discussion, if they were not already.
