### ISSUE TITLE
get importScripts to work offline

### ISSUE THREAD

**Issue by tomasgil123** [w3c/ServiceWorker#1555]
Hi guys, does anyone know how to import scripts in the service worker while being offline?

I tried caching the resource I want to import, but is not working :/ 
```
async function getIdb() {
  if (typeof idb === 'undefined') {
     try {
       self.importScripts('https://cdn.jsdelivr.net/npm/idb@5.0.7/build/iife/with-async-ittr-min.js')
     } catch (err) {
       console.log('err idb')
    const cache = await caches.open(STATIC_CACHE_NAME)
    const cacheIdb = await cache.match(
      'https://cdn.jsdelivr.net/npm/idb@5.0.7/build/iife/with-async-ittr-min.js'
    )
    self.importScripts(cacheIdb)
    }
  }
}

getIdb()
```
Any ideas?

**Comment by makotoshimazu** [comment]
Scripts must be loaded until the install event finishes. Calling importScripts() for a new script after installation fails.

**Comment by makotoshimazu** [comment]
Ref: Step 4 at https://w3c.github.io/ServiceWorker/#importscripts
