### ISSUE TITLE
How can we intercept network requests comes from iframe

### ISSUE THREAD

**Issue by suryadevelope** [w3c/ServiceWorker#1565]
hi all 

how can we intercept network requests come from iframe using service worker...

my iframe code look like this

`document.getElementById('o').setAttribute('srcdoc','<img src="assets/a1.jpeg"/>')` 

here i need to listen the img src get request 

can any one tell me how is this possible

**Comment by wanderview** [comment]
Per the spec a srcdoc iframe should inherit the service worker from the parent document.  This is implemented in firefox, but not chrome.  (Not sure about safari.)  The chrome bug for fixing this is crbug.com/880768, but its not currently a priority.

I believe browsers are more consistent about inheriting the service worker for blob URLs, though.  So you could try making a blob URL iframe.

**Comment by suryadevelope** [comment]
@wanderview 
thank you for your response 

actually my point is i had used iframe using src attribute indicating to local html where all my html code is present 
in that code there is an img tag in that , i got the fetch request in the service worker,

when i add total html using sorcdoc to an iframe , i am unable to get the fetch request of that image in service worker

is there any way to get that fetch request or am i doing any thing wrong.....

**Comment by mfalken** [comment]
@suryadevelope As @wanderview points out Chrome has a bug where srcdoc iframes are not recognized by service workers: https://crbug.com/880768

This GitHub repository is about the specification, which already matches what you are expecting: srcdoc iframes should be recognized, so there is nothing to change here in the spec. If this is a behavior you are seeing in Chrome, you can star/follow that Chromium bug.

**Comment by jakearchibald** [comment]
Covered by the crbug link - not a spec issue
