### ISSUE TITLE
Old React.JS App with sw.js never ditches and switches to new Svelte.JS App with service-worker.js

### ISSUE THREAD

**Issue by michaelcuneo** [w3c/ServiceWorker#1578]
This is more of a usage question rather than an issue.

How would I force any browsers who have loaded an old project written in React.JS with a sw.js to reload a brand new service-worker.js instead, and it's corresponding app, and files, etc... 

My app appears to be locked into the old sw.js, and won't load the new service-worker.js

I don't want to have every client to have to manually perform an administrative stop/unregister/reload under Application or any other hard reset of SW procedure... because that could be thousands of users.

Not sure how to go about this... I have placed a sw.js inside the new project alongside service-worker.js and it's sole purpose is to find and destroy any service workers currently found in the browser pertaining to the endpoint. But it doesn't register a new service-worker.js I don't think. There's no way for me to test this properly because the old app hosted on S3 and was Client Side, and the new app is hosted as a Lambda Function, and is Server Side.

**Comment by jakearchibald** [comment]
A self-destructing service worker at the same URL as the old one will do the trick. You may want to get it to reload all clients, so they go to the network rather than the old service worker.

You might have more luck if you avoid changing the URL of the service worker. Details: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle

**Comment by michaelcuneo** [comment]
Well the old service worker was in a folder on an S3, the new service worker is in the root of a Lambda function, I push the site up using apex/up so I end up with a .zip in an S3 that is compiled into the lambda, and I don't really have any access or control over what gets into folders, how and when... some people who have seen or visited the site in the past, cannot see the new version so they're stuck.

I can't do my usual old sw.js new sw.js workflow testing, because of the obvious, S3 <--> Lambda switch. Even if I injected some SSR sw.js code into the Lambda to serve, how do I know what folder it's in or where it's coming from.
