### ISSUE TITLE
Exempt path restriction for for static import in a module service worker

### ISSUE THREAD

**Issue by ghazale-hosseinabadi** [w3c/ServiceWorker#1586]
It seems to us that we should not impose the path restriction on static-imports for module service workers. This is aligned with the classic worker script's importScripts. Please let me know your thoughts. Thanks!

**Comment by wanderview** [comment]
Looking here, I don't think the spec says to impose path restrictions on static imports:

https://w3c.github.io/ServiceWorker/#update-algorithm

See step 4 in the "performing the fetch" subsection.  It returns if not top-level before checking the Service-Worker-Allowed header.
