### ISSUE TITLE
fetch request catching in service worker with iframe

### ISSUE THREAD

**Issue by suryadevelope** [w3c/ServiceWorker#1587]
Hai everyone
1). In Firefox the fetch request in the iframe is catches perfectly by the service worker but why not in chrome
2). In Firefox even thow failed fetch request is catched but unable to return the cached item back 

how to achieve this

**Comment by jakearchibald** [comment]
Closing this, since it isn't a spec issue. However, I'm happy to continue to provide support. Can you create a demo of the issue you're seeing, along with how you expect it to behave? Glitch.com is a good place to create a demo like this.
