### ISSUE TITLE
consider using navigation preload response when respondWith() is not called

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#1611]
Currently if navigation preload is enabled, but the fetch handler does not call `respondWith()` we fallback to initiating a new request.  This results in two requests to the server.  The first navigation preload request and its response are thrown away.

You may ask, why would a service worker script do this?  The answer is that writing code to consume the navigation preload response is not obvious to new developers.  Many sites end up launching a simple "no-op" service worker in order to meet PWA installation criteria.  It seems like the double-request behavior of fallback+navpreload is a bit of a footgun.

A possible solution to this would be to implicitly call `evt.respondWith(evt.preloadResponse)` if the fetch handler returns without calling `respondWith()` explicitly.  We probably could not do this in cases where there is an extra preload header, though, as that could change the underlying content of the preload response vs what a non-preload response would see.

@jakearchibald @asutherland @youennf WDYT?

**Comment by jeffposnick** [comment]
How would this account for multiple `fetch` handlers? Would that implicit `evt.respondWith(evt.preloadResponse)` only happen in the last `fetch` handler that executes?

I guess the browser _should_ know how many `fetch` handlers are registered at following `install`, but correct me if I'm wrong when I say that not every browser has been as strict about preventing post-`install` calls to `addEventListener()`.

**Comment by wanderview** [comment]
This would be after all fetch handlers had executed and when the browser decides to do a fallback request because `respondWith()` was not called by any handler.

**Comment by asutherland** [comment]
The auto-respondWith behavior as described seems reasonable.

**Comment by jakearchibald** [comment]
The request is sent with a `Service-Worker-Navigation-Preload` header, which can be assigned a custom value. The idea here is that the server could return something other than a regular response. Eg, just the main content to be inserted in some other shell, or a JSON response to be fed into app code.

Auto-responding with this could produce broken output.

**Comment by wanderview** [comment]
Yea, I thought we could not do that when the header was sent:

> We probably could not do this in cases where there is an extra preload header, though, as that could change the underlying content of the preload response vs what a non-preload response would see.

But you are saying the header is always sent?  I see now that it defaults to being sent with a value of `true`.

Ok.  I guess we can't do this then.  Sorry for the noise.

**Comment by youennf** [comment]
@jakearchibald , do you know how much this strategy is being used in practice?
Are they using Vary: Service-Worker-Navigation-Preload to prevent answering from the HTTP cache (say hard refresh)?

**Comment by jakearchibald** [comment]
> do you know how much this strategy is being used in practice?

I don't have numbers, but Facebook were keen on using it. It seems pretty good practice if you're able to serve a shell without going to the network.

> Are they using Vary: Service-Worker-Navigation-Preload to prevent answering from the HTTP cache (say hard refresh)?

I'm not sure, although content that differs per user (which is common for navigation targets) tends to be `no-cache`/`no-store` (like the headers for this page)
