### ISSUE TITLE
Capturing Audio and Webcam within Service Worker

### ISSUE THREAD

**Issue by alex2snikers** [w3c/ServiceWorker#1613]
Can't find any information about getUserMedia() alternatives

Have service workers any functionality for capturing Webcam and Audio, like getUserMedia with its streams ?

**Comment by wanderview** [comment]
Not that I'm aware of.  There would be privacy and security concerns around enabling these features in the background.  If you have a foreground tab you can postMessage() it using the clients API and then have it use getUserMedia().

**Comment by wanderview** [comment]
I meant the other way around.  You can postMessage() from the service worker to the foreground tab to ask the window to do the getUserMedia().

**Comment by alex2snikers** [comment]
I know only one way to ask for Webcam/Audio permissions is using getUserMedia() (ex. navigator.mediaDevices.getUserMedia({video: true}); )

But there is no way for using it within Service Worker, can you say how can I ask the window to do getUserMedia() through the postMessage()?
