### ISSUE TITLE
Question: Does ServiceWorker reflects to Web Performance when store cache?

### ISSUE THREAD

**Issue by sudokzt** [w3c/ServiceWorker#1625]
I have two question.

1. Does ServiceWorker reflects to Web Performance when install ServiceWorker on browser?
2. Does ServiceWorker reflects to Web Performance when store cache?

I thought ServiceWorker does not reflects to web performance. Because it run in worker thread different from the main thread.

But I wasn't sure if this idea was correct.

**Comment by jakearchibald** [comment]
What do you mean by "reflects to Web Performance"?

I don't think this is a spec question, so I'm closing this issue, but I'll continue to provide support, and reopen if necessary.
