### ISSUE TITLE
when I deploy my app new version, latest version/changes not updated at the first time reload

### ISSUE THREAD

**Issue by vinodpotru** [w3c/ServiceWorker#1627]
Hi 

I have build the blazor application but I am unable to get the updated latest version changes after deployment.

**_Issue_**: when I deploy my app new version in server, latest version/changes not updated at the first time reload but on second time reload I am getting new changes.  **_I need new changes on first reload_**

For this, I have added **skipWaiting()**  in install method.

**_Expected_**: if any new build deployed, on first time reload I need to get new version changes.

**_Note_**: On every deployment, I have updated the version number in service-worker file

Please see the below screenshots of service worker file.

![Service-worker-part1](https://user-images.githubusercontent.com/68293272/155268865-9a7a7db2-bdc9-407c-ac0b-306628c77b1b.JPG)
![Service-worker-part2](https://user-images.githubusercontent.com/68293272/155268877-e0cd3087-8120-4540-8644-298027643e82.JPG)

### Could you please help on this issue?

Thanks & Regards
Vinod Kumar

**Comment by jakearchibald** [comment]
Here's a guide to the service worker lifecycle https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle
