### ISSUE TITLE
Documentation: meaning of "The coast is only clear when all the resources are ready"

### ISSUE THREAD

**Issue by fytriht** [w3c/ServiceWorker#1635]
https://github.com/w3c/ServiceWorker/blob/2d7be2b202993a332b2b142fc498f3e089638db2/docs/index.bs#L1013

As a non-native speaker, I found that this sentence is confusing, mainly the "the coast is clear" part. 

What's the meaning of it? Or are there any typos? Thanks.

**Comment by tomayac** [comment]
Fixed via #1636. @jakearchibald

**Comment by fytriht** [comment]
Thanks!
