### ISSUE TITLE
cache.addAll accepts an array of URLs (not just requests)

### ISSUE THREAD

**Issue by noamr** [w3c/ServiceWorker#1657]
This works in practice and is documented in MDN but is not specified. SWs in the wild probably already use this, so maybe it should be in the spec.

**Comment by wanderview** [comment]
Why do you say its not in the spec?  The webidl takes a `RequestInfo` which is a typedef to `Request or USVString`.  This is then passed to a `Request` constructor in step 4.1 of addAll which normalizes any urls into Request objects.

**Comment by noamr** [comment]
You're right, I missed a part. Sorry for the noise.
