### ISSUE TITLE
Shouldn't `InstallEvent` has a constructor?

### ISSUE THREAD

**Issue by skyclouds2001** [w3c/ServiceWorker#1713]
current the definition for `InstallEvent` does not has a constructor, this is different from other event interfaces and is quite uncommon, should it also define with a constructor, too?

![image](https://github.com/w3c/ServiceWorker/assets/95597335/2856331c-1bd3-4623-955f-8162a54a999d)

relates with https://github.com/mdn/browser-compat-data/pull/22870

**Comment by skyclouds2001** [comment]
but interestingly, in browser implement `InstallEvent` is constructible

![image](https://github.com/user-attachments/assets/cd55b58b-cebf-467a-bd3e-9c4324c60fca)

test in https://worker-playground.glitch.me/

**Comment by mkruisselbrink** [comment]
Yes, I believe this is an oversight in the spec that was missed when InstallEvent was added in https://github.com/w3c/ServiceWorker/pull/1701. I can't think of any reason why we shouldn't have a constructor.
