### ISSUE TITLE
Disable SW's when cookies are disabled?

### ISSUE THREAD

**Issue by slightlyoff** [w3c/ServiceWorker#209]
SW's provide the ability to implement cookie-like behavior about HTTP requests and responses. Joey Hurst (Googler) suggests disabling SW's in UAs when Cookies are disabled. It's unclear to me that there's 1:1 overlap (similar things can be done via local state, URL re-writing, and XHR when script is disabled), but it's worth thinking about when to disable SW's in response to user configuration. When Cookies are disabled? When both cookies and JS are?

**Comment by indolering** [comment]
Sorry to bring up an old topic, but at most you should block access to the Cache.  Service workers are useful for other things besides caching, especially now that Shared Workers are all-but-deprecated.
