### ISSUE TITLE
Should 'fetch' be an event, or some different API?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#256]
Some have suggested 'fetch' shouldn't be an event, and should be another kind of callback where you return a response/promise to indicate interest in the event.

``` js
this.onfetch = function(event) {
  event.respondWidth(
    caches.match(event.request).catch(function() {
      return fetch('kittens.jpg');
    })
  );
};

// vs

fetchIntercept(function(requestDetails) {
  return caches.match(requestDetails.request).catch(function() {
    return fetch('kittens.jpg');
  });
});
```

Why it should be an event:
- Like 'click', 'fetch' is a thing that happens
- Intercepting a default action & doing something else is what deveopers use events for
- You can have multiple listeners

Why it shouldn't be an event:
- Currently `respondWith` calls `preventDefault` and `stopImmediatePropogation`, is this breaking the model?
- ...

@Hixie @stefanpenner @annevk - any further cases against?

**Comment by hemanth** [comment]
![thegooddinosaur-disney-pixar-the-good-dinosaur-3oEduMcvxTNPlGuhH2](https://camo.githubusercontent.com/916ace44c56bcec22c5937ceeb5ca2878efeae27/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f336f4564754d637678544e506c47756848322f67697068792e676966>)
