### ISSUE TITLE
[[register]] entry settings object's API

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ServiceWorker#336]
The spec says: 

> Let scope be the result of running the URL parser on scope with entry settings object's API base URL.

The entry settings object's API should be an **input** for the algorithm. It's an object that can be passed in. I presume I'm going to be passing in the `Document` in the Gecko implementation of manifest that enables SW.

**Comment by jungkees** [comment]
Note that Register algorithm has been updated to take parsed URLs for the script url and the scope url (cb6535b96490844ae365bc13bf279c621266ca7b): https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#register-algorithm

/cc @marcoscaceres
