### ISSUE TITLE
Is fetch() before or after Content-Encoding

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#339]
E.g. if I fetch something gzipped, what bytes should end up in the stream? XMLHttpRequest handles this automatically, should fetch()?

Existing browser architecture handles this pretty low-level. Are we prepared to change that? @bzbarsky @sicking @domenic @michael-nordman

**Comment by RReverser** [comment]
Having looked through the Fetch API and then through this thread as it seemed the most relevant, I'm still a bit confused: is there a way to read raw body of the HTTP response before decompression or was it decided that this low-level API should be an implementation detail available only to the Cache API and not to JS consumers?

**Comment by jakearchibald** [comment]
> is there a way to read raw body of the HTTP response before decompression

Not right now, no.

**Comment by RReverser** [comment]
@jakearchibald Ok, thank you, at least now I have definitive answer.

**Comment by wanderview** [comment]
> or was it decided that this low-level API should be an implementation detail available only to the Cache API

FWIW, I don't think Cache API has access to this either.  Stuff like `Cache.add()` effectively does a fetch() which will strip any content-encoding.  At least from a spec perspective.

**Comment by sheerun** [comment]
> > is there a way to read raw body of the HTTP response before decompression

> Not right now, no.

@jakearchibald Can this be addressed? I also need to access original response
