### ISSUE TITLE
Use RequireJS to load external libraries within ServiceWorker

### ISSUE THREAD

**Issue by pdorgambide** [w3c/ServiceWorker#456]
Hello:
What is the right way to use RequireJS to import external libraries within a serviceworker? 
In the scope of WebWorkers importScript()  can be used , but how would be resolved in the scope of ServiceWorker where the connection could be out?. ImportScript() fail and would have to search the libraries ( cache,etc ) into the Serviceworker caches?? 
I tried to searh into the "trained-to-thrill" demo but seems that require is injected when compile the project..

Thanks a lot and great job,

**Comment by bsed** [comment]
i have same problem.
