### ISSUE TITLE
Consistency of ServiceWorkerClient fields

### ISSUE THREAD

**Issue by dmurph** [w3c/ServiceWorker#500]
I'm looking at implementing these fields, and I'm wondering, is there any consistency guarantees w/ client properties? Especially regarding the URL, which can be changed via javascript w/o loading a new page (and making a new client).

Interface here:
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-client-interface

**Comment by mattto** [comment]
The conclusion is Client is a snapshot and doesn't get updated. It'd be good to have tests for this. I'll look into filing a new issue to add tests.
