### ISSUE TITLE
skipWaiting issue on different registrations

### ISSUE THREAD

**Issue by seanlong** [w3c/ServiceWorker#561]
Thinking a scenario like below:
"foo1.html" is using registration A(scope: "foo1");
"foo.html" is using registration B(scope: "fo");
"fo2.html" is using registration B(scope: "fo");

Now a new worker of registration C(scope: "foo") registers itself with skipWaiting(), the result should be: "foo1.html" controller not change, "fo.html" controller changes to the new worker, and "fo2.html" controller not change. Am I right?

So I think what we do when skip-waiting-flag is set might look like:

```
for each client who will be controlled by this registration:
   if its existing worker is not null
       wait for existing worker to finish any in-process requests
       let client do not use its current registration anymore
run activate algorithm...
```

By the way should part 4.1.7 step 2.2.1: " Run Activate algorithm, or its equivalent..." change to the steps described above too?

**Comment by mattto** [comment]
skipWaiting() is only affects clients that are already using a registration; claim() is used to change the registration a client is using.

In https://github.com/w3c/ServiceWorker/issues/561#issuecomment-63252861, I said the spec is too aggressive, but looking at today's spec, the step on matching URLs is only for resolving .ready and disassociating AppCache, which is fine. Actually changing the controller is done in another step, which is on clients that are using registration already.
