### ISSUE TITLE
A header-based SW installation

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#685]
It's been discussed as part of the `navigator.connect()` and decided to be proposed as an extension to SW API (v2).

Assuming a communication between a _client_ SW and a _service_ SW is enabled through the efforts in `navigator.connect()`'s [persistent channel messaging](https://github.com/mkruisselbrink/navigator-connect/blob/gh-pages/explainer.md#inter-app-rpc) and the [fallThrough requests proposal](https://github.com/slightlyoff/ServiceWorker/issues/684), the _client_ SWs would need to use readily installed _service_ SWs whenever possible.

Here's a proposal to allow _services_ to install their SWs using HTTP headers when any of their resources are requested: https://github.com/mkruisselbrink/navigator-connect/blob/gh-pages/explainer.md#mommy-where-do-service-workers-come-from

**Comment by jakearchibald** [comment]
You could have:

```js
// https://foo/sw.js
self.oninstall = event => {
  event.waitUntil(
    event.registerExternal('//font-service/sw.js')
  );
};
```

`//font-service/sw.js` would require a `Service-Worker-Scope` header, which would be the scope on `//font-service` that it would be registered to.

```js
// https://font-service/sw.js
self.oninstall = event => {
  event.handleFallThroughRequests(['/resources', '/font']);
  // …
};
```

URLs passed to `handleFallThroughRequests` must be within the SW's scope.

My questions/concerns about this model:

* The number of workers that may be needed to handle requests to a single page - is this a problem?
* How/when will `//font-service/sw.js` be checked for updates?

**Comment by jakearchibald** [comment]
On #684 I pitch the idea of:

```
// https://foo/sw.js
self.oninstall = event => {
  event.waitUntil(
    event.registerExternal('//font-service/sw.js')
  );
};
```

This would only require `'//font-service/sw.js` to have a header indicating scope. It doesn't allow page/subresource headers to register a ServiceWorker, but is there any benefit in doing this?

**Comment by mkruisselbrink** [comment]
I don't really like the idea of having in this case the `foo` service worker specify the exact path to the `font-service` service worker script. It seems to me that conceptually the script URL of a service worker should be an implementation detail of that site, and not part of its public API. But maybe that's just my mental model being wrong. 

And specifically for the [fonts usecase](https://github.com/mkruisselbrink/navigator-connect/blob/gh-pages/explainer.md#solving-the-fonts-problem), allowing subresource headers to register a ServiceWorker is what makes this all work transparently. I'm not entirely sure what we would gain by requiring any website that wants to benefit from a fonts service worker to explicitly specify this. Shouldn't websites that don't have their own service worker also be able to benefit from services they rely on having service workers?

**Comment by jakearchibald** [comment]
> allowing subresource headers to register a ServiceWorker is what makes this all work transparently

I don't think it does. Your site should work offline after install. Since font requests happen when the font is requested, you could end up with a serviceworker installing without a request to the font service.

> Shouldn't websites that don't have their own service worker also be able to benefit from services they rely on having service workers?

Hmm, yeah, that would be nice.

**Comment by KenjiBaheux** [comment]
@jungkees I lost track of this feature. Was there any other relevant discussion or pushback?

We are discussing with partners and for some a header based SW installation is a must have (e.g. Google Fonts: no a destination website, integration point == <link rel=stylesheet...>)

**Comment by jungkees** [comment]
I think it has just not been discussed for a while. I added this issue to the f2f agenda. If there's not enough time to cover this, I'll at least share it with the attendees so we can follow up on the discussion.

**Comment by jakearchibald** [comment]
F2F:

Header: `Link: </sw.js>; rel=serviceworker; scope=/`
But also element: `<link rel="serviceworker" scope="/" href="/sw.js">`

**Comment by ehsan** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1243404

**Comment by mkruisselbrink** [comment]
@annevk How would I go about actually spec-ing this? 

The `<link rel=` part is probably relatively straight forward. Similar to how specs like the web app manifest specified a new link type, we can do the same in the service worker spec for the new serviceworker link type. Although I'm not sure how we'd add the new 'scope' attribute to the link tag without changing the HTML spec directly?

But what do we do about the Link header. https://www.w3.org/wiki/LinkHeader makes it sound like it isn't actually specified anywhere (other than some old version of HTTP 1.1). So how/where should Link be specified?

**Comment by KenjiBaheux** [comment]
Perhaps, following how it's done for preload would work?
http://w3c.github.io/preload/
cc/ @igrigorik

**Comment by KenjiBaheux** [comment]
Blink bug: https://code.google.com/p/chromium/issues/detail?id=582310

**Comment by mkruisselbrink** [comment]
Ah yes, thanks. I must have not been searching for the right things. That looks helpful for inspiration.

**Comment by annevk** [comment]
The header is defined in https://tools.ietf.org/html/rfc5988. And yes, we'd have to modify the HTML standard to properly define the element.

**Comment by sideshowbarker** [comment]
FYI I wrote a PR for adding `<link rel=serviceworker>` and `scope`, `workertype`, and `usecache` to the HTML spec: https://github.com/whatwg/html/pull/2356

**Comment by annevk** [comment]
Were tests written for this as well?

**Comment by wanderview** [comment]
Looks like it:

https://github.com/w3c/web-platform-tests/blob/master/service-workers/service-worker/register-link-element.https.html
https://github.com/w3c/web-platform-tests/blob/master/service-workers/service-worker/register-link-header.https.html

**Comment by mkruisselbrink** [comment]
Yes, I believe the only things left to do here are I think the cleanup from #1098 and IANA registering the new link relation type.
