### ISSUE TITLE
Remove frameType, maybe add ancestorOrigins

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#732]
Frame type does not address the use case of e.g., an embedded youtube.com showing fallback content. (Where youtube.com embedded in youtube.com should not show such a thing.)

**Comment by jungkees** [comment]
F2F: Spec ancestorOrigins and remove frameType for now. We can get it back if it's really required in the future.

**Comment by jungkees** [comment]
Just to check if the decision still holds. Is it still okay to remove `Client.frameType`?

**Comment by jakearchibald** [comment]
F2F: Adding `ancestorOrigins` if fine as long as you can already get this information.

`frameType` is still useful for "auxiliary", which you can't determine from `ancestorOrigins`.

**Comment by annevk** [comment]
When do you want to check `auxiliary`? Should it be `auxiliary` when `noopener` is set?

**Comment by jakearchibald** [comment]
Pre F2F notes: come up with an answer to @annevk's question

**Comment by jakearchibald** [comment]
F2F:

* We don't have solid use-cases for `frameType` right now, we should remove it and add it back if/when we get better data
* Keep `ancestorOrigins`, but it's only needed on `WindowClient`

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1290936

**Comment by jungkees** [comment]
@annevk, I'm planning to factor the steps of [`location.ancestorOrigins`](https://html.spec.whatwg.org/multipage/browsers.html#dom-location-ancestororigins) out as an algorithm that both `location.ancestorOrigins` and `WindowClient.ancestorOrigins` can invoke (taking an environment settings object as an argument.)

Currently, `location.ancestorOrigins`'s step 1 throws "SecurityError" if the relevant document's origin is not the same as entry settings object's origin. I don't think this would be meaningful for `WindowClient.ancestorOrigins` where the entry settings object's origin will always be the same as the client's origin. I'm not sure what the purpose of this security check in the first place.

In case we should retain this entry settings object checking step, should I make the algorithm take both relevant settings object and the entry settings object as arguments? Or any good idea how to define this algorithm?

/cc @domenic

**Comment by annevk** [comment]
Yes, that security check is important for `Location` objects. Is a `WindowClient` always same-origin?

I think you basically want to make the computation of this array reusable https://html.spec.whatwg.org/multipage/browsers.html#concept-location-ancestor-origins-array and not bother with `ancestorOrigins` itself (that you'd just define to return such an array).

**Comment by jungkees** [comment]
Yes, `WindowClient` is exposed to only service workers, and only same origin clients can be retrieved.

> just define to return such an array

That sounds good.

Out of curiosity, why is the security check in the attributes of `Location` against the **entry** settings object?

**Comment by annevk** [comment]
That is what browsers implement. I believe it comes into play when you use document.domain, but it's been a while. We might change away from entry if we can, we'll see.

**Comment by jungkees** [comment]
I see. So it was in this list: https://github.com/whatwg/html/issues/1431#issue-160503593

**Comment by jungkees** [comment]
Addressed: https://github.com/w3c/ServiceWorker/commit/58be22d7ffdb743db406c02175b9268569c3e1f5

Closing.

**Comment by wanderview** [comment]
Note, `location.ancestorOrigins` has a privacy issue here:

https://github.com/whatwg/html/issues/1918

Which blocks gecko implementation for the moment.

**Comment by jakearchibald** [comment]
Implementations haven't removed this, we should add it back to the spec but mark it as at risk.

We should look at usage and see if we can at the very least move it to windowclient.

"auxiliary" is the only feature ancestor origins doens't give us.

**Comment by jungkees** [comment]
> We should look at usage and see if we can at the very least move it to windowclient.

@mattto, wanderview, do you happen to have any data on the usage of `Client.frameType`?

> When do you want to check auxiliary? Should it be auxiliary when noopener is set?

For the client opened with "rel=noopener", Chromium returns "top-level", and Firefox returns "auxiliary" at the moment.

@annevk, do you have any update on https://github.com/w3c/ServiceWorker/issues/1075#issuecomment-290983186?

**Comment by jungkees** [comment]
I'm planning to add `frameType` back. EdgeHTML, Chromium, Gecko all maintain it. @cdumez, does WebKit support it?

**Comment by annevk** [comment]
Hmm, it seems that'd become redundant with https://github.com/whatwg/fetch/issues/755 too, but if implementations cannot remove it...

**Comment by jungkees** [comment]
Yeah, implementations have maintained it so far, and `client.frameType` can also be accessed out of fetch event handlers, too.
