### ISSUE TITLE
Should the active worker move to environment settings object?

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#811]
It seems the navigation behavior in HTML has changed and says now a navigation doesn't create a new environment settings object but just re-use the settings object for the browsing context: https://html.spec.whatwg.org/#navigating-across-documents:set-up-a-browsing-context-environment-settings-object.

An environment settings object is a good fit to cover both window clients and worker clients. I think service worker client's [active worker](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#dfn-service-worker-client-active-worker) should move to environment settings object. And resetting the active worker can be specified in the HTML navigation algorithm. WDYT?

/cc @annevk @domenic

**Comment by annevk** [comment]
@domenic should probably weigh in, but I think that any state should be stored on the document. The global is not a great place.

**Comment by jungkees** [comment]
Then what do we do with workers? I don't think we're adding an unnecessary state. If that's still not desired, I guess at least we need a new _client_ definition that holds necessary info for fetch and sw. What was the reason that environment settings object's lifetime is tied to the entire browsing context lifetime by the way?

**Comment by annevk** [comment]
For workers it's fine to use the global object. I'm not saying the state is unnecessary, I'm just saying to put it on documents when the global is Window, and on the global elsewhere.

(And the reason the Window global is so messed up, not sure. Largely history at this point. We should probably explain that a bit somewhere if we haven't already.)

**Comment by slightlyoff** [comment]
Going to resolve in favor of Client changes #870

**Comment by jakearchibald** [comment]
Pre F2F notes: Doesn't look like there's anything to discuss

**Comment by jungkees** [comment]
F2F: We will have the active worker internal slot in global objects and have the corresponding environment settings objects return those values. This issue depends on and will be resolved by the changes that client-creating steps will make (among HTML, SW, and Fetch): #870.

**Comment by jungkees** [comment]
The active service worker has settled on the newly defined [_environment_](https://html.spec.whatwg.org/#environment) concept finally!
