### ISSUE TITLE
Is a new property to get the navigation's target client needed?

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#817]
As discussed in https://github.com/slightlyoff/ServiceWorker/issues/808, `FetchEvent.clientId` returns null for a navigation request. But as Mozilla suggested, we may need a new property (reservedClientId or potentialClientId?) to get the target client's id if it has use cases.

**Comment by slightlyoff** [comment]
I think we can just pre-emptively add a `clientId` in the case of a navigation instead of a new property. If a Client is created, you'll be able to get it from the clients list. If not, we just won't have a matching client at some later point. This seems entirely normal to me.

Objections?

**Comment by jakearchibald** [comment]
I still don't think reusing `clientId` is a good idea https://github.com/slightlyoff/ServiceWorker/issues/808#issuecomment-169625196

**Comment by slightlyoff** [comment]
I don't understand this concern. Clients can disappear at any time. That's just life in a multi-process world.

That said, if instead we had a promise-returning getter that handed you the client (or null if none) in this case, that'd work for me too (both in this case and in the general client fetch scenario). I don't have any sympathy whatsoever for @annevk's arguments abut GC. GC isn't observable here.

**Comment by jakearchibald** [comment]
> Clients can disappear at any time.

Right, but `clients.get(fetchEvent.clientId)` currently returns null when the client no longer exists. This means I can remove any book-keeping data in idb relating to that client.

The change you're suggesting means `clients.get(fetchEvent.clientId)` returns null when the client no longer exists, may never exist, or may exist at some point in the future, or may point to a client we can't expose (another origin). This makes it useless for the book-keeping case.

That aside, I don't think it's useful to reuse `fetchEvent.clientId` for two separate things, especially as we might want to expose both of those things separately in future. It could be useful to know the id of the client that initiated the request, and the one potentially created as a result of the response. You could use this to link clients together and build a navigation tree.

For the promises case, `clients.get(id)` could wait if it's passed a reserved id, and only resolve once the client is created, or the browser knows the client will not be created.

**Comment by jakearchibald** [comment]
FWIW this came up when trying to emulate appcache via SW.

Appcache assigns a version of a manifest on navigation, so we'd need to create a record that links a client to a cache at the time of the client request. This same cache needs to be used for subresources of the client (if a client is created).

We have ideas for workarounds (which come with race conditions, but they'd be highly unlikely) so it's not a blocker, but it's an interesting use-case.

**Comment by jakearchibald** [comment]
I think we should have both btw. `clientId` should represent the client that initiated the request, and `potentialClientId` should be populated if the result *may* create a new client.

This means:

```js
if (fetchEvent.request.mode == 'navigate' && fetchEvent.clientId && fetchEvent.potentialClientId) {
  clients.matchAll().then(clients => {
    if (clients.length == 1) {
      // there's a single page open, and it's in the process of navigating
    }
  })
}
```

**Comment by isonmad** [comment]
This was fixed with https://github.com/w3c/ServiceWorker/commit/8b483b091e0f0bae6b698cf05d915c2029748ae0 and https://github.com/w3c/ServiceWorker/issues/870 right?
