### ISSUE TITLE
Resolve Job Promise can resolve jobs with an incorrect value

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/ServiceWorker#829]
Currently the Resolve Job Promise algorithm resolves all equivalent jobs with the same value, I don't think this is correct. For example multiple equivalent register jobs should possibly be resolved with distinct `ServiceWorkerRegistration` instances (if they were called from different javascript contexts). But maybe more importantly, two equivalent jobs can have different `client` properties; this means that for example with a register job each equivalent promise needs a `ServiceWorkerRegistration` instance with a different associated service worker client.

**Comment by wanderview** [comment]
Where does ServiceWorkerRegistration have an associated client?  I don't see that in the spec.

**Comment by mkruisselbrink** [comment]
> Where does ServiceWorkerRegistration have an associated client? I don't see that in the spec.

https://slightlyoff.github.io/ServiceWorker/spec/service_worker_1/#dfn-service-worker-registration-interface-client

**Comment by wanderview** [comment]
Oh, I see.  I'm probably missing something, but it seems thats not really needed.  The .installing/waiting/active getters could get the service worker client from the current context's service worker client.

**Comment by mkruisselbrink** [comment]
I'm not even sure what `ServiceWorker` needs an associated service worker client for. It's `postMessage` method doesn't even use the associated client but looks it up from the incumbent settings object instead, and I can't see anywhere else it is used either. So yes, removing the associated client from `ServiceWorker` and `ServiceWorkerRegistration` is probably the sanest solution, unless we're both missing something.

**Comment by jungkees** [comment]
F2F: I'll inspect and fix it.
