### ISSUE TITLE
html no longer defines "referrer source"

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/ServiceWorker#834]
@annevk removed the definition of "referrer source" in whatwg/html@7c5555a16f2920c02244c10756bb2f1a11e87a22 , but this spec still links to that (in Run Service Worker and the importScripts definition). This should somehow be fixed.

**Comment by domenic** [comment]
It looks to me like this is solvable by removing the reference to "referrer source" in the definition of the settings object (in Run Service Worker), then in importScripts saying "with [referrer](https://fetch.spec.whatwg.org/#concept-request-referrer) set to _settings object_'s API base URL."

**Comment by annevk** [comment]
If referrer matches the client you passes to Fetch, you don't have to set it at all. Referrer is never the base URL by the way (unless it happens to match the URL of the resource).

**Comment by jakearchibald** [comment]
Pre F2F notes: Does @domenic's proposal work here?

**Comment by domenic** [comment]
Hmm, now that I know more about this, probably not. Setting the referrer from a settings object is in general tricky; see https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer.

**Comment by jungkees** [comment]
F2F: Change SW to use referrer policy language.

**Comment by annevk** [comment]
Sounds reasonable.

**Comment by domenic** [comment]
Sounds exactly right, thanks!
