### ISSUE TITLE
consider exposing install time on ServiceWorker DOM object

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#842]
It might be nice to expose when a service worker was installed.  This could be used for debugging and other diagnostics.  For example, the site could send the value to the server and if it sees that a client is not updating for some reason then send the serviceworker kill header.

**Comment by wanderview** [comment]
In IRC Jake suggests exposing last update attempt time on registration as well.

**Comment by delapuente** [comment]
In addition to the [proposal of relying on server headers to perform an update](https://github.com/slightlyoff/ServiceWorker/issues/839), this could be very convenient.

**Comment by jakearchibald** [comment]
F2F: lukewarm. Wait for more usecases.

**Comment by jakearchibald** [comment]
F2F: lukewarm. Wait for more usecases.
