### ISSUE TITLE
Add client "close" event

### ISSUE THREAD

**Issue by AshleyScirra** [w3c/ServiceWorker#868]
If a SW wants to map a `clientId` to some state, there's no good way to know when to remove the map key. Adding an event that is fired when a client is closed would make this simpler.

Note you can't use a `WeakMap`, since `clients.get()` returns a different Client object every time even for the same `clientId`, so the same client gets added as new keys every time (which IMO is a nasty gotcha).

**Comment by jakearchibald** [comment]
We should consider this feature.

In the mean time, performing GC like this when you see navigation fetches works pretty well

**Comment by wanderview** [comment]
It would need to be slightly different from "close".  Currently the spec controls windows, not documents.  So a client can be closed, but also just navigated to a non-controlled document.  In that case the client still exists, but is no longer a controlling client.

Perhaps we could add events to Client for transition controlled vs non-controlled state.

**Comment by NekR** [comment]
Also `Ctrl/Cmd + Shift + T` (re-open tab) restores previous state of the page & back/forward history navigation can perform just session state restore. So this cannot be just `close` event, because then you will need an `open[-again]` event.

**Comment by jakearchibald** [comment]
https://github.com/w3c/ServiceWorker/issues/886 seems to have more detail
