### ISSUE TITLE
Drop isReload

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#873]
I think we should go lower level here.

If we supported https://github.com/slightlyoff/ServiceWorker/issues/817#issuecomment-206396683 I'd be able to tell that a client of url was instigating a navigation request to the same url.

This may be a reload, or may be opening a new window, so additional information like "target" would be needed.

**Comment by jakearchibald** [comment]
Issue for the target client id https://github.com/slightlyoff/ServiceWorker/issues/874

**Comment by jakearchibald** [comment]
It's possible that knowing the reload button was pressed (or pull-to-refresh) is interesting enough to keep this feature, as the client Ids won't express that.

**Comment by wanderview** [comment]
Is the refresh button observable in the FetchEvent.cache value?  Doesn't it set it to something that requires revalidation?

**Comment by jakearchibald** [comment]
Chrome seems to request with `cache-control:max-age=0` on refresh

(guess you mean `fetchEvent.request`?)

**Comment by wanderview** [comment]
Sorry, I meant `FetchEvent.request.cache`.  Firefox nightly right now generates "default", but I think thats a bug.  If I fix the code to actually look at our load flags it returns "no-cache" when the refresh button is pushed.

**Comment by annevk** [comment]
Yeah, the cache mode is what is actually affected here. Nice catch.

**Comment by jakearchibald** [comment]
F2F: https://github.com/slightlyoff/ServiceWorker/issues/875 - we can drop `isReload` if we can get the right information out of `.cache`.

**Comment by slightlyoff** [comment]
Spec is blocked on implementation.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1264175

**Comment by jakearchibald** [comment]
Pre F2F notes: Probably nothing to discuss here.

**Comment by jakearchibald** [comment]
Resolution:

* The cache mode of the request should reflect the browser's intent
* You can use this and the clients API to detect a reload vs navigation to the same resource
* We need to look at `location.reload` and see if we need to spec a "revalidate all subresources" flag on the env settings object

**Comment by jungkees** [comment]
I'd like to check if we're ready to drop this API. It seems Chromium bug for this (https://bugs.chromium.org/p/chromium/issues/detail?id=453190) is still in progress but its blocking issue (https://github.com/whatwg/fetch/issues/39) had been closed.

/cc @mattto @tyoshino @wanderview @jakearchibald @annevk

**Comment by mattto** [comment]
Our bug to drop this is https://bugs.chromium.org/p/chromium/issues/detail?id=652994. We're mostly blocked on implementing Request.cache (https://bugs.chromium.org/p/chromium/issues/detail?id=453190) and gathering usage data for FetchEvent.isReload (https://bugs.chromium.org/p/chromium/issues/detail?id=376039).

I think it's ok for the spec to drop this and Chrome will eventually catch up.

**Comment by jungkees** [comment]
> We need to look at location.reload and see if we need to spec a "revalidate all subresources" flag on the env settings object

Let's move this question to #875.
