### ISSUE TITLE
Property on fetchEvent to indicate the target client

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#874]
The intent is to allow developers to identify a client that will be replaced by a given navigation. The developer will be able to identify a reload by looking at the client id, its url, the request url and the target client id.

**Comment by annevk** [comment]
This will need some careful integration with HTML's navigate algorithm.

**Comment by jungkees** [comment]
With the work done through #870, now we have all of them: the client id, its url, the request url and the target client id. Closing.
