### ISSUE TITLE
Reporting URL for SW update failures

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#877]
Like CSP reporting, something to report update failures to. Probably particular kinds of failures.

**Comment by mkruisselbrink** [comment]
See https://w3c.github.io/reporting/ for a possible generic reporting mechanism we could use for this,

**Comment by jakearchibald** [comment]
F2F:

* Things we might want to report
  * Failed installs
  * Error page served to browser
  * Browser bypassed your SW because it doesn't like it (?)
* Could `respondWith` return something to indicate if fetch accepted the response - but would you have to use `waitUntil` to keep alive for this?
* Could we have a `fetcherror` event which fires if a response returned from fetch was rejected - it would allow you to fall back to default browser behaviour

**Comment by wheresrhys** [comment]
This would be very useful. Is there some reason this could not also trigger an event sent to one/all the current sw clients. My use case is that users with a cookie longer than 4096 bytes get a 400 when requesting our sw (I'm working on a fix for this elsewhere too), and for each of those users I would like an API to detect this and unregister the service worker.

In a similar vein, an interface for handling failed registrations would be useful: am I right in thinking `navigator.serviceWorker.register()` doesn't reject if the request for the service worker fails?

**Comment by jakearchibald** [comment]
> am I right in thinking `navigator.serviceWorker.register()` doesn't reject if the request for the service worker fails?

It'll reject if it's the first call to `register()`, as it's a failure to register. After registration, calling register doesn't trigger updates, so it doesn't reject on update failure.

**Comment by jakearchibald** [comment]
F2F: Lukewarm to this. We can look again if people ask for it.
