### ISSUE TITLE
CORS pre-flight for foreign fetch

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/ServiceWorker#880]
At the F2F the point was brought up if foreign fetch should involve some kind of pre-flight like regular cross origin CORS requests has. This could take the form of extending the `ForeignFetchOptions` dictionary to have additional fields to limit which requests can get intercepted by the foreign fetch service worker, such as allowed methods and headers.

**Comment by mkruisselbrink** [comment]
@wanderview does this sum up your concerns?

**Comment by wanderview** [comment]
Yea, I think some kind of safety belt seems reasonable since I expect many writers of ForeignFetchEvent service workers won't understand all the different types of requests that could be thrown at it.  Having to explicitly opt in to handling POSTs would be good to prevent naive pass-through code accidentally sending posts to the server without CORS protections.

Thanks.

**Comment by annevk** [comment]
I thought the idea was that registering for foreign fetch was sufficient for this. Note that with on the web you can POST without CORS preflight.

**Comment by wanderview** [comment]
In theory yes you are opting in, but I don't think devs will realize all the kinds of things which might get maliciously sent.  I think we should safety belts similar to what cors provides to protect the server.

This could just be implementing cors at this layer which was suggested by Alex.

**Comment by annevk** [comment]
I really don't see why. We already have all those safety belts with the protocol we designed around respondWith(). The preflight only exists because servers might not know about CORS at all. That's not the case for entirely new features.

**Comment by delapuente** [comment]
@wanderview can you explain an example of malicious request where we should use these belts and `respondWith()` protocols are not enough? @annevk , what happen if one of this request reaches the network?

**Comment by annevk** [comment]
@delapuente then it would go through the normal non-foreign-fetch code path, right?

**Comment by delapuente** [comment]
And the usual CORS mechanisms actuated and all is fine. Isn't it?

**Comment by annevk** [comment]
Yeah.

**Comment by wanderview** [comment]
If a site only tests with GET requests and just blanket passes requests through with respondWith(evt.request).  Once they go through the foreign fetch they are considered from the new origin, past the CORS boundary.  If some sends a POST with a dangerous header this naive foreign fetch SW script will send it to server without any pre-flight.

**Comment by delapuente** [comment]
Do you mean this?
```js
self.onforeignfetch = evt => {
  var evilRequest = evt.request;
  evt.respondWith(fetch(evilRequest));
};
```

**Comment by wanderview** [comment]
Essentially yes.

**Comment by annevk** [comment]
@wanderview only if they opted in to handle those things.

**Comment by wanderview** [comment]
> @wanderview only if they opted in to handle those things.

We require a special opt-in to get POST requests, etc?

**Comment by annevk** [comment]
@wanderview I was thinking the foreign fetch registration would have things similar to what preflights take care of. E.g., whether you handle headers outside the "no-cors" range, methods, etc.

**Comment by wanderview** [comment]
> @wanderview I was thinking the foreign fetch registration would have things similar to what preflights take care of. E.g., whether you handle headers outside the "no-cors" range, methods, etc.

That would qualify as an adequate set of safety belts to me.  I thought Salva was asking why we needed safety belts at all.

**Comment by mkruisselbrink** [comment]
So what is being suggested is to change the options passed to `registerForeignFetch` to be something like this?
```idl
dictionary ForeignFetchOptions {
  // existing attributes:
  required sequence<USVString> scopes;
  required sequence<USVString> origin;

  // new attributes:
  sequence<USVString> methods = ["GET", "HEAD", "POST"];
  sequence<USVString> headers = [];
};```

Foreign fetch would then only intercept requests whose method is one of those specified in the options (I don't actually think webidl allows having a non-empty sequence as default value for an attribute though). Requests with other methods would just hit the network.

I'm not entirely sure how headers should behave though. I suppose by default foreign fetch could only intercept requests that only have headers which are CORS-safelisted request headers, and you can specify more headers in the options to intercept more requests.

(for what it's worth, in at least the initial chrome implementation I'm likely going to limit foreign fetch to entirely only intercept requests that would not result in a CORS preflight. So there wouldn't be any way for the service worker to opt-in to more methods and/or headers. This is primarily because doing anything else would require a major refactoring of the way CORS is implemented in chrome).

**Comment by annevk** [comment]
Yeah something like that. I do think we should allow wildcards here. Probably also origin -> origins?

**Comment by mkruisselbrink** [comment]
Yeah, wildcards would make sense. And origin/origins was my typo, it already currently is origins.

**Comment by jakearchibald** [comment]
Closing due to removing foreign fetch.
