### ISSUE TITLE
addAll should resolve when the cache is fully & successfully written

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#884]
At the moment it resolves on headers, which doesn't feel like a good fit for install `waitUntil`.

We changed `.put`, and I think it's an oversight that we didn't fix it for `addAll`. What do you think @wanderview?

**Comment by wanderview** [comment]
I think this is part of removing the incumbent/fetching spec language.  I agree we should not commit addAll() to storage until we have all the bodies.  And we shouldn't remove any previous entries with the same requests until that commit is done.

At least, thats what gecko does now which makes me biased towards it. :-)

**Comment by jakearchibald** [comment]
Pre F2F notes: Probably nothing to discuss unless anyone has changed their minds.
