### ISSUE TITLE
spec exactly how to order non-window Client objects

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#887]
The `Clients.matchAll()` spec requires windows to be ordered so that most recently focused windows come first.  This should also specify how to order non-window Clients.

This could probably as simple as:
- Non-window Client objects are considered to never have been focused so always come at the end.
- If there is a tie in focus ordering, order by creation time

**Comment by jakearchibald** [comment]
Your words are good and I agree with them all.

**Comment by aliams** [comment]
Perhaps even more generally: if there is a tie in ~~focus~~ ordering, order by creation time?

**Comment by jakearchibald** [comment]
Pre F2F notes: Agree on ordering

**Comment by jakearchibald** [comment]
F2F: Wot Ben said.

**Comment by beidson** [comment]
Webkit would prefer ordering *only* on creation time.

Focus time would be much trickier for us, and we're not sure what benefit it would add.

**Comment by aliams** [comment]
I believe it has to do with the fact that the most likely to be picked for focusing or navigating after a notification is clicked would be the window client that was most recently focused.

**Comment by beidson** [comment]
We could easily do:
- Most recently focused window.
- All other windows, ordered by creation time.
- Non-windows, ordered by creation time.

**Comment by jakearchibald** [comment]
I missed these comments during the F2F sorry!

I think the common case is:

```js
// in reaction to a notification click:
clients.matchAll().then(allClients => {
  const client = allClients.find(c => new URL(c.url).pathname == '/chat/');
  if (client) return client.focus();
  return clients.openWindow('/chat/');
});
```

If the user had two `/chat/` tabs open, one of them focused, it'd be weird to take focus from one `/chat/` tab to another. And it seems desirable to focus the most recently used `/chat/` tab, but that's not essential.

I'd be happy if the order was:

* Currently focused window, if any
* Windows
* Non-windows

And add a note to encourage browsers to order the windows & non-windows on relevancy descending.

This would allow browsers to give priority to a visible window on an active desktop etc.

WDYT @beverloo?

**Comment by jakearchibald** [comment]
Resolution:

* You may be looking for the most recently focused "chat" window on your origin, which may not be the most recently focused window, so having all clients ordered by recently focused is useful
* Window clients will continue to be ordered by focus time

**Comment by aliams** [comment]
> You may be looking for the most recently focused "chat" window on your origin, which may not be the most recently focused window, so having all clients ordered by recently focused is useful

Just to clarify, "all clients" do not include non-window clients, correct?

**Comment by jakearchibald** [comment]
Since non-window clients cannot be focused they'll always be at the end of the list. @wanderview's original comment sums it up better than I did.
