### ISSUE TITLE
potential http cache issues with importScripts()

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#894]
Currently the spec says to use RequestCache `reload` when updating the service worker script if its been over 24 hours since the last update check.  I don't however, see anything about bypassing the http cache for files fetched for `importScripts()`.  I think this could lead to http cache coherence problems when loading and evaluating a service worker script thats split across multiple files.

Edit: My statement about the default http cache behavior in gecko was not accurate.

**Comment by jakearchibald** [comment]
Hmm, I agree. We should use the same cache mode for `importScripts` as we do for the service worker script itself.

**Comment by wanderview** [comment]
Maybe this is something chrome is already doing, but I don't think we do it in firefox right now.  Kind of a sharp edge waiting to catch someone.

**Comment by jakearchibald** [comment]
Pre F2F notes: The `reload` behaviour in SW avoids lock-in. We don't need it for `importScripts` requests, since you can cache-bust urls in the SW script, but is this difference a gotcha?

**Comment by jakearchibald** [comment]
F2F:

* If the main script is skipping cache, all imported modules should do the same

**Comment by wanderview** [comment]
Gecko bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1290939

Sounds like chrome already does this.

**Comment by jungkees** [comment]
> If the main script is skipping cache, all imported modules should do the same

I'd like to double-check this behavior. The main script "skipping cache" is different from the main script "changed". I believe the model has been a service worker version holds until the main script itself is changed. In this proposed change, do we want to include all the to-be-imported-scripts for calculating the byte-by-byte match decision for short-circuiting a registration? Then, if an imported script has been changed, will we see this set of scripts as a different service worker version? Advancing to Install in this case seems weird to me.

**Comment by jungkees** [comment]
Note that in the current spec behavior, the imported scripts are served from the cache without hitting the network once the installation is successfully complete for a service worker version.

**Comment by jungkees** [comment]
Sorry. In my previous two comments, I completely missed this history: https://github.com/w3c/ServiceWorker/issues/839#issuecomment-236256162. I'll dig into it again with that context and consensus considered.

**Comment by jungkees** [comment]
Closed by https://github.com/w3c/ServiceWorker/commit/7deb2380a2b8fc327d73636f7c185a22f85f11d5.
