### ISSUE TITLE
Foreign fetch and no-referrer Referrer Policy

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/ServiceWorker#899]
Currently the way foreign fetch is specified, a foreign fetch handler always has access to the requests origin. When a requests referrer policy is `no-referrer` this should probably not be allowed though. Not sure what the best thing to do here would be though:
1. Change `ForeignFetchEvent.origin` to return `"null"` if the referrer policy is `no-referrer`. Which would effectively mean foreign fetch could only reply with opaque responses to these requests (which again means it can only reply to no-cors requests). Or maybe just
2. Don't allow foreign fetch to intercept no-referrer requests at all.

**Comment by mkruisselbrink** [comment]
> Which would effectively mean foreign fetch could only reply with opaque responses to these requests (which again means it can only reply to no-cors requests).

If this is true or not depends on what I do with #900. If I make these checks similar to the ones for CORS (which probably makes sense) and compare serialized origins passing "null" to the response origin will work fine to expose responses to opaque origins.

**Comment by annevk** [comment]
I think what we actually want here is that "no-cors" does not expose origin ever, but "cors" always does. That would be analogous to the network situation, except maybe for some navigations in Chrome.

See https://github.com/whatwg/xhr/issues/31 for some issues surrounding origin in the Fetch Standard.

**Comment by mkruisselbrink** [comment]
Hmm, yeah. Aligning with when and how the Origin header gets emitted probably makes sense. Although it does seem surprising to me that it seems that header gets emitted even for no-referrer requests? Doesn't that kind of defeat the purpose of having both `no-referrer` and `origin` referrer policies, as the origin will pretty much always be exposed anyway?

Also not sure when the fetch standard actually decides not to emit the Origin header. As far as I can tell this is only done for a select few situations in the HTML spec (for downloads, plugins, and app-cache manifests or something like that)?

**Comment by annevk** [comment]
Fetch is broken with respect to the Origin header per that issue and those linked from it.

I don't think the Referrer Policy specification should break CORS. If it does, that would be a bigger issue that needs to be addressed separately and would only then impact Foreign Fetch.

**Comment by annevk** [comment]
Note https://github.com/whatwg/fetch/issues/225 on the `Origin` header. If you have insights as to what Chrome does, they're welcome. Once we settle that we should just align this field with that, imo, and I still think putting it on `Request` makes sense.

**Comment by jakearchibald** [comment]
Closing due to foreign fetch being removed.
