### ISSUE TITLE
should UA check for updates on navigate when there is no fetch event?

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#905]
Currently we trigger updates for events fired at the SW.  In particular, navigates always trigger updates.

Now that we allow the browser to avoid firing fetch events if there is no fetch handler, should the update still be triggered?

Per the spec, I think the answer is no.  I think for dev UX, though, we should still trigger updates.  It would be nice to be consistent across browsers here.

**Comment by mattto** [comment]
The Chrome implementation at https://bugs.chromium.org/p/chromium/issues/detail?id=605844 triggers update.

**Comment by jakearchibald** [comment]
Agree that we should trigger update on navigate within scope regardless of fetch event.

**Comment by jakearchibald** [comment]
F2F: Yes.

**Comment by slightlyoff** [comment]
LGTM.
