### ISSUE TITLE
Should WindowClient.navigate(url) navigate with "replacement enabled"?

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/ServiceWorker#918]
Currently the `navigate(url)` method is specified as navigating [with replacement enabled](https://html.spec.whatwg.org/multipage/browsers.html#replacement-enabled). Is that correct? I wonder if that was just a mistaken copy of the text from `openWindow` (where it probably is correct to navigate with replacement enabled).

**Comment by annevk** [comment]
That does not seem correct indeed. For `openWindow()` it is correct since you want to replace the initial about:blank.

**Comment by NekR** [comment]
Does anyone vendor already implements it with replacement enabled?

**Comment by wanderview** [comment]
We're still working on it for gecko here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1218148

Looking at the current patches we are not using replacement.

**Comment by aliams** [comment]
I agree: it makes more sense to _not_ use replacement for `navigate()`.

**Comment by jakearchibald** [comment]
Pre F2F notes: Absolutely seems like a copy-paste error on my part.

**Comment by jakearchibald** [comment]
F2F: Jake's an idiot and made a copy-paste error. This shouldn't be a replace.
