### ISSUE TITLE
Eliminate usage of entry and incumbent settings objects

### ISSUE THREAD

**Issue by domenic** [w3c/ServiceWorker#922]
See https://readable-email.org/list/public-script-coord/topic/multiple-globals-and-you. We'd like to stop using these in new specs. In addition, it seems to be the case that most places that use them, are not actually implemented that way in browsers.

It would be good to do an audit of this spec and see which globals are actually implemented in browsers, then update the spec to use those. In the rare cases where incumbent and entry are actually implemented as specced, it would be ideal to change implementations if possible.

For an example of how you can test implementations, see e.g. https://github.com/whatwg/html/pull/1472 and https://github.com/whatwg/html/pull/1473

**Comment by jungkees** [comment]
I'd need to check them thoroughly but presume many of them actually implemented entry and incumbent. I changed `navigator.serviceWorker.register(url)` and `navigator.serviceWorker.getRegistration(url)` to use entry for parsing url at least.

For that change, I was referencing the example code in https://www.w3.org/TR/2016/WD-html51-20160503/webappapis.html#calling-scripts section the corresponding part of which in WHATWG version is now replaced with your recent patches that clarify those concepts.

Having tried the example code with `location.assign()`, it turned out Chrome and IE (didn't try with Edge yet) use entry for parsing the url and Firefox uses current. (I saw you filed the `Location` object behavior in https://github.com/whatwg/html/issues/1431)

To sort them out in SW spec, I'd want to check once again if the goal is to make them all use current instead of entry and incumbent for both parsing urls and security checks? And don't we need any implementer/developer feedback on the behavior change? (I agree we should sort them out sooner than later but somewhat worry about the impact.)

**Comment by domenic** [comment]
> To sort them out in SW spec, I'd want to check once again if the goal is to make them all use current instead of entry and incumbent for both parsing urls and security checks?

Sometimes it may be more appropriate to use relevant. Boris has argued that for URL parsing in particular that is better. (Note that inside constructors, the relevant settings object of the object being created _is_ the current settings object, so we just use the latter.)

> And don't we need any implementer/developer feedback on the behavior change?

So far in this multi-globals work, it seems to not impact developers at all, since they mostly don't do weird multi-global things on purpose. Implementers have been largely indifferent as well, apart from the fact that only Firefox seems to have a perfectly-to-spec version of entry and incumbent.

I think the way to proceed is to perform some tests and come up with a comprehensive plan for changing everything to current or relevant. Then we can see how well that matches existing service worker implementations. In the best case, it just aligns with implementations better, so the implementers don't care. In the worst case, both implementations have already done incumbent or entry, so this would be a change for them. If that's true then we should bring it up with implementers, and possibly not make the change.

So I guess the first step is to write up tests for all the different uses.

**Comment by domenic** [comment]
I've verified by code inspection that Chrome and Firefox seem to agree on the various places that this spec and fetch use "entry", documented in https://github.com/whatwg/html/issues/1431. Most of them are around URL parsing.

I think it would be ideal if implementers were willing to coordinate on a switch to the relevant settings object of the object on which the method is being called (or the current settings object in the case of constructors). This might require use counters if people think this change is risky; it seems very unlikely to be risky to me given how few developers do these sort of multi-global things, but maybe it's better to be safe than sorry. /cc @wanderview @mattto 

What would be a good next step here? Would writing up a spec PR with the changes I propose be a good way to concretize this?

**Comment by jungkees** [comment]
I'd like to get feedback from @wanderview and @matto if they're willing to change. It seems SW and window.open() are the ones that have been implemented using entry as spec'd. I'm into this change as the goal is to minimize the use of entry concept. I also believe it'd be better to make other instances (e.g. window.open()) consistent with the base rule if the change is not risky. If the implementers agree, I can update the spec.

**Comment by jungkees** [comment]
@wanderview, `navigator.serviceWorker.getRegistration(clientURL)` in FF uses something like "incumbent's parent" rather than "entry" to parse the URL. Can you check whether it's a bug?

**Comment by mattto** [comment]
What does entry and incumbent mean in easy-to-understand language?

**Comment by jungkees** [comment]
Entry is enteredExecutionContext() in Blink. I'm not sure what the corresponding function to get the incumbent context in Blink. /cc @jeisinger

Entry: https://html.spec.whatwg.org/multipage/webappapis.html#concept-entry-everything
Incumbent: https://html.spec.whatwg.org/multipage/webappapis.html#concept-incumbent-everything
The example in https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects seems the most intuitive explanation I guess.

**Comment by mattto** [comment]
Thanks. Maybe the best way forward is to write the WPTs that would be affected by the change, and then see what the current implementations do and whether we expect the changes to be risky.

Looking at the spec, the things that would be affected are:
- ExtendableMessageEvent and ServiceWorkerMessageEvent's .origin and .source
- navigate(url) and openWindow(url)
- registerForeignFetch's scope
?

**Comment by wanderview** [comment]
+1 to seeing the wpt test changes.

**Comment by domenic** [comment]
Awesome, thanks for being willing to work with us on this. I'll take the action item to write up some web platform tests.

**Comment by mkruisselbrink** [comment]
> registerForeignFetch's scope ?

This one shouldn't really be effected since it's only callable from within a service worker, so there isn't more than one global you can reach that has that method. Also should be easy to change anyway since it hasn't shipped yet of course.

Similar I don't think there are any issues around navigate(url) and openWindow(url), as both of these methods are similarly only exposed within service workers, where as far as I can tell all four settings objects would always be the same.

**Comment by jeisinger** [comment]
Note that enteredExecutionContext returns the entry context, or the current context... so it's kinda random.

In fact, we don't have an entered context during microtask execution, so if you try to invoke ServiceWorkerContainer.register in a promise handler you'll get different semantics compared to when running it in a regular task :-/

**Comment by domenic** [comment]
> In fact, we don't have an entered context during microtask execution

That's https://github.com/whatwg/html/issues/1426 FYI

**Comment by jakearchibald** [comment]
This feels like v1, but feel free to change it.

**Comment by jakearchibald** [comment]
Pre F2F notes: Doesn't feel like there's much to discuss here. Just work to do.

**Comment by slightlyoff** [comment]
Is this really v1?

**Comment by annevk** [comment]
It affects all impl, so yes?

**Comment by domenic** [comment]
Spending a bit more time on this.

### Entry

URL parsing would change:

- ServiceWorkerContainer.prototype.register
- ServiceWorkerContainer.prototype.getRegistration

No affect, since multiple globals cannot be present inside a service worker and these are only exposed there:

- Client.prototype.navigate
- Clients.prototype.openWindow
- InstallEvent.prototype.registerForeignFetch

### Incumbent

No affect, since multiple globals cannot be present inside a service worker and these are only exposed there:

- Client.prototype.navigate
- InstallEvent.prototype.registerForeignFetch

### postMessage (special case)

- For ServiceWorker.prototype.postMessage, we need to align with the changes in https://github.com/whatwg/html/pull/1573, which make the incumbent global the only one. There were some follow-up editorial changes in https://github.com/whatwg/html/pull/1584 and https://github.com/whatwg/html/pull/1586 which are worth copying too.
- For Client.prototype.postMessage, we can get rid of incumbent/entry since there cannot be multiple globals present

### Todo:

- I will submit a pull request cleaning up all usages that have no normative effect, and aligning postMessage with HTML's
- I will then work on web platform tests for the two URL parsing changes, and also probably for the postMessage alignment

**Comment by domenic** [comment]
OK, here's the web platform tests for the three URL parsing cases that remain: https://github.com/w3c/web-platform-tests/pull/3449

As you can see this requires some esoteric contortions to actually come up in practice.

(They are written to demand relevant, which I think is more correct, so they will fail in Chrome and Firefox.)

**Comment by jungkees** [comment]
b546c24c6fba8d91dc74661de8ff15693ba7c9d4 has been backported to V1: 1d7f4975895aa9fa5f22a14e093b67df5e527396

**Comment by domenic** [comment]
As noted above, I uploaded the web platform tests. Have people had a chance to review them, and hopefully agree with me that the change is doable? Is there anything else we can do to move this issue forward?

**Comment by mattto** [comment]
Thanks for the tests. I agree this change is unlikely to break sites, and it makes sense. I'm willing to change Chrome implementation to conform to these tests.

**Comment by wanderview** [comment]
Works for me.  Sorry for the delay in responding.  (I really wish there was a need-info system in github.)

Gecko bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1298819

@domenic are you going to land the tests in the WPT repo?  Or we can import them and uplift to WPT when we make the code changes.  Not sure on time frame, though.

**Comment by domenic** [comment]
@wanderview I guess I should get a reviewer to sign off on the tests? But they're ready to land if so.

If people haven't seen, I also sent a spec PR: https://github.com/w3c/ServiceWorker/pull/963

**Comment by domenic** [comment]
Can someone sign-off on the corresponding tests PR at https://github.com/w3c/web-platform-tests/pull/3449 ?

**Comment by domenic** [comment]
Tests merged to WPT; I also filed a Chrome issue at https://bugs.chromium.org/p/chromium/issues/detail?id=691008.

**Comment by domenic** [comment]
Also filed an Edge issue for good measure, although I don't know if they implemented the old spec or new spec: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10902802/
