### ISSUE TITLE
Does accessing ExtendableEvent's extend lifetime promises race?

### ISSUE THREAD

**Issue by jungkees** [w3c/ServiceWorker#931]
@annevk pointed out there can be a race in accessing ExtendableEvent’s extend lifetime promises:
https://github.com/slightlyoff/ServiceWorker/commit/72315b913d8f2b0f639b668056f2f58275e7abd2#commitcomment-18283685

I think it's a fair point as now `e.waitUntil(f)` can be called async.

**Comment by jakearchibald** [comment]
Feels like `Set <var>extendLifetimePromises</var> to a copy of` should go before the parallel steps, but `If the length of <var>extendLifetimePromises</var> does not equal` also needs to be in the service worker thread, so I guess a task needs to be queued for that?

**Comment by jakearchibald** [comment]
F2F:

* `Set <var>extendLifetimePromises</var> to a copy of` happening before parallel doesn't seem to be an issue, since it's only ever going to be more promises, which we want to catch
* We need to look at the spec language for "waiting for all" to see if it queues a microtask

**Comment by jungkees** [comment]
Having discussed with @annevk, I will first have to move the "When dispatching an event e that uses the ExtendableEvent interface" steps to right after the actual (dispatching) actions. I'll define some general wrapper that dispatches the event and run these steps, and make it invoked from Handle Fetch and Handle Functional Events.

The OP still should be addressed here.

**Comment by jungkees** [comment]
@domenic suggested we use a reference count approach over the current promise-copying-and-checking one. Will try to come up with it.

**Comment by jungkees** [comment]
Addressed https://github.com/w3c/ServiceWorker/issues/931#issuecomment-248233338: https://github.com/w3c/ServiceWorker/commit/c2a518b3b01dd77ad0d0b47b6eeff54b6cd34ba7.

TODO: https://github.com/w3c/ServiceWorker/issues/931#issuecomment-248570852.
