### ISSUE TITLE
should async waitUntil() work in .then() handler of promise passed to previous waitUntil()?

### ISSUE THREAD

**Issue by wanderview** [w3c/ServiceWorker#935]
I'm currently implementing async `waitUntil()` in gecko.  The main intention here is to allow things like:

```
addEventListener('fetch', e => {
  e.respondWith(fetch(e.request)).then(response => {
    e.waitUntil(caches.open('db').then(cache => {
      return cache.put(e.request, response);
    });
    return response.clone();
  });
});
```

So you can call `waitUntil()` as long as there is an extension promise still unsettled.

But what about this non-idiomatic code:

```
addEventListener('fetch', e => {
  let respondWithPromise = fetch(e.request);
  respondWithPromise.then(response => {
    let clone = response.clone();
    e.waitUntil(caches.open('db').then(cache => {
      return cache.put(e.request, clone);
    });
  });
  e.respondWith(respondWithPromise);
});
```

Here pass the `fetch()` promise directly to `respondWith()`.  Or additional caching code is also hung off this same `fetch()` promise.

Technically when the caching code runs the promise passed to `respondWith()` is settled, but if order of promise handlers is maintained then the `respondWith()` code has not been notified yet.

I _think_ this should probably work, but the spec text is a bit vague.  It says:

> Wait until the result of waiting for all of extendLifetimePromises settles. 

Does that respect ordering of promise handlers?

Conversely, if we call `respondWith()` before the `respondWithPromise.then()` above, then I think the `waitUntil` should throw.  The respondWith code would clear the extensions allowed flag before the caching code had a chance to run.

All this is corner casey, but I thought it would be good to clarify.

**Comment by wanderview** [comment]
I guess the "waiting for all" here:

> Wait until the result of waiting for all of extendLifetimePromises settles. 

Explicitly links to the Promise.all() algorithm.  So I guess this is defined and this should work:

```
addEventListener('fetch', e => {
  let respondWithPromise = fetch(e.request);
  respondWithPromise.then(response => {
    let clone = response.clone();
    e.waitUntil(caches.open('db').then(cache => {
      return cache.put(e.request, clone);
    });
  });
  e.respondWith(respondWithPromise);
});
```

But this would trigger a throwing waitUntil():

```
addEventListener('fetch', e => {
  let respondWithPromise = fetch(e.request);
  e.respondWith(respondWithPromise);
  respondWithPromise.then(response => {
    let clone = response.clone();
    e.waitUntil(caches.open('db').then(cache => {
      return cache.put(e.request, clone);
    });
  });
});
```

This is fine with me since its clearly defined.  Jake did suggest in person, though, that maybe we should wait a micro task turn to allow both of these cases to work.  Thoughts?

**Comment by jakearchibald** [comment]
F2F:

* We should queue a microtask so that calls to `waitUntil` in promise handlers passed to `waitUntil` extend the lifetime of the event

**Comment by slightlyoff** [comment]
Sounds like this is decided?

**Comment by jakearchibald** [comment]
Yep, I'm going to go through all the issues post F2F and make sure they're tagged properly and carry additional actions out

**Comment by jungkees** [comment]
Dupe of https://github.com/w3c/ServiceWorker/issues/1039.

**Comment by jungkees** [comment]
Closed by https://github.com/w3c/ServiceWorker/commit/6c1f3fe31a976652d1ac4c48d7f0764ff8d63b58.
