### ISSUE TITLE
Block 206s entering the cache (via put & addAll)

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#937]
Right now it seems like this would only happen by accident (passthrough caching), and it's something we can open up later if we need to.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1264181

**Comment by inexorabletash** [comment]
Blink bug: https://bugs.chromium.org/p/chromium/issues/detail?id=633338

**Comment by ricea** [comment]
Shouldn't 416 "Requested Range Not Satisfiable." also be blocked?

**Comment by jungkees** [comment]
Just made a PR for this.

I didn't include 416 in the PR. Currently, addAll() filters out 416 while put() doesn't. Should we add 416 to put()?

/cc @jakearchibald, @wanderview

**Comment by jakearchibald** [comment]
I think 416 is fine for the same reasons 404 is fine. The danger of 206 is it's an 'ok' response that likely only represents part of what the developer expects.

Also, by not-allowing 206 we can potentially add range coalescing behaviour in future.

**Comment by jungkees** [comment]
Sounds good. I'll merge #1210.

**Comment by jungkees** [comment]
We have tests for this: https://github.com/w3c/web-platform-tests/blob/master/service-workers/cache-storage/script-tests/cache-add.js#L86.
