### ISSUE TITLE
Send correct Accept header with fetch() request

### ISSUE THREAD

**Issue by plegner** [w3c/ServiceWorker#945]
We currently use the `Accept` header to determine if a browser supports WebP, and to change our response on the server. However, fetch() requests always send `'*/*'` by default, so our implementation would fail.

Of course, we could manually override the `Accept` header as `fetch(url, {headers: {Accept: 'img/webp'}})`, however client side WebP detection is quite clunky (and we might also need some other parts of the `Accept` header).

Similarly, we could save the original `Accept` header to a cookie or session variable and use it as fallback, but this behaviour seems quite fragile and hacky.

Is there/will there be a way to send all default browser request headers with `fetch()`?

**Comment by wanderview** [comment]
Are you doing a pass through in your service worker?  Something like:

```
e.respondWith(fetch(e.request))`
```

If so, then I think the original request header should be preserved.  Is that not happening for you?

**Comment by plegner** [comment]
No, we're precaching urls directly, using `fetch('/abc', {...})`. I tried `fetch(new Request('/abc'))` with the same problem.

**Comment by mkruisselbrink** [comment]
So the problem here could be that the fetch API and/or Request constructor don't allow you to set the "type" of a request. Not sure what would break if we would allow the type to be set directly (presumably you'd want to set it to "image" in this case).

But this also seems like a fetch issue, and not a service worker issue. So probably should re-file this issue at https://github.com/whatwg/fetch/issues

**Comment by wanderview** [comment]
Ok.  That makes sense then.

I think in these cases you need to set the Accept header explicitly.  The browser doesn't really have any way to determine what it should be.  We could try to parse the URL for the file extension, but that would be kind of error prone.

**Comment by mkruisselbrink** [comment]
And actually even fetch(e.request) would not work to preserve the type of the request, as fetch() calls the Request constructor to clone the request, which ends up clearing out the type of the request.

**Comment by plegner** [comment]
Thanks!

**Comment by jakearchibald** [comment]
`fetch(e.request)` will work if the headers have already been set.

But yeah, it'd be nice to have an API that does the same as the `as` attribute on `link[rel=preload]`.

**Comment by jakearchibald** [comment]
Moved to https://github.com/whatwg/fetch/issues/521
