### ISSUE TITLE
Declarative url filters in `fetch` event

### ISSUE THREAD

**Issue by NekR** [w3c/ServiceWorker#949]
I'm thinking about this, possible optimization (inspired by Chrome Extensions [1]):

```js
self.addEventListener('fetch', (e) => {
  // ...
}, {
  url: [
    { pathPrefix: '/assets/' }
  ]
})
```

Taking in account that you already want potentially optimize for HTTP 2 (https://github.com/slightlyoff/ServiceWorker/issues/756), this could be also possible optimization. In case of such declarative filters, SW instance will be spawned only if route matches definition. In the code above, SW will be spawned only for router with path which starts with `/assets/` and won't be spawned from routes such as `/api/*` which potentially are requested more often than `/assets/` routes.

[1] [Filtered events](https://developer.chrome.com/extensions/events#filtered)

**Comment by NekR** [comment]
Any thoughts? I understand that it's harder than traditional declarative filters, e.g. some may conditionally add and remove `fetch` handlers with different filters, but it would be good to discuss this at least.

**Comment by jakearchibald** [comment]
There's a lot of discussion around this type of thing over at https://github.com/slightlyoff/ServiceWorker/issues/920#issuecomment-229016073

It's not something we're looking to do until we have a better picture of the performance problem.

**Comment by NekR** [comment]
I see, thanks for the info.

**Comment by NekR** [comment]
Yeah, if you think so.
