### ISSUE TITLE
notification of cancelled download?

### ISSUE THREAD

**Issue by Spongman** [w3c/ServiceWorker#957]
If a ServiceWorker's 'fetch' event responds with a Response with a `'Content-Disposition': 'attachment; filename=blah'` header, the browser starts a download.

Is there any way for the ServiceWorker to know if/when the user cancels the download (in the `chrome://downloads/` window)?

I would have expected the `cancel(reason)` method of the `Response` stream's underlyingSource to be called. But in Chrome v52.0.2743.116, it's not.

**Comment by wanderview** [comment]
Maybe with ReadableStream?  You could interpose a js monitor and observe if the stream is closed before its fully read.  The browser may read ahead and buffer though.

**Comment by piersh** [comment]
I'm passing a ReadableStream into the Response's constructor. The stream's underlyingSource has a 'cancel' method, but that is never called. Also, i can call controller.enqueue without error after the download is cancelled.

**Comment by domenic** [comment]
That just sounds like a bug in Chrome to me... /cc @yutakahirano

**Comment by yutakahirano** [comment]
Thank you for reporting, I filed [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=638494).

**Comment by Spongman** [comment]
Thanks. I think it's fantastic that Chromium even handles this at all (I didn't see anything about attachments in the SW spec, though). IMHO being able to completely customize how the browser does downloads is a game-changer for us: we're using it to concurrently stream chunks of multiple huge, CDN-hosted files directly into a client-side archive.

**Comment by jakearchibald** [comment]
Eventually we'll also have a cancel token on the fetch event to signal a cancellation of the request.

**Comment by Spongman** [comment]
why was this closed? is this fixed?

**Comment by Spongman** [comment]
did anything happen with this, or did it just get swept under the rug?

**Comment by jakearchibald** [comment]
Nothing's been swept under the rug. Read the comments above.

This tracker is for spec issues, but what you identified was a Chrome bug. A ticket to the Chrome bug was posted above, and this issue was closed because there's no change to the spec needed.
