### ISSUE TITLE
CacheStorage has an associated global object?

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#964]
https://w3c.github.io/ServiceWorker/spec/service_worker/index.html#cache-storage-interface did not make much sense to me. And is the only bikeshed linking error left.

**Comment by jungkees** [comment]
Yes, it has the associated global object.

> "The user agent must create a CacheStorage object when a Window object or a WorkerGlobalScope object is created and associate it with that object."

**Comment by annevk** [comment]
So `window.open()` would create a new object? (Although I guess we're trying to remove that.)

Not sure the sentence makes sense with that clarified, but I guess it might work...

**Comment by jungkees** [comment]
> So window.open() would create a new object?

It depends on whether a new target browsing context is created or a navigation to a resource happens. That is, basically when a new Window object is created, a new CacheStorage object is created.

I could also do s/associated global object’s environment settings object/relevant settings object/, but think it'd make more sense to leave the object creation sentence. WDYT?

**Comment by annevk** [comment]
I'm not sure. I think ideally we a list somewhere at some point of all the objects that are created together with global or document object. Just make the whole setup more explicit. (And of course, implementations would likely create them lazily.)

**Comment by jungkees** [comment]
That sounds a good idea though it'll need some maintenance when new features are added. For now, I'd want to stay with the current language. Can I close?

**Comment by annevk** [comment]
I think what might help is the addition of `<dfn for=CacheStorage>global object</dfn>` to make it clear that is an internal slot of CacheStorage.

**Comment by jungkees** [comment]
That sounds good. I'll add it.
