### ISSUE TITLE
Lots of bikeshed usage issues

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#965]
All 702 instances of `<a href="#dfn-` are an issue of sorts  and would be better if they were expressed correctly without `href`. If you cannot correctly identify the term you want to use internally, it kinda follows that the external interface (when exporting terms at all) is not ideal either.

**Comment by mkruisselbrink** [comment]
These are mostly a leftover of not wanting to make the bikeshed conversion more involved than it already was. But I agree that it would be ideal if the vast majority of these would be replaced with auto-linking links.

**Comment by annevk** [comment]
More:

* ASCII case-insensitive is now only defined by Infra, not DOM
* Lots of variables that need to be annotated with the ignore attribute
* I don't understand for=resource for the term origin
* None of the Fetch Standard terms should be in "anchors"

**Comment by annevk** [comment]
I fixed a simple one in #1008.

**Comment by jakearchibald** [comment]
I'm going to tackle this - about time I learned the ins & outs of bikeshed.

**Comment by jungkees** [comment]
@jakearchibald, sounds great. One thing I'd like to note is while I was trying to resolve bikeshed linking errors, I removed/changed some of the dfn IDs (in this commit: https://github.com/w3c/ServiceWorker/commit/2e802220d13cbea559cbdfa6265162aff1b5a14b). Removing the IDs was mostly around the dfns for IDL attributes and methods, which I thought was needed to use {{Interface/attribute}} notation to reference with. (Not sure whether dropping the IDs wouldn't have been required though.) Changing the IDs was for improving naming consistency, but I think it was not a good idea. Sorry for the confusion. I'll definitely help this cleanup. It seems not breaking the existing urls should be one of the important rules that we should have in mind. Let's sort this out together!

**Comment by jakearchibald** [comment]
@jungkees yeah, I'm preserving all the IDs that are there now for linking

**Comment by tabatkins** [comment]
IDs don't matter; if they're missing, Bikeshed generates them for you, but otherwise it's completely indifferent as to what the ID is. Definitely ideal to keep the existing IDs if they differ from the auto-gen patterns.

Definitely ping me if y'all have any questions about Bikeshed, or if the documention is lacking - I'd love to improve it further with more real-world feedback!

**Comment by jakearchibald** [comment]
I think we're good here following https://github.com/w3c/ServiceWorker/pull/1014 right?
