### ISSUE TITLE
Serve subfolder to gh-pages

### ISSUE THREAD

**Issue by jakearchibald** [w3c/ServiceWorker#966]
I believe github now lets you serve a folder within master to GitHub pages. This means https://w3c.github.io/ServiceWorker/ can point to the spec, and we don't need to maintain a seperate branch.

We should set up a meta redirect for the old url.

**Comment by jungkees** [comment]
I agree to maintain only master. @siusin, I don't think I have a permission to change the settings. Can I have the permission? Or could you help?

Re the spec urls, we still need both https://w3c.github.io/ServiceWorker/spec/service_worker/ and https://w3c.github.io/ServiceWorker/spec/service_worker_1/ ?

**Comment by ylafon** [comment]
The master branch is now what is used for the GH pages, however seems that the only folder that can be selected is /docs (which is not existent), so the best would be to add a small index.html (See PR #973)

**Comment by jakearchibald** [comment]
Ok, I've moved the spec into the docs folder. @ylafon can you make github serve the docs folder?

@jungkees the specs are now in `/docs` - let me know if I've broken everything.

I've set up redirects, but once we're serving from docs, I need to:

* Delete `/index.html`
* Delete `/spec/service_worker/index.html`
* Delete `/nightly/index.html`

**Comment by ylafon** [comment]
@jakearchibald the repo is now setup to serve /docs in master.

**Comment by jakearchibald** [comment]
https://w3c.github.io/ServiceWorker/ whooo!!

Right, I'll do the last couple of link changes and deletions. Thank you @ylafon!

Can you update the link at the top of https://github.com/w3c/ServiceWorker/? For some reason I've never been trusted with those keys.

**Comment by ylafon** [comment]
done as well.

**Comment by jungkees** [comment]
> @jungkees the specs are now in /docs, the nightly is at the root, v1 is in the v1 folder - let me know if I've broken everything.

@jakearchibald, I'm fine with this change.

> Right, I'll do the last couple of link changes and deletions.

Please.

**Comment by jakearchibald** [comment]
All done then!
