### ISSUE TITLE
Add URL to GitHub repo

### ISSUE THREAD

**Issue by annevk** [w3c/ServiceWorker#967]
Someone please edit https://github.com/w3c/ServiceWorker to link to the specification. In particular the bit that says "The Service Worker Specification" can also contain a URL which should point to https://w3c.github.io/ServiceWorker/spec/service_worker/.

**Comment by annevk** [comment]
See https://github.com/whatwg/fetch for an example.

**Comment by sideshowbarker** [comment]
Added
