### ISSUE TITLE
SW for multilingual website

### ISSUE THREAD

**Issue by vigneshshanmugam** [w3c/ServiceWorker#968]
Apologies if this issue is already discussed before. 

If you have a service worker registered to `/cart`, It then controls all the requests to `/cart/*`. 

But for multilingual website  `/cart` scope holds true only for the English version, the same url is named differently according to the regional context. The scope here wont match with the registered service worker scope.

The domains might also be different in this case depending on the region. Yes, you could always proxy and respond it with 302 to the valid scope. 

I am really interested how SW behaves in these scenario's and whats the best way to deploy SW here.

**Comment by jakearchibald** [comment]
You would need a scope of / to be able to control both of those URLs with the same SW.

SWs can only control a single origin, although foreign-fetch allows some cross-origin request control.

If you're using different origins for different regions, remember they will also have different localstorage, indexeddb etc etc.

**Comment by jakearchibald** [comment]
(closed because this doesn't appear to be a spec issue, but happy to continue to provide support)

**Comment by vigneshshanmugam** [comment]
@jakearchibald Thanks for the explanation. 

Does that mean, I need to have SW for each origin and register it with `/` scope?. 

As I mentioned, if we do a 302 to a particular scope - How will SW behave in this case.
