### ISSUE TITLE
Chrome API unavailable in ServiceWorker

### ISSUE THREAD

**Issue by shlatchz** [w3c/ServiceWorker#969]
Hello,

I'm building a Chrome OS App, and my app uses a Service Worker.
In my Service Worker, I'm trying to call [chrome.storage](https://developer.chrome.com/extensions/storage) and it is unavailable.

Should I configure something special when I register the Service Worker from my `background.js` file?
Maybe it has to do with the service worker scope?

Thanks!

**Comment by tabatkins** [comment]
No, I suspect it's simply not available. Please file a bug on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list), as this isn't directly Service Worker related.
