### ISSUE TITLE
Provide a simple synchronous k-v storage for ServiceWorker?

### ISSUE THREAD

**Issue by upsuper** [w3c/ServiceWorker#981]
It seems to me the only storage currently exists in ServiceWorker is Cache, which is designed for storing request-response pair.

However, sometimes the worker may just want to store some simple data in a key-value storage which can be read/write synchronously (like `localStorage` in page), rather than an asynchronous request cache.

Some possible usecases like:

1. store a revision number and use it to check whether the cache is stale;
2. cache submitted data when offline;
3. do adjustment on data from server and cache the result.

A key-value storage can be simulated with Cache, but it would be great if it is provided natively.

**Comment by annevk** [comment]
Use IDB? We don't really want new sync storage APIs.

**Comment by upsuper** [comment]
Because physical IO may block script? Or for synchronization between callers? If the later, I guess the storage can be made only accessible from the current Service Worker?

IDB sounds too heavy for many cases, but it may make sense to expose that in SW... I still hope there could be a simple kv storage like Web Storage API.

**Comment by ykahlon** [comment]
I also agree that IDB is too complicated for simple k-v storage. I think that an asyn k-v storage would be the best solution here.  It is something in between IDB and localstorage

**Comment by asutherland** [comment]
@inexorabletash of IndexedDB fame has proposed a Promise-based transaction-less lighter-weight IndexedDB API at https://gist.github.com/inexorabletash/280016e79188b6a28247 that's very much worth looking at.  See https://github.com/w3c/IndexedDB/issues/91 for discussion and other proposals.

Arguably it would be ideal for IndexedDB to gain such an interface rather than add another storage subsystem or increase dependencies on existing storage systems with downsides like localstorage (all per-origin stored data is loaded into memory at a per-origin granularity and stays there until the pages go away) or cookies (all stored data may be present in memory at all times).

**Comment by jakearchibald** [comment]
@upsuper @ykahlon have you seen https://www.npmjs.com/package/idb-keyval?

**Comment by upsuper** [comment]
1. IDB ks currently not available in Service Workers.
2. I don't think something being doable via a library is a good reason against adding it to the standard in general.

**Comment by jakearchibald** [comment]
@upsuper IDB is definately available in service workers.

I agree with 2 in general, but we're talking < 500 bytes here.

**Comment by bsittler** [comment]
Why is synchronous calling desirable? Is this something that `await` solves
already, or at least will solve once IDB exposes promises?

**Comment by upsuper** [comment]
OK, given `await` is coming, I agree that being synchronous isn't that important. And OK, I wasn't aware that IDB is available in Service Workers, so given there is that, it's probably fine.

(I personally wouldn't choose IDB for my case... I feel that it is probably easier to write a wrapper around Cache API to provide k-v storage, actually. I'm just not a fan of using external libs :)

> I agree with 2 in general, but we're talking < 500 bytes here.

Many things added in standards can be implemented with even fewer bytes.

For example, the recent added (and implemented) `once` option for `EventTarget.addEventListener` can actually be implemented in a four line JavaScript function, but I still think adding that to the spec is a good thing, because that makes me no longer need to care about importing a right util module or writing that function every time when I need it.

@asutherland The lite IDB looks easier to use, though I might probably still argue it is more complicated than a k-v storage for e.g. having store object and index. I have no idea where the trade-off between easy to use and powerful enough should be.

**Comment by wanderview** [comment]
Note, you should be similarly concerned about blocking the js event loop in service workers just like you are on the main thread.  While it won't jank graphics, it can jank network requests slowing your time-to-load.
