### ISSUE TITLE
registerForeignFetch({ origins, scope }) optional

### ISSUE THREAD

**Issue by DanielHerr** [w3c/ServiceWorker#982]
The foreign fetch scopes and origins should be optional. This wouldnt be a security concern because the SW is already explicitly intending to handle foreign fetches.

**Comment by jakearchibald** [comment]
I'm in favour of removing this part of the API. As you say, it's explicit in the event handler, and adding an additional level of scoping seems confusing.

@mkruisselbrink - am I missing something about this API?

**Comment by annevk** [comment]
Well, we wanted to keep the model that CORS has around to some extent. CORS requires an origin.

**Comment by jakearchibald** [comment]
You already have to provide the origin in the response. It kinda feels redundant in `registerForeignFetch`.

**Comment by annevk** [comment]
Although currently origin is not required there, I guess that's a bug. Agreed that it could have a sensible default here.

**Comment by jakearchibald** [comment]
If you don't provide an origin, the returned response is always opaque.

**Comment by jakearchibald** [comment]
Closing due to removing foreign fetch.
