### ISSUE TITLE
Make Service Worker control only specific pages

### ISSUE THREAD

**Issue by inian** [w3c/ServiceWorker#985]
My use case is to have service workers intercept fetch requests only from a few specific pages. Right now, the only way to control which fetch requests the service worker controls is via the scope parameter via registration, but that is not granular enough. 

It would be great if I could mention which pages the SW should control on registration.

**Comment by NekR** [comment]
@inian you can just don't handle requests if you don't need them.

**Comment by inian** [comment]
Is there an easy way from a fetch event to identify the page making the request? For example, I want to intercept sub-resources from /page1.html and /page3.html but not from /page2.html. What would be the easiest way to go about doing this?

**Comment by lmj0011** [comment]
you could try placing `/page1.html` and  `/page3.html` in a directory (eg. `/static/`) and set the SW scope to that folder.

**Comment by jakearchibald** [comment]
@inian `fetchEvent.clientId` gives you the id of the client. You can do `clients.get(clientId).then(client => …)` to get additional information about the client.

**Comment by inian** [comment]
Ah clients.get is what I was looking for. Thanks Jake!

**Comment by lmj0011** [comment]
@inian do you mind uploading some code on how this helped your case?

**Comment by inian** [comment]
@lmj0011 This is what I came up with

```
self.addEventListener("fetch", function(e) {
    if (e.clientId) {
        clients
        .get(e.clientId)
        .then((client) => {
            if(client.url == "page1.html" || client.url == "page2.html") {
                // respond to fetch request
            } else {
                // pass through
                e.respondWith(fetch(e.requestURL));
            }
        });
    } else {
        // pass through for navigation request
        e.respondWith(fetch(e.requestURL));
    }
});
```

**Comment by lmj0011** [comment]
Okay, that's what I'm doing. I looking to see if changed the registration scope

**Comment by inian** [comment]
Yup, declaring them at registration time was what i was looking for but this is good enough for me now..

**Comment by jakearchibald** [comment]
@inian you can't call `respondWith` asynchronously. It'd need to be more like:

```js
const pagesToControl = ["/page1.html", "/page2.html"];

self.addEventListener("fetch", function(e) {
  e.respondWith((function() {
    if (!e.clientId) return fetch(e.request);
    return clients.get(e.clientId).then(client => {
      const clientURL = new URL(client.url);

      if (!pagesToControl.includes(clientURL.pathname)) {
        return fetch(e.request);
      }

      // respond to fetch request
    });
  }()));
});
```
