### ISSUE TITLE
ExtendableMessageEventInit should either have default values for properties or mark properties required

### ISSUE THREAD

**Issue by smaug----** [w3c/ServiceWorker#988]
Otherwise it isn't clear what constructing the event does to the attributes in the event.

**Comment by smaug----** [comment]
Looks like ServiceWorkerMessageEvent has the same issue.

**Comment by annevk** [comment]
Looks like https://github.com/w3c/ServiceWorker/commit/8538a55d5eaa2f16fdaabffa23b9fc2bc0e302a5 fixed this.
