### ISSUE TITLE
Async functions and waitUntil

### ISSUE THREAD

**Issue by NekR** [w3c/ServiceWorker#997]
Given latest comments in https://github.com/w3c/ServiceWorker/issues/920 I got some thoughts that it would be good to pass `async function` directly into `fetch` event.  

My questions is: is `waitUntil` automatically called when `async function` is used as an listener?
I would expect this to work:

```js
self.addEventListener('fetch', async function(e) {
  const preload = await e.navigationPreload;

  if (preload) {
    e.respondWith(preload);
  }
});
```

with manual `waitUntil` it needs to be:

```js
self.addEventListener('fetch', async function(e) {
  let preload = e.navigationPreload;
  e.waitUntil(preload);
  preload = await preload;

  if (preload) {
    e.respondWith(preload);
  }
});
```

**Comment by domenic** [comment]
Dupe of https://github.com/w3c/ServiceWorker/issues/354, https://github.com/w3c/ServiceWorker/issues/256

**Comment by NekR** [comment]
Okay, sorry, it just feels a bit weird to call `waitUntil` there :-)
